import {validateTownRuntimeConfig,runtimeReadiness} from './core/config.js';import {TownWebService} from './core/service.js';import {connectTownWallet,sendAuthorityTransaction,installWalletInvalidation} from './core/wallet.js';import {bytes32FromText,encodeCreate,encodeJoin,encodeLeave,encodeRemoveMember,encodeAssignRole,encodeActivateSubscription,encodeGrantEntitlement,ROLE_ADMIN,ROLE_MODERATOR} from './core/abi.js';import {readCommunity,readMembership,readSubscription,readEntitlement,membershipLabel,subscriptionLabel,entitlementLabel} from './core/authority.js';import {idempotencyKey} from './core/state.js';
const $=s=>document.querySelector(s),status=$('#global-status'),txStatus=$('#transaction-status'),discoverResults=$('#discover-results'),feed=$('#feed'),authorityState=$('#authority-state'),accessState=$('#access-state');let config,service,wallet=null,nextCursor='';
function authorityKey(){const v=$('#authority-community-key').value.trim();if(!/^0x[0-9a-fA-F]{64}$/.test(v))throw Error('Canonical authority community key is required');return v.toLowerCase();}function text(el,value,cls=''){el.textContent=String(value);if(cls)el.className=cls;}function chip(label,value){const d=document.createElement('span');d.className='chip';d.textContent=label+': '+value;return d;}function setTx(v){text(txStatus,v,'status');}
async function loadConfig(){const r=await fetch('./runtime-config.json',{cache:'no-store'});if(!r.ok)throw Error('runtime config unavailable');config=validateTownRuntimeConfig(await r.json());service=new TownWebService(config);const ready=runtimeReadiness(config);text(status,ready.ready?'Runtime ready':'Repository preview: '+ready.missing.join(', '),'status');}
async function discover(q){discoverResults.replaceChildren();text(discoverResults,'Loading communities…');try{const p=await service.discoverCommunities(q);discoverResults.replaceChildren();const items=p.results||[];if(!items.length){text(discoverResults,'No public communities found','empty');return;}for(const item of items){const c=document.createElement('button');c.className='card';c.type='button';c.textContent=item.presentation?.title||item.sourceKey||item.id;c.addEventListener('click',()=>{const id=(item.sourceKey||item.id||'').replace(/^community:/,'');$('#community-id').value=id;openCommunity();});discoverResults.append(c);}}catch(e){text(discoverResults,e.message,'card error');}}
async function openCommunity(append=false){const id=$('#community-id').value.trim();if(!id)return;if(!append){feed.replaceChildren();text(feed,'Loading feed…');nextCursor='';}try{const p=await service.feed(id,{cursor:append?nextCursor:'',limit:20});if(!append)feed.replaceChildren();for(const post of p.items||[]){const c=document.createElement('article');c.className='card';const h=document.createElement('h3');h.textContent=String(post.ID||post.id);const meta=document.createElement('p');meta.className='muted';meta.textContent='author '+String(post.AuthorID||post.author_id||'')+' · revision '+String(post.Revision||post.revision||'');const a=document.createElement('p');a.textContent=String(post.ContentRef||post.content_ref||'off-chain content');const actions=document.createElement('div');actions.className='post-actions';for(const [label,val] of [['▲',1],['▼',-1]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>mutate(()=>service.vote(String(post.ID||post.id),val,idempotencyKey('vote')),'Vote'));actions.append(b);}c.append(h,meta,a,actions);feed.append(c);}if(!feed.children.length)text(feed,'No public posts yet','empty');nextCursor=p.next_cursor||p.nextCursor||'';$('#load-more').hidden=!nextCursor;await refreshAuthority(id);}catch(e){text(feed,e.message,'card error');}}
async function refreshAuthority(id){authorityState.replaceChildren();if(!wallet||!config.contracts.townAuthority){authorityState.append(chip('authority','connect wallet / materialize contract'));return;}let communityId;try{communityId=authorityKey();}catch(e){authorityState.append(chip('authority',e.message));return;}try{const [community,membership]=await Promise.all([readCommunity(globalThis.ethereum,config.contracts.townAuthority,communityId),readMembership(globalThis.ethereum,config.contracts.townAuthority,communityId,wallet.account)]);authorityState.append(chip('owner',community.owner),chip('membership',membershipLabel(membership.state)));}catch(e){authorityState.append(chip('authority error',e.message));}}
async function authority(data,label){try{setTx(label+' pending wallet review…');const hash=await sendAuthorityTransaction({ethereum:globalThis.ethereum,config,wallet,data});setTx(label+' submitted: '+hash);return hash;}catch(e){setTx(label+' failed: '+e.message);throw e;}}
async function mutate(fn,label){try{setTx(label+' pending…');const out=await fn();setTx(label+' complete');return out;}catch(e){setTx(label+' failed: '+e.message);throw e;}}
$('#api-token').addEventListener('input',e=>service?.setToken(e.target.value));
$('#connect-wallet').addEventListener('click',async()=>{try{wallet=await connectTownWallet(globalThis.ethereum,config.network.chainId);$('#connect-wallet').textContent=wallet.account.slice(0,8)+'…';setTx('Wallet connected on '+wallet.chainId);installWalletInvalidation(globalThis.ethereum,reason=>{wallet=null;$('#connect-wallet').textContent='Connect wallet';setTx('Wallet invalidated: '+reason);});await refreshAuthority($('#community-id').value.trim());}catch(e){setTx(e.message);}});
$('#discover-form').addEventListener('submit',e=>{e.preventDefault();discover($('#discover-query').value.trim());});$('#open-community').addEventListener('click',()=>openCommunity());$('#load-more').addEventListener('click',()=>openCommunity(true));
$('#join-community').addEventListener('click',()=>{try{return authority(encodeJoin(authorityKey()),'Join community')}catch(e){setTx(e.message);}});$('#leave-community').addEventListener('click',()=>{try{return authority(encodeLeave(authorityKey()),'Leave community')}catch(e){setTx(e.message);}});
$('#create-community-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),communityId=bytes32FromText(f.get('seed'));$('#authority-community-key').value=communityId;return authority(encodeCreate({communityId,metadataHash:bytes32FromText(f.get('metadata'))}),'Create community');});
$('#post-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate(()=>service.createPost($('#community-id').value.trim(),{ID:f.get('id'),ContentRef:f.get('contentRef'),SHA256:f.get('sha256'),Visibility:f.get('visibility')},idempotencyKey('post')),'Publish post').then(()=>openCommunity());});
$('#thread-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate(()=>service.createThread(f.get('postId'),{ID:f.get('id')},idempotencyKey('thread')),'Create thread');});
$('#comment-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate(()=>service.createComment(f.get('threadId'),{ID:f.get('id'),ParentID:f.get('parentId'),ContentRef:f.get('contentRef'),SHA256:f.get('sha256')},idempotencyKey('comment')),'Add comment');});
$('#report-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate(()=>service.report({RecordID:f.get('recordId'),CaseID:f.get('caseId'),CommunityID:$('#community-id').value.trim(),TargetKind:f.get('targetKind'),TargetID:f.get('targetId'),Reason:f.get('reason'),BodyRef:'',BodySHA256:''},idempotencyKey('report')),'Report');});
$('#moderate-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate(()=>service.moderate(f.get('caseId'),{RecordID:f.get('recordId'),Action:f.get('action'),Reason:f.get('reason'),BodyRef:'',BodySHA256:''},idempotencyKey('moderate')),'Moderation action');});$('#appeal-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate(()=>service.appeal(f.get('caseId'),{RecordID:f.get('recordId'),Reason:f.get('reason'),BodyRef:'',BodySHA256:''},idempotencyKey('appeal')),'Appeal');});
$('#admin-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=authorityKey(),member=f.get('member'),action=f.get('action');const data=action==='remove'?encodeRemoveMember(id,member):encodeAssignRole(id,action==='admin'?ROLE_ADMIN:ROLE_MODERATOR,member);authority(data,'Admin '+action);});
$('#access-form').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),id=authorityKey(),address=f.get('address'),seed=bytes32FromText(f.get('seed')),action=f.get('action');if(action==='subscription')return authority(encodeActivateSubscription(id,address,seed,0),'Activate subscription');if(action==='entitlement')return authority(encodeGrantEntitlement(id,address,seed,0),'Grant entitlement');accessState.replaceChildren();try{const [sub,ent]=await Promise.all([readSubscription(globalThis.ethereum,config.contracts.townAuthority,id,address),readEntitlement(globalThis.ethereum,config.contracts.townAuthority,id,address,seed)]);accessState.append(chip('subscription',subscriptionLabel(sub.state)),chip('subscription revision',sub.revision),chip('entitlement',entitlementLabel(ent.state)),chip('entitlement revision',ent.revision));}catch(err){accessState.append(chip('state error',err.message));}});
loadConfig().catch(e=>text(status,e.message,'status error'));
