import test from 'node:test';
import assert from 'node:assert/strict';
import {Interface,keccak256,toUtf8Bytes} from 'ethers';
import {setup,seller,attacker,b32,address} from './fixtures.mjs';
import {ABIS,fixedPrice} from '../src/authority.mjs';
const terms={method:'createListing',listingId:b32(2),sellerProfileId:b32(3),itemClass:keccak256(toUtf8Bytes('420/MARKET/ITEM/PHYSICAL_GOOD/V1')),assetRef:b32(4),policyId:b32(5),adapterId:b32(6),quoteAsset:address(100),unitPrice:'100',quantity:'10',expiresAt:0};
async function draft(t){const f=setup();t.after(()=>f.close());const store=await f.service.createStore(seller.address,{merchantId:b32(1),slug:'builder-store'}),p=await f.service.product(seller.address,store.store_id,{sku:'BUILD',description:'private',media:[],publishState:'draft'});return {...f,store,p};}
test('listing plans bind exact persisted product version/hash, canonical ABI, controller and finalized source',async t=>{const f=await draft(t),plan=await f.service.listingPlan(seller.address,f.store.store_id,f.p.product_id,{...terms,version:1});assert.equal(plan.intent.target,f.contracts.ListingRegistry420.address);assert.equal(plan.intent.args[4],f.p.metadata_hash);assert.equal(plan.intent.args[6],fixedPrice);assert.equal(plan.provenance.finalized,true);assert.equal(new Interface(ABIS.ListingRegistry420).parseTransaction({data:plan.intent.data}).name,'createListing');assert.equal(f.service.store(f.store.store_id).status,'draft');assert.equal(f.db.get('SELECT publish_state FROM products').publish_state,'draft');});
for(const [name,change,code] of [['wrong version',{version:2},'version_conflict'],['bad item',{itemClass:b32(77)},'invalid_item_class'],['zero quantity',{quantity:'0'},'invalid_quantity'],['expired',{expiresAt:1},'invalid_expiry'],['unknown field',{admin:true},'unknown_field']])test('listing prepare denies '+name,async t=>{const f=await draft(t);await assert.rejects(()=>f.service.listingPlan(seller.address,f.store.store_id,f.p.product_id,{...terms,version:1,...change}),e=>e.code===code);});
test('revision mutation rejects stale revision, other seller, quantity changes and inactive policy',async t=>{const f=await draft(t),args={...terms,method:'reviseListing',revision:2,version:1};f.listings.set(b32(2),{seller:seller.address.toLowerCase(),revision:'2',quantity:'10'});assert.equal((await f.service.listingPlan(seller.address,f.store.store_id,f.p.product_id,args)).revision,3);await assert.rejects(()=>f.service.listingPlan(seller.address,f.store.store_id,f.p.product_id,{...args,revision:1}),e=>e.code==='listing_binding');await assert.rejects(()=>f.service.listingPlan(seller.address,f.store.store_id,f.p.product_id,{...args,quantity:'11'}),e=>e.code==='quantity_immutable');f.source.policy=async()=>({policyActive:false,adapterActive:true});await assert.rejects(()=>f.service.listingPlan(seller.address,f.store.store_id,f.p.product_id,args),e=>e.code==='inactive_policy');f.source.policy=async()=>({policyActive:true,adapterActive:true});f.listings.get(b32(2)).seller=attacker.address;await assert.rejects(()=>f.service.listingPlan(seller.address,f.store.store_id,f.p.product_id,args),e=>e.code==='listing_binding');});
test('onboarding registration remains a plan, uses canonical register ABI, fails on existing identity or spoof',async t=>{const f=await draft(t);const values={merchantId:b32(9),profileId:b32(8),metadataHash:b32(7),payout:seller.address};await assert.rejects(()=>f.service.registration(seller.address,values),e=>e.code==='merchant_exists');f.source.merchant=async()=>({controller:address(0),active:false});assert.equal((await f.service.identity(seller.address,b32(9))).registered,false);const plan=await f.service.registration(seller.address,values);assert.equal(new Interface(ABIS.MerchantRegistry420).parseTransaction({data:plan.intent.data}).name,'register');assert.equal(plan.controller,seller.address.toLowerCase());assert.equal(plan.payout,seller.address.toLowerCase());assert.equal(f.db.all('SELECT * FROM stores').length,1);});
test('controller identity lookup resumes tenant and denies another wallet',async t=>{const f=await draft(t);assert.equal((await f.service.identity(seller.address,b32(1))).store.store_id,f.store.store_id);await assert.rejects(()=>f.service.identity(attacker.address,b32(1)),e=>e.code==='forbidden');});
test('builder sections obey scope, revocation and controller change; editors cannot prepare financial or listing writes',async t=>{const f=await draft(t);await f.service.delegate(seller.address,f.store.store_id,{wallet:attacker.address,scopes:['branding'],expiresAt:f.now()+10000});const view=await f.service.builder(attacker.address,f.store.store_id);assert.deepEqual(view.permissions,['branding']);assert.equal(view.products.length,0);assert.equal(view.media.length,0);assert.equal(view.categories.length,0);await assert.rejects(()=>f.service.listingPlan(attacker.address,f.store.store_id,f.p.product_id,{...terms,version:1}),e=>e.code==='forbidden');f.setController(address(500));await assert.rejects(()=>f.service.builder(attacker.address,f.store.store_id),e=>e.code==='forbidden');});
test('branding/category release isolates draft edits and private media until explicit publish, retains previous versions and survives reopen',async t=>{const f=await draft(t);await f.service.branding(seller.address,f.store.store_id,{version:1,theme:'light',description:'first design'});await f.service.category(seller.address,f.store.store_id,{slug:'first-category',order:0,visibility:'public'});await f.service.updateStore(seller.address,f.store.store_id,{version:1,status:'published',slug:f.store.slug});await f.service.branding(seller.address,f.store.store_id,{version:2,theme:'dark',description:'secret second design'});await f.service.category(seller.address,f.store.store_id,{slug:'private-category',order:1,visibility:'public'});assert.equal(f.service.publicStore(f.store.slug).public_description,'first design');assert.equal(f.service.publicStore(f.store.slug).categories.length,1);assert.equal(f.service.publicStores({query:'secret'}).items.length,0);await f.service.updateStore(seller.address,f.store.store_id,{version:2,status:'published',slug:f.store.slug});assert.equal(f.service.publicStore(f.store.slug).public_description,'secret second design');assert.equal((await f.service.builder(seller.address,f.store.store_id)).releases.length,2);await assert.rejects(()=>f.service.updateStore(seller.address,f.store.store_id,{version:2,status:'published',slug:f.store.slug}),e=>e.code==='version_conflict');});
test('stock reads are merchant-bound, authoritative and available for private drafts without publishing',async t=>{const f=await draft(t);f.listings.set(b32(2),{seller:seller.address.toLowerCase(),available:'4',inventory:{originalOffered:'10',reserved:'2',sold:'4',released:'0'}});const read=await f.service.merchantListing(seller.address,f.store.store_id,b32(2));assert.equal(read.listing.available,'4');assert.equal(read.provenance.finalized,true);await assert.rejects(()=>f.service.merchantListing(attacker.address,f.store.store_id,b32(2)),e=>e.code==='forbidden');f.listings.get(b32(2)).seller=attacker.address.toLowerCase();await assert.rejects(()=>f.service.merchantListing(seller.address,f.store.store_id,b32(2)),e=>e.code==='listing_tenant');});
test('store publish pins reviewed branding and every category version before the atomic release',async t=>{const f=await draft(t);const c=await f.service.category(seller.address,f.store.store_id,{slug:'reviewed',order:0,visibility:'public'});const publish={version:1,designVersion:1,categoryVersions:[{category_id:c.category_id,version:1}],slug:f.store.slug,status:'published'};await f.service.branding(seller.address,f.store.store_id,{version:1,theme:'dark',description:'changed behind preview'});await assert.rejects(()=>f.service.updateStore(seller.address,f.store.store_id,publish),e=>e.code==='design_conflict');publish.designVersion=2;await f.service.category(seller.address,f.store.store_id,{id:c.category_id,version:1,slug:'changed',order:1,visibility:'public'});await assert.rejects(()=>f.service.updateStore(seller.address,f.store.store_id,publish),e=>e.code==='design_conflict');assert.equal(f.db.all('SELECT * FROM store_releases').length,0);assert.equal(f.service.store(f.store.store_id).version,1);});
test('same uploaded object can be avatar and banner while product manifest duplicates remain rejected',async t=>{const f=await draft(t);const id='a'.repeat(64);f.db.run('INSERT INTO media VALUES(?,?,?,?,?,?)',id,f.store.store_id,'b'.repeat(64),Buffer.from('png'),'image/png',f.now());await f.service.branding(seller.address,f.store.store_id,{version:1,avatar:id,banner:id,theme:'light',description:'shared safe image'});assert.equal(f.db.get('SELECT avatar_object_id FROM store_branding').avatar_object_id,id);assert.throws(()=>f.service.mediaReferences(f.store.store_id,[id,id]),e=>e.code==='invalid_media_manifest');});
test('optional profile references can be zero without inventing verified identity or changing canonical register semantics',async t=>{const f=await draft(t);f.source.merchant=async()=>({controller:address(0),active:false});const plan=await f.service.registration(seller.address,{merchantId:b32(9),profileId:b32(0),metadataHash:b32(0),payout:seller.address});assert.equal(plan.intent.args[1],b32(0));assert.equal(plan.intent.args[2],b32(0));});
test('schema-1 published stores backfill releases atomically and retain released state after restart',async t=>{
  const {DatabaseSync}=await import('node:sqlite'),{readFileSync,mkdtempSync,rmSync}=await import('node:fs'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{Database}=await import('../src/database.mjs');
  const dir=mkdtempSync(join(tmpdir(),'commerce-migration-')),file=join(dir,'old.sqlite');t.after(()=>rmSync(dir,{recursive:true,force:true}));
  const old=new DatabaseSync(file);old.exec(readFileSync(new URL('../sql/001-commerce.sql',import.meta.url),'utf8'));old.prepare("INSERT INTO stores VALUES(?,?,?,'existing','published',0,0,2)").run('a'.repeat(64),b32(1),seller.address.toLowerCase());old.prepare("INSERT INTO store_branding VALUES(?,NULL,NULL,'light','Existing public description',3)").run('a'.repeat(64));old.close();
  const db=new Database(file);assert.equal(db.get('SELECT MAX(version) AS version FROM migrations').version,6);assert.equal(JSON.parse(db.get('SELECT branding FROM store_releases').branding).public_description,'Existing public description');db.close();const reopened=new Database(file);assert.equal(reopened.all('SELECT * FROM store_releases').length,1);reopened.close();
});
