import type { SqlExecutor420 } from './core-projections.js';
import type { QueryDirection420, QueryPage420 } from './query-layer.js';
import { decodePositionCursor420, encodePositionCursor420, normalizeLimit420 } from './query-layer.js';
import type { QueryRow420 } from './query-service.js';

export const AI_READ_SCHEMA_VERSION_420='420-ai-read-v1' as const;
const PRIVATE_KEY=/(payload|plaintext|prompt|document|dataset|token|secret|credential|privatekey|apikey|inputbytes|outputbytes|rawoutput)/i;
const PROVIDER_EVENTS=['ProviderRegistered','ProviderMetadataUpdated','ProviderSettlementUpdated','ProviderStakeReferenceUpdated','ProviderComputeReferenceUpdated','ProviderStateChanged'] as const;
const MODEL_EVENTS=['ModelRegistered','ModelUpdated','ModelStateChanged'] as const;
const VERSION_EVENTS=['ModelVersionRegistered','ModelVersionDeprecated'] as const;
const DEPLOYMENT_EVENTS=['DeploymentRegistered','DeploymentUpdated','DeploymentStateChanged'] as const;
const JOB_EVENTS=['JobCreated','FundingConfirmed','ComputeMatched','JobStatus','ResultCommitted','DisputeOpened','DisputeResolved','Funded','FundingBound','Released','Refunded','SettlementReferenceBound'] as const;
const POLICY_EVENTS=['PolicyConfigured'] as const;
const REPUTATION_EVENTS=['ReputationApplied','EvidenceApplied'] as const;
const PROVIDER_STATE=['NONE','REGISTERED','ACTIVE','SUSPENDED','RETIRED'] as const;
const MODEL_STATE=['NONE','ACTIVE','SUSPENDED','RETIRED'] as const;
const DEPLOYMENT_STATE=['NONE','REGISTERED','ACTIVE','SUSPENDED','RETIRED'] as const;
const JOB_STATE=['NONE','CREATED','FUNDED','MATCHED','ACCEPTED','RUNNING','RESULT_COMMITTED','VERIFIED','SETTLED','CANCELLED','EXPIRED','FAILED','DISPUTED','REFUNDED'] as const;
const ESCROW_STATE=['NONE','FUNDED','CLAIMABLE','REFUNDABLE','CLOSED'] as const;

export interface AiPageRequest420 { cursor?:string; limit?:number; direction?:QueryDirection420; }
export interface AiReadConfig420 { expectedChainId?:bigint; }

interface Position420 { blockNumber:string; blockHash:string; transactionHash:string; transactionIndex:number; logIndex:number; }
interface Event420 extends Position420 { eventName:string; fields:Record<string,unknown>; }

export interface AiProviderState420 extends Position420 { schemaVersion:typeof AI_READ_SCHEMA_VERSION_420; chainId:string; providerId:string; operatorAccount:string; settlementAccount:string; stakeRef:string; computeProviderRef:string; metadataHash:string|null; revision:string|null; state:string; authoritative:false; }
export interface AiModelState420 extends Position420 { schemaVersion:typeof AI_READ_SCHEMA_VERSION_420; chainId:string; modelId:string; creator:string; metadataHash:string; licensePolicyId:string; revision:string|null; state:string; authoritative:false; }
export interface AiModelVersionState420 extends Position420 { schemaVersion:typeof AI_READ_SCHEMA_VERSION_420; chainId:string; modelVersionId:string; modelId:string; version:string; artifactHash:string; artifactManifestHash:string; deprecated:boolean; authoritative:false; }
export interface AiDeploymentState420 extends Position420 { schemaVersion:typeof AI_READ_SCHEMA_VERSION_420; chainId:string; deploymentId:string; providerId:string; modelVersionId:string; computeOfferRef:string; endpointManifestHash:string|null; revision:string|null; state:string; authoritative:false; }
export interface AiPolicyState420 extends Position420 { schemaVersion:typeof AI_READ_SCHEMA_VERSION_420; chainId:string; policyId:string; revision:string; workloadClass:string; verificationProfileId:string; maxSpend420:string; maxDeadlineSeconds:string; active:boolean; privacyPolicyId:null; servicePricingPolicyId:null; authoritative:false; }
export interface AiReputationState420 extends Position420 { schemaVersion:typeof AI_READ_SCHEMA_VERSION_420; chainId:string; providerId:string; completed:string; disputed:string; upheld:string; failed:string; latestEvidenceId:string|null; latestOutcome:string|null; authoritative:false; }
export interface AiJobState420 extends Position420 {
  schemaVersion:typeof AI_READ_SCHEMA_VERSION_420; chainId:string; jobId:string; requester:string; modelVersionId:string; workloadClass:string; maxSpend:string; deadline:string;
  fundingRef:string|null; fundedAmount:string|null; computeRequestId:string|null; computeJobId:string|null; providerId:string|null; status:string;
  resultHash:string|null; resultManifestHash:string|null; disputeRef:string|null; disputeUpheld:boolean|null; resolutionRef:string|null;
  payer:string|null; escrowProviderId:string|null; escrowAmount:string|null; vaultRef:string|null; beneficiary:string|null;
  releasedTo:string|null; releasedAmount:string|null; refundedTo:string|null; refundedAmount:string|null; settlementRef:string|null; escrowState:string|null;
  authoritative:false;
}

function rows(result:unknown):QueryRow420[]{if(!result||typeof result!=='object'||!Array.isArray((result as {rows?:QueryRow420[]}).rows)) throw new Error('AI read query result invalid');return (result as {rows:QueryRow420[]}).rows;}
function safeObject(value:unknown):Record<string,unknown>{let v=value;if(typeof v==='string'){try{v=JSON.parse(v);}catch{throw new Error('AI event fields invalid');}}if(!v||typeof v!=='object'||Array.isArray(v)) throw new Error('AI event fields invalid');const obj=v as Record<string,unknown>;for(const [k,x] of Object.entries(obj)){if(PRIVATE_KEY.test(k)) throw new Error('AI private field leakage blocked: '+k);if(x&&typeof x==='object') safeObject(x);}return obj;}
function text(value:unknown,name:string):string{if(typeof value!=='string'||!value) throw new Error('AI field missing: '+name);return value.toLowerCase();}
function uint(value:unknown,name:string):string{const s=String(value??'');if(!/^\d+$/.test(s)) throw new Error('AI numeric field invalid: '+name);return s;}
function bool(value:unknown,name:string):boolean{if(typeof value!=='boolean') throw new Error('AI boolean field invalid: '+name);return value;}
function rowInt(row:QueryRow420,name:string):number{const v=row[name];if(typeof v==='number'&&Number.isSafeInteger(v)&&v>=0)return v;if(typeof v==='string'&&/^\d+$/.test(v))return Number(v);throw new Error('AI projection position invalid: '+name);}
function rowText(row:QueryRow420,name:string):string{const v=row[name];if(typeof v!=='string'||!v)throw new Error('AI projection provenance missing: '+name);return v;}
function event(row:QueryRow420):Event420{return {eventName:rowText(row,'event_name'),fields:safeObject(row.fields),blockNumber:rowText(row,'block_number'),blockHash:rowText(row,'block_hash'),transactionHash:rowText(row,'tx_hash'),transactionIndex:rowInt(row,'tx_index'),logIndex:rowInt(row,'log_index')};}
function enumName(value:unknown,names:readonly string[],name:string):string{const n=Number(uint(value,name));if(!Number.isSafeInteger(n)||n<0||n>=names.length)throw new Error('AI enum invalid: '+name);return names[n]!;}
function assertChain(chainId:bigint,config:AiReadConfig420={}){if(chainId<=0n)throw new Error('AI chain id invalid');if(config.expectedChainId!==undefined&&chainId!==config.expectedChainId)throw new Error('AI network mismatch');}
function pos(e:Position420){return {blockNumber:e.blockNumber,blockHash:e.blockHash,transactionHash:e.transactionHash,transactionIndex:e.transactionIndex,logIndex:e.logIndex};}
async function history(db:SqlExecutor420,chainId:bigint,idField:string,id:string,names:readonly string[],config:AiReadConfig420):Promise<Event420[]>{
  assertChain(chainId,config); const normalized=id.trim().toLowerCase(); if(!normalized)throw new Error('AI object id required');
  return rows(await db.query(`select * from idx_protocol_events where chain_id=$1 and protocol='420AI' and fields->>$2=$3 and event_name=any($4::text[]) order by block_number asc, tx_index asc, log_index asc`,[chainId.toString(),idField,normalized,names])).map(event);
}
async function listIds(db:SqlExecutor420,chainId:bigint,idField:string,names:readonly string[],request:AiPageRequest420,config:AiReadConfig420):Promise<{ids:string[];nextCursor:string|null}>{
  assertChain(chainId,config); const limit=normalizeLimit420(request.limit),direction=request.direction??'desc',params:unknown[]=[chainId.toString(),idField,names]; let where='';
  if(request.cursor){const c=decodePositionCursor420(request.cursor),cmp=direction==='asc'?'>':'<';params.push(c.blockNumber.toString(),c.txIndex,c.logIndex);where=`where (block_number,tx_index,log_index) ${cmp} ($4,$5,$6)`;}
  params.push(limit+1); const n=params.length;
  const result=rows(await db.query(`with latest as (select distinct on (fields->>$2) fields->>$2 as object_id, block_number, tx_index, log_index from idx_protocol_events where chain_id=$1 and protocol='420AI' and event_name=any($3::text[]) and fields ? $2 order by fields->>$2, block_number desc, tx_index desc, log_index desc) select * from latest ${where} order by block_number ${direction}, tx_index ${direction}, log_index ${direction} limit $${n}`,params));
  const page=result.slice(0,limit),last=page.at(-1),next=result.length>limit&&last?encodePositionCursor420({blockNumber:BigInt(String(last.block_number)),txIndex:rowInt(last,'tx_index'),logIndex:rowInt(last,'log_index')}):null;
  return {ids:page.map((r)=>text(r.object_id,'object_id')),nextCursor:next};
}
async function states<T>(ids:string[],load:(id:string)=>Promise<T|null>,nextCursor:string|null):Promise<QueryPage420<T>>{const items:T[]=[];for(const id of ids){const state=await load(id);if(!state)throw new Error('AI indexed object missing canonical creation event');items.push(state);}return {items,nextCursor};}

export async function aiProviderState420(db:SqlExecutor420,chainId:bigint,providerId:string,config:AiReadConfig420={}):Promise<AiProviderState420|null>{
  const events=await history(db,chainId,'providerId',providerId,PROVIDER_EVENTS,config);if(!events.length)return null;let s:AiProviderState420|null=null;
  for(const e of events){const f=e.fields;if(e.eventName==='ProviderRegistered')s={schemaVersion:AI_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),providerId:text(f.providerId,'providerId'),operatorAccount:text(f.operatorAccount,'operatorAccount'),settlementAccount:text(f.settlementAccount,'settlementAccount'),stakeRef:text(f.stakeRef,'stakeRef'),computeProviderRef:text(f.computeProviderRef,'computeProviderRef'),metadataHash:null,revision:null,state:'REGISTERED',...pos(e),authoritative:false};else if(!s)throw new Error('AI provider event precedes registration');else if(e.eventName==='ProviderMetadataUpdated'){s.metadataHash=text(f.metadataHash,'metadataHash');s.revision=uint(f.revision,'revision');}else if(e.eventName==='ProviderSettlementUpdated'){s.settlementAccount=text(f.settlementAccount,'settlementAccount');s.revision=uint(f.revision,'revision');}else if(e.eventName==='ProviderStakeReferenceUpdated'){s.stakeRef=text(f.stakeRef,'stakeRef');s.revision=uint(f.revision,'revision');}else if(e.eventName==='ProviderComputeReferenceUpdated'){s.computeProviderRef=text(f.computeProviderRef,'computeProviderRef');s.revision=uint(f.revision,'revision');}else if(e.eventName==='ProviderStateChanged'){s.state=enumName(f.newState,PROVIDER_STATE,'newState');s.revision=uint(f.revision,'revision');}if(s)Object.assign(s,pos(e));}
  return s;
}
export async function aiModelState420(db:SqlExecutor420,chainId:bigint,modelId:string,config:AiReadConfig420={}):Promise<AiModelState420|null>{const events=await history(db,chainId,'modelId',modelId,MODEL_EVENTS,config);if(!events.length)return null;let s:AiModelState420|null=null;for(const e of events){const f=e.fields;if(e.eventName==='ModelRegistered')s={schemaVersion:AI_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),modelId:text(f.modelId,'modelId'),creator:text(f.creator,'creator'),metadataHash:text(f.metadataHash,'metadataHash'),licensePolicyId:text(f.licensePolicyId,'licensePolicyId'),revision:null,state:'ACTIVE',...pos(e),authoritative:false};else if(!s)throw new Error('AI model event precedes registration');else if(e.eventName==='ModelUpdated'){s.metadataHash=text(f.metadataHash,'metadataHash');s.licensePolicyId=text(f.licensePolicyId,'licensePolicyId');s.revision=uint(f.revision,'revision');}else if(e.eventName==='ModelStateChanged'){s.state=enumName(f.newState,MODEL_STATE,'newState');s.revision=uint(f.revision,'revision');}if(s)Object.assign(s,pos(e));}return s;}
export async function aiModelVersionState420(db:SqlExecutor420,chainId:bigint,modelVersionId:string,config:AiReadConfig420={}):Promise<AiModelVersionState420|null>{const events=await history(db,chainId,'modelVersionId',modelVersionId,VERSION_EVENTS,config);if(!events.length)return null;let s:AiModelVersionState420|null=null;for(const e of events){const f=e.fields;if(e.eventName==='ModelVersionRegistered')s={schemaVersion:AI_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),modelVersionId:text(f.modelVersionId,'modelVersionId'),modelId:text(f.modelId,'modelId'),version:uint(f.version,'version'),artifactHash:text(f.artifactHash,'artifactHash'),artifactManifestHash:text(f.artifactManifestHash,'artifactManifestHash'),deprecated:false,...pos(e),authoritative:false};else if(!s)throw new Error('AI model version event precedes registration');else if(e.eventName==='ModelVersionDeprecated')s.deprecated=true;if(s)Object.assign(s,pos(e));}return s;}
export async function aiDeploymentState420(db:SqlExecutor420,chainId:bigint,deploymentId:string,config:AiReadConfig420={}):Promise<AiDeploymentState420|null>{const events=await history(db,chainId,'deploymentId',deploymentId,DEPLOYMENT_EVENTS,config);if(!events.length)return null;let s:AiDeploymentState420|null=null;for(const e of events){const f=e.fields;if(e.eventName==='DeploymentRegistered')s={schemaVersion:AI_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),deploymentId:text(f.deploymentId,'deploymentId'),providerId:text(f.providerId,'providerId'),modelVersionId:text(f.modelVersionId,'modelVersionId'),computeOfferRef:text(f.computeOfferRef,'computeOfferRef'),endpointManifestHash:null,revision:null,state:'REGISTERED',...pos(e),authoritative:false};else if(!s)throw new Error('AI deployment event precedes registration');else if(e.eventName==='DeploymentUpdated'){s.endpointManifestHash=text(f.endpointManifestHash,'endpointManifestHash');s.revision=uint(f.revision,'revision');}else if(e.eventName==='DeploymentStateChanged'){s.state=enumName(f.newState,DEPLOYMENT_STATE,'newState');s.revision=uint(f.revision,'revision');}if(s)Object.assign(s,pos(e));}return s;}
export async function aiJobState420(db:SqlExecutor420,chainId:bigint,jobId:string,config:AiReadConfig420={}):Promise<AiJobState420|null>{const events=await history(db,chainId,'jobId',jobId,JOB_EVENTS,config);if(!events.length)return null;let s:AiJobState420|null=null;for(const e of events){const f=e.fields;if(e.eventName==='JobCreated')s={schemaVersion:AI_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),jobId:text(f.jobId,'jobId'),requester:text(f.requester,'requester'),modelVersionId:text(f.modelVersionId,'modelVersionId'),workloadClass:text(f.workloadClass,'workloadClass'),maxSpend:uint(f.maxSpend,'maxSpend'),deadline:uint(f.deadline,'deadline'),fundingRef:null,fundedAmount:null,computeRequestId:null,computeJobId:null,providerId:null,status:'CREATED',resultHash:null,resultManifestHash:null,disputeRef:null,disputeUpheld:null,resolutionRef:null,payer:null,escrowProviderId:null,escrowAmount:null,vaultRef:null,beneficiary:null,releasedTo:null,releasedAmount:null,refundedTo:null,refundedAmount:null,settlementRef:null,escrowState:null,...pos(e),authoritative:false};else if(!s)throw new Error('AI job event precedes creation');else if(e.eventName==='FundingConfirmed'){s.fundingRef=text(f.fundingRef,'fundingRef');s.fundedAmount=uint(f.amount,'amount');}else if(e.eventName==='ComputeMatched'){s.computeRequestId=text(f.computeRequestId,'computeRequestId');s.computeJobId=text(f.computeJobId,'computeJobId');s.providerId=text(f.providerId,'providerId');}else if(e.eventName==='JobStatus')s.status=enumName(f.newStatus,JOB_STATE,'newStatus');else if(e.eventName==='ResultCommitted'){s.resultHash=text(f.resultHash,'resultHash');s.resultManifestHash=text(f.resultManifestHash,'resultManifestHash');}else if(e.eventName==='DisputeOpened')s.disputeRef=text(f.disputeRef,'disputeRef');else if(e.eventName==='DisputeResolved'){s.disputeUpheld=bool(f.upheld,'upheld');s.resolutionRef=text(f.resolutionRef,'resolutionRef');}else if(e.eventName==='Funded'){s.payer=text(f.payer,'payer');s.escrowProviderId=text(f.providerId,'providerId');s.escrowAmount=uint(f.amount,'amount');}else if(e.eventName==='FundingBound'){s.vaultRef=text(f.vaultRef,'vaultRef');s.fundingRef=text(f.fundingRef,'fundingRef');s.beneficiary=text(f.beneficiary,'beneficiary');s.escrowAmount=uint(f.amount,'amount');}else if(e.eventName==='Released'){s.releasedTo=text(f.to,'to');s.releasedAmount=uint(f.amount,'amount');}else if(e.eventName==='Refunded'){s.refundedTo=text(f.to,'to');s.refundedAmount=uint(f.amount,'amount');}else if(e.eventName==='SettlementReferenceBound'){s.settlementRef=text(f.settlementRef,'settlementRef');s.escrowState=enumName(f.state,ESCROW_STATE,'state');}if(s)Object.assign(s,pos(e));}return s;}

export async function aiProviders420(db:SqlExecutor420,chainId:bigint,request:AiPageRequest420={},config:AiReadConfig420={}):Promise<QueryPage420<AiProviderState420>>{const page=await listIds(db,chainId,'providerId',PROVIDER_EVENTS,request,config);return states(page.ids,(id)=>aiProviderState420(db,chainId,id,config),page.nextCursor);}
export async function aiModels420(db:SqlExecutor420,chainId:bigint,request:AiPageRequest420={},config:AiReadConfig420={}):Promise<QueryPage420<AiModelState420>>{const page=await listIds(db,chainId,'modelId',MODEL_EVENTS,request,config);return states(page.ids,(id)=>aiModelState420(db,chainId,id,config),page.nextCursor);}
export async function aiModelVersions420(db:SqlExecutor420,chainId:bigint,request:AiPageRequest420={},config:AiReadConfig420={}):Promise<QueryPage420<AiModelVersionState420>>{const page=await listIds(db,chainId,'modelVersionId',VERSION_EVENTS,request,config);return states(page.ids,(id)=>aiModelVersionState420(db,chainId,id,config),page.nextCursor);}
export async function aiDeployments420(db:SqlExecutor420,chainId:bigint,request:AiPageRequest420={},config:AiReadConfig420={}):Promise<QueryPage420<AiDeploymentState420>>{const page=await listIds(db,chainId,'deploymentId',DEPLOYMENT_EVENTS,request,config);return states(page.ids,(id)=>aiDeploymentState420(db,chainId,id,config),page.nextCursor);}
export async function aiPolicyState420(db:SqlExecutor420,chainId:bigint,policyId:string,config:AiReadConfig420={}):Promise<AiPolicyState420|null>{const events=await history(db,chainId,'policyId',policyId,POLICY_EVENTS,config);if(!events.length)return null;let s:AiPolicyState420|null=null;for(const e of events){const f=e.fields;s={schemaVersion:AI_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),policyId:text(f.policyId,'policyId'),revision:uint(f.revision,'revision'),workloadClass:text(f.workloadClass,'workloadClass'),verificationProfileId:text(f.verificationProfileId,'verificationProfileId'),maxSpend420:uint(f.maxSpend420,'maxSpend420'),maxDeadlineSeconds:uint(f.maxDeadlineSeconds,'maxDeadlineSeconds'),active:bool(f.active,'active'),privacyPolicyId:null,servicePricingPolicyId:null,...pos(e),authoritative:false};}return s;}
export async function aiReputationState420(db:SqlExecutor420,chainId:bigint,providerId:string,config:AiReadConfig420={}):Promise<AiReputationState420|null>{const events=await history(db,chainId,'providerId',providerId,REPUTATION_EVENTS,config);if(!events.length)return null;let s:AiReputationState420|null=null;for(const e of events){const f=e.fields;if(e.eventName==='ReputationApplied'){const previous=s as AiReputationState420|null;s={schemaVersion:AI_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),providerId:text(f.providerId,'providerId'),completed:uint(f.completed,'completed'),disputed:uint(f.disputed,'disputed'),upheld:uint(f.upheld,'upheld'),failed:previous?.failed??'0',latestEvidenceId:previous?.latestEvidenceId??null,latestOutcome:previous?.latestOutcome??null,...pos(e),authoritative:false};}else{s={schemaVersion:AI_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),providerId:text(f.providerId,'providerId'),completed:uint(f.completed,'completed'),disputed:uint(f.disputed,'disputed'),upheld:uint(f.upheld,'upheld'),failed:uint(f.failed,'failed'),latestEvidenceId:text(f.evidenceId,'evidenceId'),latestOutcome:text(f.outcome,'outcome'),...pos(e),authoritative:false};}}return s;}
export async function aiJobs420(db:SqlExecutor420,chainId:bigint,request:AiPageRequest420={},config:AiReadConfig420={}):Promise<QueryPage420<AiJobState420>>{const page=await listIds(db,chainId,'jobId',JOB_EVENTS,request,config);return states(page.ids,(id)=>aiJobState420(db,chainId,id,config),page.nextCursor);}
export async function aiPolicies420(db:SqlExecutor420,chainId:bigint,request:AiPageRequest420={},config:AiReadConfig420={}):Promise<QueryPage420<AiPolicyState420>>{const page=await listIds(db,chainId,'policyId',POLICY_EVENTS,request,config);return states(page.ids,(id)=>aiPolicyState420(db,chainId,id,config),page.nextCursor);}
export async function aiReputations420(db:SqlExecutor420,chainId:bigint,request:AiPageRequest420={},config:AiReadConfig420={}):Promise<QueryPage420<AiReputationState420>>{const page=await listIds(db,chainId,'providerId',REPUTATION_EVENTS,request,config);return states(page.ids,(id)=>aiReputationState420(db,chainId,id,config),page.nextCursor);}
