import type { SqlExecutor420 } from './core-projections.js';
import type { QueryRow420 } from './query-service.js';

export const COMPUTE_READ_SCHEMA_VERSION_420='420-compute-read-v1' as const;
const PRIVATE=/(payload|plaintext|document|dataset|token|secret|credential|privatekey|apikey|inputbytes|outputbytes|rawoutput)/i;
interface Position420{blockNumber:string;blockHash:string;transactionHash:string;transactionIndex:number;logIndex:number;}
interface Event420 extends Position420{eventName:string;fields:Record<string,unknown>;}
function rows(v:unknown):QueryRow420[]{if(!v||typeof v!=='object'||!Array.isArray((v as any).rows))throw new Error('Compute read query invalid');return (v as any).rows;}
function safe(v:unknown):Record<string,unknown>{if(typeof v==='string')v=JSON.parse(v);if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('Compute event fields invalid');for(const [k,x] of Object.entries(v as any)){if(PRIVATE.test(k))throw new Error('Compute private field leakage blocked: '+k);if(x&&typeof x==='object')safe(x);}return v as any;}
function str(v:unknown,n:string){if(typeof v!=='string'||!v)throw new Error('Compute field missing: '+n);return v.toLowerCase();}
function uint(v:unknown,n:string){const s=String(v??'');if(!/^\d+$/.test(s))throw new Error('Compute numeric field invalid: '+n);return s;}
function bool(v:unknown,n:string){if(typeof v!=='boolean')throw new Error('Compute boolean field invalid: '+n);return v;}
function ri(r:QueryRow420,n:string){const v=r[n];if(typeof v==='number'&&Number.isSafeInteger(v))return v;if(typeof v==='string'&&/^\d+$/.test(v))return Number(v);throw new Error('Compute position invalid: '+n);}
function rt(r:QueryRow420,n:string){const v=r[n];if(typeof v!=='string'||!v)throw new Error('Compute provenance missing: '+n);return v;}
function event(r:QueryRow420):Event420{return{eventName:rt(r,'event_name'),fields:safe(r.fields),blockNumber:rt(r,'block_number'),blockHash:rt(r,'block_hash'),transactionHash:rt(r,'tx_hash'),transactionIndex:ri(r,'tx_index'),logIndex:ri(r,'log_index')};}
function pos(e:Position420){return{blockNumber:e.blockNumber,blockHash:e.blockHash,transactionHash:e.transactionHash,transactionIndex:e.transactionIndex,logIndex:e.logIndex};}
async function history(db:SqlExecutor420,chainId:bigint,idField:string,id:string,names:readonly string[]):Promise<Event420[]>{if(chainId<=0n)throw new Error('Compute chain id invalid');if(!/^0x[0-9a-fA-F]{64}$/.test(id))throw new Error('Compute object id invalid');return rows(await db.query(`select * from idx_protocol_events where chain_id=$1 and protocol='420Compute' and fields->>$2=$3 and event_name=any($4::text[]) order by block_number asc, tx_index asc, log_index asc`,[chainId.toString(),idField,id.toLowerCase(),names])).map(event);}

const JOB_STATUS_420=['NONE','CREATED','FUNDED','MATCHED','ACCEPTED','RUNNING','RESULT_COMMITTED','VERIFIED','SETTLED','CANCELLED','EXPIRED','FAILED','DISPUTED','REFUNDED'] as const;
export interface ComputeJobState420 extends Position420{schemaVersion:typeof COMPUTE_READ_SCHEMA_VERSION_420;chainId:string;jobId:string;requestId:string;owner:string;manifestHash:string;workloadType:string;status:string;revision:string;worker:string|null;assignmentRef:string|null;resultCommitment:string|null;verifier:string|null;verificationRef:string|null;approved:boolean|null;authoritative:false;}
export interface ComputeRequestState420 extends Position420{schemaVersion:typeof COMPUTE_READ_SCHEMA_VERSION_420;chainId:string;requestId:string;owner:string;revision:string;actor:string;commitment:string;predecessorCommitment:string;status:string;authoritative:false;}
export interface ComputeWorkerState420 extends Position420{schemaVersion:typeof COMPUTE_READ_SCHEMA_VERSION_420;chainId:string;workerId:string;nodeId:string;resourceId:string;operator:string;executionSigner:string;serial:string;revision:string;commitment:string|null;authoritative:false;}
export interface ComputeVerifierState420 extends Position420{schemaVersion:typeof COMPUTE_READ_SCHEMA_VERSION_420;chainId:string;verifierId:string;authority:string;registrationManifestHash:string;serial:string;revision:string;commitment:string|null;authoritative:false;}
export interface ComputeResearchProjectState420 extends Position420{schemaVersion:typeof COMPUTE_READ_SCHEMA_VERSION_420;chainId:string;projectId:string;owner:string;researchDomain:string;revision:string;projectCommitment:string;acceptingNewWork:boolean;retired:boolean;authoritative:false;}
export interface ComputeRewardState420 extends Position420{schemaVersion:typeof COMPUTE_READ_SCHEMA_VERSION_420;chainId:string;rewardId:string;contributionId:string;poolId:string;beneficiary:string;metricId:string;contributionAmount:string;amount:string;rewardPolicyId:string;rewardPolicyRevision:string;poolFundingSnapshot:string;authoritative:false;}

export async function computeJobState420(db:SqlExecutor420,chainId:bigint,id:string):Promise<ComputeJobState420|null>{const es=await history(db,chainId,'jobId',id,['JobCreated','JobTransition','WorkerAssigned','ResultRecorded','VerifierDecision']);if(!es.length)return null;let s:ComputeJobState420|null=null;for(const e of es){const f=e.fields;if(e.eventName==='JobCreated')s={schemaVersion:COMPUTE_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),jobId:str(f.jobId,'jobId'),requestId:str(f.requestId,'requestId'),owner:str(f.owner,'owner'),manifestHash:str(f.manifestHash,'manifestHash'),workloadType:str(f.workloadType,'workloadType'),status:'CREATED',revision:'1',worker:null,assignmentRef:null,resultCommitment:null,verifier:null,verificationRef:null,approved:null,...pos(e),authoritative:false};else{if(!s)throw new Error('Compute job event precedes creation');if(e.eventName==='JobTransition'){const n=Number(uint(f.current,'current'));if(!Number.isSafeInteger(n)||n<0||n>=JOB_STATUS_420.length)throw new Error('Compute job status invalid');s.status=JOB_STATUS_420[n]!;s.revision=uint(f.currentRevision,'currentRevision');}else if(e.eventName==='WorkerAssigned'){s.worker=str(f.worker,'worker');s.assignmentRef=str(f.assignmentRef,'assignmentRef');}else if(e.eventName==='ResultRecorded')s.resultCommitment=str(f.resultCommitment,'resultCommitment');else if(e.eventName==='VerifierDecision'){s.verifier=str(f.verifier,'verifier');s.verificationRef=str(f.decisionRef,'decisionRef');s.approved=bool(f.approved,'approved');}Object.assign(s,pos(e));}}return s;}
export async function computeRequestState420(db:SqlExecutor420,chainId:bigint,id:string):Promise<ComputeRequestState420|null>{const es=await history(db,chainId,'requestId',id,['RequestRevision']);if(!es.length)return null;let s:ComputeRequestState420|null=null;for(const e of es){const f=e.fields;s={schemaVersion:COMPUTE_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),requestId:str(f.requestId,'requestId'),owner:str(f.owner,'owner'),revision:uint(f.revision,'revision'),actor:str(f.actor,'actor'),commitment:str(f.commitment,'commitment'),predecessorCommitment:str(f.predecessorCommitment,'predecessorCommitment'),status:uint(f.status,'status'),...pos(e),authoritative:false};}return s;}
export async function computeWorkerState420(db:SqlExecutor420,chainId:bigint,id:string):Promise<ComputeWorkerState420|null>{const es=await history(db,chainId,'workerId',id,['WorkerRegistered','WorkerRevised']);if(!es.length)return null;let s:ComputeWorkerState420|null=null;for(const e of es){const f=e.fields;if(e.eventName==='WorkerRegistered')s={schemaVersion:COMPUTE_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),workerId:str(f.workerId,'workerId'),nodeId:str(f.nodeId,'nodeId'),resourceId:str(f.resourceId,'resourceId'),operator:str(f.operator,'operator'),executionSigner:str(f.executionSigner,'executionSigner'),serial:uint(f.serial,'serial'),revision:'1',commitment:null,...pos(e),authoritative:false};else{if(!s)throw new Error('Compute worker revision precedes registration');s.revision=uint(f.newRevision,'newRevision');s.commitment=str(f.newCommitment,'newCommitment');Object.assign(s,pos(e));}}return s;}
export async function computeVerifierState420(db:SqlExecutor420,chainId:bigint,id:string):Promise<ComputeVerifierState420|null>{const es=await history(db,chainId,'verifierId',id,['VerifierRegistered','VerifierRevised']);if(!es.length)return null;let s:ComputeVerifierState420|null=null;for(const e of es){const f=e.fields;if(e.eventName==='VerifierRegistered')s={schemaVersion:COMPUTE_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),verifierId:str(f.verifierId,'verifierId'),authority:str(f.authority,'authority'),registrationManifestHash:str(f.registrationManifestHash,'registrationManifestHash'),serial:uint(f.serial,'serial'),revision:'1',commitment:null,...pos(e),authoritative:false};else{if(!s)throw new Error('Compute verifier revision precedes registration');s.revision=uint(f.newRevision,'newRevision');s.commitment=str(f.newCommitment,'newCommitment');Object.assign(s,pos(e));}}return s;}
export async function computeResearchProjectState420(db:SqlExecutor420,chainId:bigint,id:string):Promise<ComputeResearchProjectState420|null>{const es=await history(db,chainId,'projectId',id,['ResearchProjectRegistered','ResearchProjectRevised','ResearchProjectAcceptanceSet','ResearchProjectRetired']);if(!es.length)return null;let s:ComputeResearchProjectState420|null=null;for(const e of es){const f=e.fields;if(e.eventName==='ResearchProjectRegistered')s={schemaVersion:COMPUTE_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),projectId:str(f.projectId,'projectId'),owner:str(f.owner,'owner'),researchDomain:str(f.researchDomain,'researchDomain'),revision:uint(f.revision,'revision'),projectCommitment:str(f.projectCommitment,'projectCommitment'),acceptingNewWork:true,retired:false,...pos(e),authoritative:false};else{if(!s)throw new Error('Compute research event precedes registration');s.revision=uint(f.currentRevision??f.revision,'revision');s.projectCommitment=str(f.projectCommitment,'projectCommitment');if(e.eventName==='ResearchProjectAcceptanceSet')s.acceptingNewWork=bool(f.acceptingNewWork,'acceptingNewWork');if(e.eventName==='ResearchProjectRetired'){s.retired=true;s.acceptingNewWork=false;}Object.assign(s,pos(e));}}return s;}
export async function computeRewardState420(db:SqlExecutor420,chainId:bigint,id:string):Promise<ComputeRewardState420|null>{const es=await history(db,chainId,'rewardId',id,['UsefulRewardAccounted']);if(!es.length)return null;const e=es[0]!,f=e.fields;return{schemaVersion:COMPUTE_READ_SCHEMA_VERSION_420,chainId:chainId.toString(),rewardId:str(f.rewardId,'rewardId'),contributionId:str(f.contributionId,'contributionId'),poolId:str(f.poolId,'poolId'),beneficiary:str(f.beneficiary,'beneficiary'),metricId:str(f.metricId,'metricId'),contributionAmount:uint(f.contributionAmount,'contributionAmount'),amount:uint(f.amount,'amount'),rewardPolicyId:str(f.rewardPolicyId,'rewardPolicyId'),rewardPolicyRevision:uint(f.rewardPolicyRevision,'rewardPolicyRevision'),poolFundingSnapshot:uint(f.poolFundingSnapshot,'poolFundingSnapshot'),...pos(e),authoritative:false};}
