import type {SqlExecutor420} from './core-projections.js';import type {QueryRow420} from './query-service.js';
export const COMPUTE_ANALYTICS_SCHEMA_420='420-compute-analytics-v1' as const;
export interface ComputeAnalyticsRange420{fromBlock:bigint;toBlock:bigint;}
export interface ComputeMetricTotal420{metricId:string;contributionAmount:string;rewardAmount:string;rewardCount:string;}
export interface ComputeHistoricalAnalytics420{schemaVersion:typeof COMPUTE_ANALYTICS_SCHEMA_420;chainId:string;fromBlock:string;toBlock:string;jobsCreated:string;jobsVerified:string;jobsSettled:string;jobsFailed:string;rewardCount:string;totalRewardAmount:string;uniqueRewardBeneficiaries:string;metrics:readonly ComputeMetricTotal420[];authoritative:false;}
function rows(v:unknown):QueryRow420[]{if(!v||typeof v!=='object'||!Array.isArray((v as any).rows))throw new Error('Compute analytics query invalid');return (v as any).rows;}
function fields(v:unknown):Record<string,unknown>{if(typeof v==='string')v=JSON.parse(v);if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('Compute analytics event fields invalid');return v as any;}
function text(v:unknown,n:string){if(typeof v!=='string'||!v)throw new Error('Compute analytics field missing: '+n);return v.toLowerCase();}
function uint(v:unknown,n:string){const s=String(v??'');if(!/^\d+$/.test(s))throw new Error('Compute analytics numeric field invalid: '+n);return BigInt(s);}
function plus(a:bigint,b:bigint,n:string){const c=a+b;if(c<0n||c>=(1n<<256n))throw new Error('Compute analytics overflow: '+n);return c;}
export async function computeHistoricalAnalytics420(db:SqlExecutor420,chainId:bigint,range:ComputeAnalyticsRange420):Promise<ComputeHistoricalAnalytics420>{
 if(chainId<=0n)throw new Error('Compute analytics chain id invalid');if(range.fromBlock<0n||range.toBlock<range.fromBlock)throw new Error('Compute analytics range invalid');if(range.toBlock-range.fromBlock>1_000_000n)throw new Error('Compute analytics range too large');
 const result=rows(await db.query(`select event_name,fields,block_number,tx_index,log_index from idx_protocol_events where chain_id=$1 and protocol='420Compute' and block_number between $2 and $3 and event_name=any($4::text[]) order by block_number asc,tx_index asc,log_index asc`,[chainId.toString(),range.fromBlock.toString(),range.toBlock.toString(),['JobCreated','JobTransition','UsefulRewardAccounted']]));
 const jobs=new Set<string>(),final=new Map<string,number>(),rewardIds=new Set<string>(),beneficiaries=new Set<string>(),metrics=new Map<string,{c:bigint;r:bigint;n:bigint}>();let rewardTotal=0n;
 for(const row of result){const name=String(row.event_name??''),f=fields(row.fields);if(name==='JobCreated'){jobs.add(text(f.jobId,'jobId'));continue;}if(name==='JobTransition'){const id=text(f.jobId,'jobId'),current=Number(uint(f.current,'current'));if(!Number.isSafeInteger(current)||current<0||current>13)throw new Error('Compute analytics job status invalid');final.set(id,current);continue;}if(name==='UsefulRewardAccounted'){const rewardId=text(f.rewardId,'rewardId');if(rewardIds.has(rewardId))throw new Error('Compute analytics duplicate reward id');rewardIds.add(rewardId);const beneficiary=text(f.beneficiary,'beneficiary');beneficiaries.add(beneficiary);const metric=text(f.metricId,'metricId'),c=uint(f.contributionAmount,'contributionAmount'),r=uint(f.amount,'amount');rewardTotal=plus(rewardTotal,r,'reward total');const m=metrics.get(metric)??{c:0n,r:0n,n:0n};m.c=plus(m.c,c,'contribution total');m.r=plus(m.r,r,'metric reward total');m.n+=1n;metrics.set(metric,m);}}
 let verified=0n,settled=0n,failed=0n;for(const s of final.values()){if(s===7)verified++;else if(s===8)settled++;else if(s===11)failed++;}
 return{schemaVersion:COMPUTE_ANALYTICS_SCHEMA_420,chainId:chainId.toString(),fromBlock:range.fromBlock.toString(),toBlock:range.toBlock.toString(),jobsCreated:BigInt(jobs.size).toString(),jobsVerified:verified.toString(),jobsSettled:settled.toString(),jobsFailed:failed.toString(),rewardCount:BigInt(rewardIds.size).toString(),totalRewardAmount:rewardTotal.toString(),uniqueRewardBeneficiaries:BigInt(beneficiaries.size).toString(),metrics:[...metrics.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([metricId,m])=>({metricId,contributionAmount:m.c.toString(),rewardAmount:m.r.toString(),rewardCount:m.n.toString()})),authoritative:false};
}
