const SECRET=/(private.?key|mnemonic|seed.?phrase|password|credential|secret|api.?key|access.?token)/i;
const ADDRESS=/^0x[0-9a-fA-F]{40}$/;const BYTES32=/^0x[0-9a-fA-F]{64}$/;
function object(v,n){if(!v||typeof v!=='object'||Array.isArray(v))throw new Error(n+' must be an object');return v;}
function noSecrets(v,path='config'){if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach((x,i)=>noSecrets(x,path+'['+i+']'));return;}for(const[k,x]of Object.entries(v)){if(SECRET.test(k))throw new Error('secret field rejected: '+path+'.'+k);noSecrets(x,path+'.'+k);}}
function url(v,n){if(typeof v!=='string'||!v)throw new Error(n+' URL required');const u=new URL(v);if(!['https:','http:'].includes(u.protocol))throw new Error(n+' URL must use http/https');if(u.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(u.hostname))throw new Error(n+' URL must use https outside localhost');return u.toString().replace(/\/$/,'');}
function contract(v,n,required){if(v===null||v===undefined||v===''){if(required)throw new Error(n+' canonical contract address required');return null;}if(typeof v!=='string'||!ADDRESS.test(v))throw new Error(n+' contract address invalid');return v.toLowerCase();}
function metric(v,n){if(v===undefined||v===null||v==='')return null;if(typeof v!=='string'||!BYTES32.test(v))throw new Error(n+' metric id invalid');return v.toLowerCase();}
export function validateComputeWebConfig420(value){noSecrets(value);const c=object(value,'config');if(c.schemaVersion!=='420-compute-web-runtime-v1')throw new Error('unsupported compute web config schema');const chain=String(c.chainId??'');if(!/^\d+$/.test(chain)||chain==='0')throw new Error('chainId must be a positive integer');const contracts=object(c.contracts,'contracts');const downloads=object(c.workerDownloads,'workerDownloads');const writeActionsEnabled=c.writeActionsEnabled===true;return Object.freeze({schemaVersion:c.schemaVersion,chainId:chain,indexerUrl:url(c.indexerUrl,'indexer'),computeApiUrl:url(c.computeApiUrl,'compute API'),walletUrl:url(c.walletUrl,'wallet'),writeActionsEnabled,contracts:Object.freeze({workerRegistry:contract(contracts.workerRegistry,'workerRegistry',writeActionsEnabled),researchProjectRegistry:contract(contracts.researchProjectRegistry,'researchProjectRegistry',writeActionsEnabled),verifierRegistry:contract(contracts.verifierRegistry,'verifierRegistry',writeActionsEnabled)}),workerDownloads:Object.freeze({windows:url(downloads.windows,'windows worker'),linux:url(downloads.linux,'linux worker'),darwin:url(downloads.darwin,'macOS worker')}),cpuMetricId:metric(c.cpuMetricId,'cpu'),gpuMetricId:metric(c.gpuMetricId,'gpu')});}
export async function loadComputeWebConfig420(fetchImpl=fetch,path='./runtime-config.json'){const r=await fetchImpl(path,{cache:'no-store'});if(!r.ok)throw new Error('runtime config HTTP '+r.status);return validateComputeWebConfig420(await r.json());}
