const HEX32=/^0x[0-9a-fA-F]{64}$/;const ACCOUNT=/^0x[0-9a-fA-F]{40}$/;const SECRET=/(private.?key|mnemonic|seed.?phrase|password|credential|secret|api.?key|access.?token)/i;
function scan(v,path='args'){if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach((x,i)=>scan(x,path+'['+i+']'));return;}for(const[k,x]of Object.entries(v)){if(SECRET.test(k))throw new Error('secret field rejected: '+path+'.'+k);scan(x,path+'.'+k);}}
function bytes(v,n){if(typeof v!=='string'||!HEX32.test(v))throw new Error(n+' must be bytes32 hex');return v.toLowerCase();}
function addr(v,n){if(typeof v!=='string'||!ACCOUNT.test(v))throw new Error(n+' must be an address');return v.toLowerCase();}
function envelope(config,target,method,args){scan(args);if(config.writeActionsEnabled!==true||!target)throw new Error('canonical write runtime is not enabled');return Object.freeze({schemaVersion:'420-wallet-handoff-v1',chainId:config.chainId,walletUrl:config.walletUrl,targetContract:target,method,args:Object.freeze(args),requiresWalletAuthorization:true,canonicalState:false,secretMaterialManaged:false});}
export function workerRegistrationHandoff420(config,{resourceId,executionSigner,capabilityProfileHash,jurisdictionHash,executionKeyProof}){if(typeof executionKeyProof!=='string'||!/^0x[0-9a-fA-F]*$/.test(executionKeyProof))throw new Error('executionKeyProof must be hex');return envelope(config,config.contracts.workerRegistry,'register',[bytes(resourceId,'resourceId'),addr(executionSigner,'executionSigner'),bytes(capabilityProfileHash,'capabilityProfileHash'),bytes(jurisdictionHash,'jurisdictionHash'),executionKeyProof]);}
export function workerLifecycleHandoff420(config,method,workerId){if(!['activate','suspend','retire'].includes(method))throw new Error('unsupported worker lifecycle action');return envelope(config,config.contracts.workerRegistry,method,[bytes(workerId,'workerId')]);}
export function registerProjectHandoff420(config,{researchDomain,definitionCommitment}){return envelope(config,config.contracts.researchProjectRegistry,'registerProject',[bytes(researchDomain,'researchDomain'),bytes(definitionCommitment,'definitionCommitment')]);}
export function projectAcceptanceHandoff420(config,{projectId,expectedRevision,accepting}){if(!Number.isSafeInteger(expectedRevision)||expectedRevision<1)throw new Error('expectedRevision invalid');if(typeof accepting!=='boolean')throw new Error('accepting must be boolean');return envelope(config,config.contracts.researchProjectRegistry,'setNewWorkAcceptance',[bytes(projectId,'projectId'),String(expectedRevision),accepting]);}
export function verifierViewHandoff420(config,verifierId){return Object.freeze({schemaVersion:'420-wallet-handoff-v1',chainId:config.chainId,walletUrl:config.walletUrl,targetContract:config.contracts.verifierRegistry,method:null,args:[bytes(verifierId,'verifierId')],requiresWalletAuthorization:false,canonicalState:false,secretMaterialManaged:false,note:'Verifier lifecycle governance/authority actions are not exposed as ordinary user mutations.'});}

export function reviseProjectHandoff420(config,{projectId,expectedRevision,researchDomain,definitionCommitment}){if(!Number.isSafeInteger(expectedRevision)||expectedRevision<1)throw new Error('expectedRevision invalid');return envelope(config,config.contracts.researchProjectRegistry,'reviseProject',[bytes(projectId,'projectId'),String(expectedRevision),bytes(researchDomain,'researchDomain'),bytes(definitionCommitment,'definitionCommitment')]);}
export function retireProjectHandoff420(config,{projectId,expectedRevision}){if(!Number.isSafeInteger(expectedRevision)||expectedRevision<1)throw new Error('expectedRevision invalid');return envelope(config,config.contracts.researchProjectRegistry,'retireProject',[bytes(projectId,'projectId'),String(expectedRevision)]);}
