import{loadComputeWebConfig420}from'./core/config.js';import{createComputeController420}from'./core/controller.js';import{buildParticipationProfile420,participationSteps420}from'./core/participation.js';import{registerProjectHandoff420}from'./core/handoff.js';
const $=(id)=>document.getElementById(id);let config,controller,lastPlan=null;
const show=(el,value)=>{el.textContent=typeof value==='string'?value:JSON.stringify(value,null,2);};
const fail=(el,error)=>{el.textContent=error instanceof Error?error.message:String(error);el.classList.add('error');};
const account=()=>$('account').value.trim();const workerId=()=>($('worker-id').value.trim()||$('onboard-worker-id').value.trim());
function cards(el,items,render){el.replaceChildren(...items.map((item)=>{const a=document.createElement('article');const lines=render(item);for(const line of lines){const p=document.createElement('p');p.textContent=line;a.append(p);}return a;}));}
async function refresh(){try{const d=await controller.dashboard({account:account(),workerId:workerId()||undefined});$('jobs-completed').textContent=d.summary.jobsCompleted;$('earnings').textContent=d.summary.earnings420;$('cpu-contribution').textContent=d.summary.cpuContribution;$('gpu-contribution').textContent=d.summary.gpuContribution;$('projects-supported').textContent=d.summary.projectsSupported;$('worker-health').textContent=d.summary.workerHealth.registered?'Worker registered · revision '+d.summary.workerHealth.revision+' · indexed projection':'No indexed worker selected/registered';cards($('completed-jobs'),d.jobs.items.filter(x=>['VERIFIED','SETTLED'].includes(x.status)),j=>[j.status,j.jobId,'result '+(j.resultCommitment??'pending'),'verification '+(j.verificationRef??'pending')]);cards($('project-list'),d.projects.items,p=>[(p.retired?'retired':'active')+' · revision '+p.revision,p.projectId,'domain '+p.researchDomain]);cards($('reputation-list'),d.reputation.items??[],r=>['total '+r.total+' · signals '+r.activeSignals,'policy '+r.policyId,'reference '+r.referenceId]);cards($('stake-list'),d.stake.items??[],s=>['policy revision '+s.stakePolicyRevision,'position '+s.positionId+' @ '+s.positionRevision,'reference '+s.referenceId]);$('network-badge').textContent='chain '+config.chainId+' · indexer '+(d.status?.indexedHead??'—');}catch(e){fail($('worker-health'),e);}}
async function boot(){config=await loadComputeWebConfig420();controller=createComputeController420(config);$('network-badge').textContent='chain '+config.chainId;$('refresh-dashboard').onclick=refresh;$('load-projects').onclick=refresh;$('load-trust').onclick=refresh;
$('submit-job').onclick=async()=>{try{const env=JSON.parse($('job-envelope').value);lastPlan=await controller.submitJob(env);show($('submission-plan'),lastPlan);$('open-wallet-submit').disabled=false;}catch(e){fail($('submission-plan'),e);}};
$('open-wallet-submit').onclick=()=>{if(lastPlan)window.open(config.walletUrl,'_blank','noopener,noreferrer');};
$('build-participation').onclick=()=>{try{const bundle=buildParticipationProfile420(config,{providerId:$('provider-id').value.trim(),nodeId:$('node-id').value.trim(),resourceId:$('resource-id').value.trim(),workerId:$('onboard-worker-id').value.trim(),cpuPercent:$('cpu-percent').value,gpuPercent:$('gpu-percent').value,projectIds:$('project-preferences').value.split(/\s+/).filter(Boolean)});show($('worker-args'),bundle.workerArgs);$('participation-steps').replaceChildren(...participationSteps420(bundle).map(s=>{const d=document.createElement('div');const b=document.createElement('strong');b.textContent=s.title;const p=document.createElement('p');p.textContent=s.detail;d.append(b,p);return d;}));}catch(e){fail($('worker-args'),e);}};
$('load-verifiers').onclick=async()=>{try{const p=await controller.verifierOperations(account());cards($('verifier-list'),p.items,v=>[v.status??'indexed verifier',v.verifierId,'authority '+(v.authority??'—')]);}catch(e){fail($('verifier-list'),e);}};
$('prepare-project').onclick=()=>{try{show($('project-handoff'),registerProjectHandoff420(config,{researchDomain:$('research-domain').value.trim(),definitionCommitment:$('definition-commitment').value.trim()}));}catch(e){fail($('project-handoff'),e);}};
$('inspect-job').onclick=async()=>{try{show($('job-status'),await controller.inspectJob($('inspect-job-id').value.trim()));}catch(e){fail($('job-status'),e);}};
}
boot().catch(e=>{document.body.dataset.boot='failed';$('network-badge').textContent='configuration unavailable';console.error(e);});