// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;

library PulseIds420 {
    bytes32 internal constant COMPONENT_PULSE = keccak256("420/COMPONENT/PULSE/V1");

    bytes32 internal constant SERVICE_POLICY_REGISTRY = keccak256("420/PULSE/SERVICE/POLICY_REGISTRY/V1");
    bytes32 internal constant SERVICE_PROFILE_REGISTRY = keccak256("420/PULSE/SERVICE/PROFILE_REGISTRY/V1");
    bytes32 internal constant SERVICE_GRAPH = keccak256("420/PULSE/SERVICE/GRAPH/V1");
    bytes32 internal constant SERVICE_PUBLICATION_REGISTRY = keccak256("420/PULSE/SERVICE/PUBLICATION_REGISTRY/V1");
    bytes32 internal constant SERVICE_INTERACTION_REGISTRY = keccak256("420/PULSE/SERVICE/INTERACTION_REGISTRY/V1");
    bytes32 internal constant SERVICE_TOPIC_REGISTRY = keccak256("420/PULSE/SERVICE/TOPIC_REGISTRY/V1");

    bytes32 internal constant PROFILE_PERSON = keccak256("420/PULSE/PROFILE/PERSON/V1");
    bytes32 internal constant PROFILE_CREATOR = keccak256("420/PULSE/PROFILE/CREATOR/V1");
    bytes32 internal constant PROFILE_ORGANIZATION = keccak256("420/PULSE/PROFILE/ORGANIZATION/V1");
    bytes32 internal constant PROFILE_MERCHANT = keccak256("420/PULSE/PROFILE/MERCHANT/V1");
    bytes32 internal constant PROFILE_PROJECT = keccak256("420/PULSE/PROFILE/PROJECT/V1");
    bytes32 internal constant PROFILE_PROTOCOL = keccak256("420/PULSE/PROFILE/PROTOCOL/V1");
    bytes32 internal constant PROFILE_COMMUNITY = keccak256("420/PULSE/PROFILE/COMMUNITY/V1");

    bytes32 internal constant PUBLICATION_POST = keccak256("420/PULSE/PUBLICATION/POST/V1");
    bytes32 internal constant PUBLICATION_ARTICLE = keccak256("420/PULSE/PUBLICATION/ARTICLE/V1");
    bytes32 internal constant PUBLICATION_IMAGE = keccak256("420/PULSE/PUBLICATION/IMAGE/V1");
    bytes32 internal constant PUBLICATION_VIDEO = keccak256("420/PULSE/PUBLICATION/VIDEO/V1");
    bytes32 internal constant PUBLICATION_AUDIO = keccak256("420/PULSE/PUBLICATION/AUDIO/V1");
    bytes32 internal constant PUBLICATION_LINK = keccak256("420/PULSE/PUBLICATION/LINK/V1");
    bytes32 internal constant PUBLICATION_POLL = keccak256("420/PULSE/PUBLICATION/POLL/V1");
    bytes32 internal constant PUBLICATION_PRODUCT_REFERENCE = keccak256("420/PULSE/PUBLICATION/PRODUCT_REFERENCE/V1");
    bytes32 internal constant PUBLICATION_RELEASE_REFERENCE = keccak256("420/PULSE/PUBLICATION/RELEASE_REFERENCE/V1");
    bytes32 internal constant PUBLICATION_EVENT_REFERENCE = keccak256("420/PULSE/PUBLICATION/EVENT_REFERENCE/V1");
    bytes32 internal constant PUBLICATION_COMMONS_REFERENCE = keccak256("420/PULSE/PUBLICATION/COMMONS_REFERENCE/V1");

    bytes32 internal constant ACTION_UPDATE_PROFILE = keccak256("420/PULSE/ACTION/UPDATE_PROFILE/V1");
    bytes32 internal constant ACTION_DEACTIVATE_PROFILE = keccak256("420/PULSE/ACTION/DEACTIVATE_PROFILE/V1");
    bytes32 internal constant ACTION_PUBLISH = keccak256("420/PULSE/ACTION/PUBLISH/V1");
    bytes32 internal constant ACTION_EDIT_PUBLICATION = keccak256("420/PULSE/ACTION/EDIT_PUBLICATION/V1");
    bytes32 internal constant ACTION_DEACTIVATE_PUBLICATION = keccak256("420/PULSE/ACTION/DEACTIVATE_PUBLICATION/V1");
}
