import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateControlledCanary} from '../core/controlled-canary.js';

const digest='sha256:'+'a'.repeat(64),commit='b'.repeat(40),url='https://ops.example.org/evidence';
const release={releaseId:'bg-canary-1',environment:'staging',commit,artifactDigest:digest,configDigest:digest,policyDigest:digest,manifestUrl:url};
const scenarios=['policy_outage','chain_reorg','access_revocation','database_restore','media_unavailable'];
function fixture(){
 const drills=scenarios.map(scenario=>({scenario,releaseId:release.releaseId,environment:'staging',result:'passed',measuredRtoMs:100,measuredRpoMs:0,evidenceUrl:url,operator:'operator',approver:'reviewer',policyAccessRechecked:true,privateIngressRemainsDisabled:true,unqualifiedFeaturesRemainDisabled:true}));
 const recovery={deployment:{...release},controls:{releaseId:release.releaseId,environment:'staging',privateIngressDisabled:true,unqualifiedFeaturesDisabled:true,rollbackTargetPinned:true,rollbackTargetReleaseId:'prior',rollbackArtifactDigest:digest,flagsEvidenceUrl:url,rollbackRunbookUrl:url,rollbackArtifactUrl:url,operator:'operator'},backup:{releaseId:release.releaseId,environment:'staging',encrypted:true,restoreVerified:true,accessReviewed:true,snapshotDigest:digest,inventoryEvidenceUrl:url,restoreEvidenceUrl:url,operator:'operator'},objectives:{maxRtoMs:200,maxRpoMs:0},drills};
 const window=(start,end)=>({environment:'staging',releaseId:release.releaseId,windowStartMs:start,windowEndMs:end,requests:100,errors:0,p95LatencyMs:20,indexLagBlocks:0,finalityLagBlocks:0,authorizationDenials:0,moderationPolicyFailures:0,privacyIncidents:0,authBoundaryFailures:0,reorgConsistencyFailures:0});
 const observations=[window(1000,2000),window(2000,3000)].map(w=>({window:w,attestation:{...release,windowStartMs:w.windowStartMs,windowEndMs:w.windowEndMs,collectorId:'trusted-collector',collectorEvidenceUrl:url,operator:'operator',approver:'reviewer'}}));
 return {release:{...release},bg19Approval:{launchApproved:true,releaseId:release.releaseId,environment:'staging',commit,artifactDigest:digest,approvalUrl:url,journeyEvidenceUrl:url},recovery,rollback:{ready:true,releaseId:release.releaseId,runbookUrl:url,drillEvidenceUrl:url,owner:'operator'},thresholds:{minRequests:10,maxErrorRate:0.1,maxP95LatencyMs:100,minWindows:2,maxIndexLagBlocks:3},observabilityPolicy:{environment:'staging',releaseId:release.releaseId,ownerTeam:'sre-team',retentionHours:24,maxWindowAgeMs:60000,minRequests:10,maxErrorRate:0.1,maxP95LatencyMs:100,maxIndexLagBlocks:3,maxFinalityLagBlocks:3},observations,nowMs:3000};
}
test('clean measured staging windows always hold for independent operator review',()=>{const value=evaluateControlledCanary(fixture());assert.equal(value.state,'hold_for_operator');assert.equal(value.trafficChangeAllowed,false);assert.equal(value.launchApproved,false);});
test('never accepts missing release signoff or production input',()=>{let v=fixture();v.bg19Approval.launchApproved=false;assert.equal(evaluateControlledCanary(v).state,'blocked');v=fixture();v.release.environment='production';assert.equal(evaluateControlledCanary(v).state,'blocked');});
test('exact release, commit, digest and policy versions must bind every observation',()=>{for(const key of ['releaseId','commit','artifactDigest','configDigest','policyDigest']){const v=fixture();v.observations[1].attestation[key]='wrong';assert.equal(evaluateControlledCanary(v).state,'blocked',key);}});
test('unknown telemetry fields, overlapping windows and self-attestation fail closed',()=>{let v=fixture();v.observations[0].window.walletAddress='0xsecret';assert.equal(evaluateControlledCanary(v).state,'blocked');v=fixture();v.observations[1].window.windowStartMs=1999;v.observations[1].attestation.windowStartMs=1999;assert.equal(evaluateControlledCanary(v).state,'blocked');v=fixture();v.observations[0].attestation.approver='operator';assert.equal(evaluateControlledCanary(v).state,'blocked');});
test('safety breach forces rollback without allowing traffic changes',()=>{const v=fixture();v.observations[1].window.authBoundaryFailures=1;const result=evaluateControlledCanary(v);assert.equal(result.state,'rollback_required');assert.equal(result.trafficChangeAllowed,false);});
test('missing rollback drill or observability samples cannot qualify',()=>{let v=fixture();v.recovery.drills.pop();assert.equal(evaluateControlledCanary(v).state,'blocked');v=fixture();v.observations[1].window.requests=0;assert.equal(evaluateControlledCanary(v).state,'blocked');});
