// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;
import "../src/ai/AIIds420.sol";import "../src/ai/AIAuthorization420.sol";import "../src/ai/AIPolicyRegistry420.sol";import "../src/ai/AIProviderRegistry.sol";import "../src/ai/AIModelRegistry.sol";import "../src/ai/AIJobManager.sol";import "../src/ai/AIModelDeploymentRegistry420.sol";import "../src/ai/AIRequestRegistry420.sol";import "../src/ai/AIResultRegistry420.sol";import "../src/ai/AIComputeAdapter420.sol";import "../src/ai/AIRouter420.sol";import "../src/interfaces/genesis/ICapabilityRegistry420.sol";import "../src/compute/ICompute420.sol";
interface VmAIV1Modules420{function prank(address) external;function expectRevert(bytes4) external;}
contract MockCapsAIV1 is ICapabilityRegistry420{bool public allowed;function setAllowed(bool v)external{allowed=v;}function grant(bytes32)external pure returns(CapabilityGrant memory g){return g;}function isAuthorized(address,bytes32,bytes32,bytes32,uint256)external view returns(bool){return allowed;}}
contract MockRequestCtorAIV1{}
contract MockJobCtorAIV1{address public requestEvidence;constructor(){requestEvidence=address(new MockRequestCtorAIV1());}}
contract MockStubCtorAIV1{}
contract MockFundingCtorAIV1{}
contract MockComputeAIV1 is ICompute420{
bytes32 public immutable override componentGraphHash=keccak256("compute-graph");
address private immutable j;address private immutable f;address private immutable m;address private immutable s;address private immutable p;
constructor(){j=address(new MockJobCtorAIV1());f=address(new MockFundingCtorAIV1());m=address(new MockStubCtorAIV1());s=address(new MockStubCtorAIV1());p=address(new MockStubCtorAIV1());}
function jobRegistry()external view returns(address){return j;}function fundingAdapter()external view returns(address){return f;}function matchRegistry()external view returns(address){return m;}function workerEvidence()external pure returns(address){return address(0x14);}function verificationRouter()external pure returns(address){return address(0x15);}function disputeResolver()external pure returns(address){return address(0x16);}function settlementAdapter()external view returns(address){return s;}function providerRegistry()external view returns(address){return p;}function nodeRegistry()external pure returns(address){return address(0x19);}function resourceRegistry()external pure returns(address){return address(0x1a);}function offerRegistry()external pure returns(address){return address(0x1b);}}
contract AIV1Modules420Test{
VmAIV1Modules420 constant vm=VmAIV1Modules420(address(uint160(uint256(keccak256("hevm cheat code")))));address constant ALICE=address(0xA11CE);bytes32 constant PROVIDER=keccak256("provider");bytes32 constant MODEL=keccak256("model");bytes32 constant VERSION=keccak256("version");bytes32 constant DEPLOYMENT=keccak256("deployment");bytes32 constant JOB=keccak256("job");
function testAuthorizationFailsClosedAndScopesDiffer() public{MockCapsAIV1 c=new MockCapsAIV1();AIAuthorization420 a=new AIAuthorization420(address(c));require(a.scopeProvider(PROVIDER)!=a.scopeDeployment(PROVIDER));require(!a.isDeploymentAuthorized(ALICE,DEPLOYMENT,AIIds420.ACTION_REGISTER_DEPLOYMENT));c.setAllowed(true);require(a.isDeploymentAuthorized(ALICE,DEPLOYMENT,AIIds420.ACTION_REGISTER_DEPLOYMENT));require(!a.isDeploymentAuthorized(ALICE,DEPLOYMENT,bytes32(uint256(7))));}
function testPolicyHistoryImmutable() public{AIPolicyRegistry420 p=new AIPolicyRegistry420(address(this));bytes32 id=keccak256("policy");p.setPolicy(id,AIIds420.WORKLOAD_TEXT,keccak256("p"),keccak256("v"),keccak256("x"),100,3600,true);p.setPolicy(id,AIIds420.WORKLOAD_TEXT,keccak256("p2"),keccak256("v2"),keccak256("x2"),80,1800,true);require(p.getPolicyRevision(id,1).maxSpend420==100);require(p.getPolicy(id).revision==2);}
function testDeploymentAndReadThroughAndAdapter() public{MockCapsAIV1 c=new MockCapsAIV1();AIAuthorization420 a=new AIAuthorization420(address(c));AIProviderRegistry pr=new AIProviderRegistry(address(this));AIModelRegistry m=new AIModelRegistry(address(this));AIJobManager j=new AIJobManager(address(this));AIModelDeploymentRegistry420 d=new AIModelDeploymentRegistry420(address(a),address(pr),address(m));vm.prank(ALICE);pr.registerProvider(PROVIDER,ALICE,ALICE,keccak256("meta"),keccak256("stake"),keccak256("compute-provider"));vm.prank(ALICE);pr.activate(PROVIDER);vm.prank(ALICE);m.registerModel(MODEL,keccak256("meta"),keccak256("lic"));vm.prank(ALICE);m.registerVersion(VERSION,MODEL,1,keccak256("man"),keccak256("w"),keccak256("r"),keccak256("c"),keccak256("s"),keccak256("v"),keccak256("l"));vm.prank(ALICE);d.registerDeployment(DEPLOYMENT,PROVIDER,VERSION,keccak256("offer"),keccak256("price"),keccak256("end"),uint64(block.timestamp+1 days),keccak256("region"),keccak256("sla"));vm.prank(ALICE);d.setState(DEPLOYMENT,AIModelDeploymentRegistry420.State.ACTIVE);require(d.isOperational(DEPLOYMENT));
AIRequestRegistry420 rq=new AIRequestRegistry420(address(j));AIResultRegistry420 rr=new AIResultRegistry420(address(j));vm.prank(ALICE);j.createRequest(JOB,VERSION,AIIds420.WORKLOAD_TEXT,keccak256("in"),keccak256("privacy"),keccak256("v"),55,uint64(block.timestamp+1 days));require(rq.getRequest(JOB).requester==ALICE);require(rr.getResult(JOB).outputCommitment==0);vm.prank(j.AI_JOB_ESCROW());j.confirmFunding(JOB,keccak256("fund"),55);MockComputeAIV1 comp=new MockComputeAIV1();AIComputeAdapter420 ad=new AIComputeAdapter420(address(j),address(a),address(comp),address(pr),address(m),address(d));require(address(ad.computeJobs())!=address(0));require(ad.computeRouter()==ICompute420(address(comp)));
AIPolicyRegistry420 pol=new AIPolicyRegistry420(address(this));AIRouter420 router=new AIRouter420(address(pr),address(m),address(j),address(a),address(pol),address(d),address(rq),address(rr),address(ad));require(router.componentGraphHash()!=0);require(router.jobManager()==address(j));}
}
