// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;
import "../src/interfaces/genesis/ICapabilityRegistry420.sol";
import "../src/treasury/TreasuryIds420.sol";
import "../src/treasury/TreasuryAuthorization420.sol";
import "../src/treasury/TreasuryPolicyRegistry420.sol";
import "../src/treasury/TreasuryBudgetRegistry420.sol";
import "../src/treasury/TreasuryDisbursementRegistry420.sol";
import "../src/treasury/TreasuryRouter420.sol";
interface VmTreasury420 { function prank(address) external; function warp(uint256) external; }
contract MockTreasuryCaps420 is ICapabilityRegistry420 { mapping(bytes32=>bool) ok; function key(address p,bytes32 c,bytes32 a,bytes32 s) public pure returns(bytes32){return keccak256(abi.encode(p,c,a,s));} function set(address p,bytes32 c,bytes32 a,bytes32 s,bool v) external{ok[key(p,c,a,s)]=v;} function grant(bytes32) external pure returns(CapabilityGrant memory g){return g;} function isAuthorized(address p,bytes32 c,bytes32 a,bytes32 s,uint256) external view returns(bool){return ok[key(p,c,a,s)];} }
contract TreasuryGenesis420Test {
    VmTreasury420 constant vm=VmTreasury420(address(uint160(uint256(keccak256("hevm cheat code"))))); address constant EXECUTOR=address(0xE); address constant RECIPIENT=address(0xB0B); address constant ASSET=address(0x420);
    struct Env {MockTreasuryCaps420 caps;TreasuryAuthorization420 auth;TreasuryPolicyRegistry420 policy;TreasuryBudgetRegistry420 budgets;TreasuryDisbursementRegistry420 disb;TreasuryRouter420 router;}
    function setup() internal returns(Env memory e){e.caps=new MockTreasuryCaps420();e.auth=new TreasuryAuthorization420(address(e.caps));e.policy=new TreasuryPolicyRegistry420(address(this));e.budgets=new TreasuryBudgetRegistry420(address(this),address(e.policy));e.disb=new TreasuryDisbursementRegistry420(address(this),address(e.auth),address(e.policy),address(e.budgets));e.budgets.setController(address(e.disb));e.router=new TreasuryRouter420(address(e.budgets),address(e.disb));e.policy.setAssetPolicy(ASSET,true,1000,1500,100);}
    function makeBudget(Env memory e) internal returns(bytes32 b,bytes32 action){b=keccak256("budget");action=keccak256("civic-action");e.budgets.createBudget(b,keccak256("treasury-vault"),TreasuryIds420.BUDGET_DEVELOPMENT,ASSET,2000,uint64(block.timestamp),uint64(block.timestamp+1000),action,keccak256("meta"));}
    function testCivicBoundBudgetAndReplaySafeDisbursement() public {Env memory e=setup();(bytes32 b,bytes32 action)=makeBudget(e);uint64 nb=uint64(block.timestamp);uint64 ex=uint64(block.timestamp+100);bytes32 id=e.disb.canonicalId(b,RECIPIENT,500,nb,ex,action,keccak256("purpose"));e.disb.schedule(id,b,RECIPIENT,500,nb,ex,action,keccak256("purpose"));(bool replay,)=address(e.disb).call(abi.encodeWithSelector(e.disb.schedule.selector,id,b,RECIPIENT,uint128(500),nb,ex,action,keccak256("purpose")));require(!replay,"replay");require(e.router.remainingBudget(b)==1500,"reserve accounting");}
    function testExecutionDefaultDenyAndScopedCapability() public {Env memory e=setup();(bytes32 b,bytes32 action)=makeBudget(e);uint64 nb=uint64(block.timestamp);uint64 ex=uint64(block.timestamp+100);bytes32 id=e.disb.canonicalId(b,RECIPIENT,500,nb,ex,action,keccak256("purpose"));e.disb.schedule(id,b,RECIPIENT,500,nb,ex,action,keccak256("purpose"));vm.prank(EXECUTOR);(bool denied,)=address(e.disb).call(abi.encodeWithSelector(e.disb.markExecuted.selector,id,keccak256("release")));require(!denied,"default allow");e.caps.set(EXECUTOR,TreasuryIds420.COMPONENT_TREASURY,TreasuryIds420.ACTION_EXECUTE_DISBURSEMENT,e.auth.scopeForDisbursement(id),true);vm.prank(EXECUTOR);e.disb.markExecuted(id,keccak256("release"));require(e.disb.disbursement(id).state==TreasuryDisbursementRegistry420.State.EXECUTED,"not executed");}
    function testBudgetAndEpochCapsFailClosed() public {Env memory e=setup();(bytes32 b,bytes32 action)=makeBudget(e);uint64 nb=uint64(block.timestamp);uint64 ex=uint64(block.timestamp+100);bytes32 tooBig=e.disb.canonicalId(b,RECIPIENT,1001,nb,ex,action,keccak256("big"));(bool ok,)=address(e.disb).call(abi.encodeWithSelector(e.disb.schedule.selector,tooBig,b,RECIPIENT,uint128(1001),nb,ex,action,keccak256("big")));require(!ok,"single cap bypass");}
    function testTemporalWindow() public {Env memory e=setup();(bytes32 b,bytes32 action)=makeBudget(e);uint64 nb=uint64(block.timestamp+10);uint64 ex=uint64(block.timestamp+20);bytes32 id=e.disb.canonicalId(b,RECIPIENT,100,nb,ex,action,keccak256("timed"));e.disb.schedule(id,b,RECIPIENT,100,nb,ex,action,keccak256("timed"));e.caps.set(EXECUTOR,TreasuryIds420.COMPONENT_TREASURY,TreasuryIds420.ACTION_EXECUTE_DISBURSEMENT,e.auth.scopeForDisbursement(id),true);vm.prank(EXECUTOR);(bool early,)=address(e.disb).call(abi.encodeWithSelector(e.disb.markExecuted.selector,id,keccak256("release")));require(!early,"early execution");vm.warp(ex+1);vm.prank(EXECUTOR);(bool late,)=address(e.disb).call(abi.encodeWithSelector(e.disb.markExecuted.selector,id,keccak256("release")));require(!late,"late execution");}
}
