import test from "node:test";
import assert from "node:assert/strict";
import {CommunityStore420, Charts420, AwardsDomain420, AwardVoting420, HzCrossService420} from "../src/index.js";

const recording={id:"song1",creatorId:"artist1",status:"PUBLISHED",visibility:"PUBLIC",owner:"artist1",disclosure:"AI_ASSISTED",publishedAt:5,genre:"rock",mood:"dark",category:"single"};
const records=new Map([["song1",recording],["secret",{...recording,id:"secret",visibility:"PRIVATE"}]]);
const fetchRecording=id=>records.get(id)||null;
fetchRecording.list=()=>[...records.values()];
const creator=id=>({id,status:"ACTIVE",visibility:"PUBLIC"});
const session=accountRef=>({verified:true,scope:"420hz:community:write",accountRef,domain:"420hz:test",expiresAt:Date.now()+60000});
const rules={nominationMode:"OPEN_SUBMISSION",selfNomination:"DISALLOWED",maxNominationsPerNominator:2,voterEligibility:"WALLET_ONE_ACCOUNT_ONE_VOTE",quorumMode:"MIN_VALID_VOTES",quorumValue:1,winnerMode:"PLURALITY",winnerValue:0,tieMode:"CO_WINNERS",allowAbstain:true,releaseStart:0,releaseEnd:100,aiClasses:["AI_ASSISTED"]};

test("M2: published source -> community -> charts; privacy, raw plays and replay cannot inflate rankings",()=>{
 const community=new CommunityStore420({source:{creator,recording:id=>{const x=fetchRecording(id);return x&&{...x,status:x.status==="PUBLISHED"?"ACTIVE":x.status};}}});
 community.follow(session("alice"),"artist1");
 community.favorite(session("alice"),"song1");
 const p=community.createPlaylist(session("alice"),{title:"Public songs",id:"playlist1",visibility:"PUBLIC"});
 community.addItem(session("alice"),p.id,"song1","item1");
 assert.equal(community.discovery().length,1);
 assert.equal(community.activity().length,2);
 assert.throws(()=>community.favorite(session("alice"),"secret"),/SOURCE_UNAVAILABLE/);
 assert.equal(community.activity().some(x=>x.type==="FAVORITE"),false);
 const charts=new Charts420({recording:fetchRecording,creator,qualification:e=>e.id==="qualified1",verifyCheckpoint:cp=>cp==="cp1"});
 charts.ingest({id:"raw1",recordingId:"song1",signal:"RAW_PLAY",at:100,checkpoint:"cp1",public:true});
 charts.ingest({id:"qualified1",recordingId:"song1",signal:"QUALIFIED_PLAY",at:101,checkpoint:"cp1",listenerToken:"listener1",public:true});
 assert.equal(charts.ingest({id:"qualified1",recordingId:"song1",signal:"QUALIFIED_PLAY",at:101,checkpoint:"cp1",listenerToken:"listener1",public:true}),false);
 assert.throws(()=>charts.ingest({id:"forged",recordingId:"song1",signal:"QUALIFIED_PLAY",at:102,checkpoint:"cp1",listenerToken:"listener2",public:true}),/UNVERIFIED_QUALIFICATION/);
 assert.throws(()=>charts.snapshot({windowEnd:200,checkpoint:"bad"}),/STALE_SOURCE/);
 const snapshot=charts.snapshot({windowEnd:200,checkpoint:"cp1"});
 assert.equal(snapshot.rows.length,1);
 assert.equal(snapshot.rows[0].qualifiedPlays,1);
 assert.deepEqual(charts.discover({disclosure:"AI_ASSISTED"}).map(x=>x.id),["song1"]);
 assert.equal(community.discovery()[0].items.length,1);
 records.get("song1").visibility="PRIVATE";
 assert.equal(community.discovery()[0].items.length,0);
 assert.equal(charts.snapshot({windowEnd:200,checkpoint:"cp1"}).rows.length,0);
});

test("M3/M4: published recording -> nomination -> qualified ballot -> result/badge -> public projection with private fail-close",()=>{
 records.get("song1").visibility="PUBLIC";
 const domain=new AwardsDomain420({authority:actor=>actor==="admin"});
 domain.program("admin",{id:"program",name:"Awards"});
 domain.change("admin","program","program","ACTIVE");
 domain.policy("admin",{id:"policy",version:1,rules});
 domain.season("admin",{id:"season",programId:"program",policyId:"policy",nominationStart:1,nominationEnd:10,votingStart:20,votingEnd:30});
 domain.category("admin",{id:"category",seasonId:"season",policyId:"policy",key:"SONG_OF_THE_YEAR",targetType:"RECORDING",definitionCommitment:"rules1"});
 domain.change("admin","category","category","ACTIVE");
 domain.change("admin","season","season","SCHEDULED");
 domain.change("admin","season","season","NOMINATIONS_OPEN");
 const voting=new AwardVoting420({domain,source:(type,id)=>type==="RECORDING"?fetchRecording(id):null,authorize:(context,action)=>context?.action===action&&context?.approved===true,production:true,verifyAbuse:()=>true});
 const act=(account,action)=>({account,action,approved:true});
 assert.throws(()=>voting.nominate(act("alice","nominate"),{id:"privateNom",categoryId:"category",targetId:"secret",at:5}),/SOURCE_NOT_ELIGIBLE/);
 voting.nominate(act("alice","nominate"),{id:"nom1",categoryId:"category",targetId:"song1",at:5});
 voting.accept(act("admin","curate"),"nom1");
 domain.change("admin","season","season","NOMINATIONS_CLOSED");
 const ballot=voting.freeze(act("admin","freeze"),{id:"ballot1",categoryId:"category"});
 assert.equal(ballot.candidateIds.length,1);
 domain.change("admin","season","season","BALLOT_FROZEN");
 domain.change("admin","ballot","ballot1","OPEN");
 domain.change("admin","season","season","VOTING_OPEN");
 voting.vote(act("bob","vote"),{id:"vote1",ballotId:"ballot1",targetId:"song1",at:25});
 assert.throws(()=>voting.vote(act("bob","vote"),{id:"vote2",ballotId:"ballot1",targetId:"song1",at:25}),/VOTE_REPLAY/);
 domain.change("admin","ballot","ballot1","CLOSED");
 domain.change("admin","season","season","VOTING_CLOSED");
 const result=voting.finalize(act("admin","finalize"),{resultId:"result1",ballotId:"ballot1",at:31});
 assert.deepEqual(result.winnerTargetIds,["song1"]);
 domain.change("admin","season","season","FINALIZED");
 const badge=domain.badge("admin",{id:"badge1",resultId:result.id,targetId:"song1"});
 assert.equal(badge.targetId,"song1");
 const projections=new HzCrossService420({verifySource:x=>x.sourceCheckpoint==="cp1",authorizePrivate:()=>false});
 const pub={sourceCheckpoint:"cp1",at:31,visibility:"PUBLIC",finalized:true,sourceReady:true};
 projections.ingest({...pub,id:"release1",objectId:"song1",recordingId:"song1",creatorId:"artist1",disclosure:"AI_ASSISTED",type:"RELEASE_PUBLISHED"});
 projections.ingest({...pub,id:"award1",objectId:result.id,recordingId:"song1",creatorId:"artist1",type:"AWARD_WON",awardCategory:"SONG_OF_THE_YEAR",commitment:result.resultCommitment});
 projections.ingest({...pub,id:"private1",objectId:"draft1",type:"GENERATION_COMPLETED",visibility:"PRIVATE",recipientAccount:"alice"});
 const view=projections.rebuild({checkpoint:"cp1",includePrivateForAccount:"alice"});
 assert.deepEqual(view.search.map(x=>x.kind).sort(),["AWARD_RESULT","RECORDING"]);
 assert.equal(view.search.find(x=>x.kind==="AWARD_RESULT").recordingId,view.search.find(x=>x.kind==="RECORDING").recordingId);
 assert.equal(view.explorer.some(x=>x.objectId===result.id),true);
 assert.equal(view.notifications.some(x=>x.id==="private1"),false);
 assert.throws(()=>projections.ingest({...pub,id:"award1",objectId:"forged",type:"AWARD_WON"}),/REPLAY_CONFLICT/);
 assert.throws(()=>projections.rebuild({checkpoint:"stale",sourceReady:false}),/STALE_CHECKPOINT/);
});
