// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;

interface IERC1155Receiver420 { function onERC1155Received(address operator,address from,uint256 id,uint256 value,bytes calldata data) external returns(bytes4); function onERC1155BatchReceived(address operator,address from,uint256[] calldata ids,uint256[] calldata values,bytes calldata data) external returns(bytes4); }
contract ERC1155Template420 {
    string public uri; address public owner; bytes32 public immutable templateId; mapping(uint256=>mapping(address=>uint256)) private _balances; mapping(address=>mapping(address=>bool)) public isApprovedForAll;
    error Unauthorized(); error ZeroAddress(); error LengthMismatch(); error InsufficientBalance(); error UnsafeRecipient();
    event TransferSingle(address indexed operator,address indexed from,address indexed to,uint256 id,uint256 value); event TransferBatch(address indexed operator,address indexed from,address indexed to,uint256[] ids,uint256[] values); event ApprovalForAll(address indexed account,address indexed operator,bool approved); event URI(string value,uint256 indexed id); event OwnershipTransferred(address indexed oldOwner,address indexed newOwner);
    constructor(string memory uri_,address owner_,bytes32 templateId_){if(owner_==address(0)) revert ZeroAddress();uri=uri_;owner=owner_;templateId=templateId_;}
    modifier onlyOwner(){if(msg.sender!=owner) revert Unauthorized();_;}
    function supportsInterface(bytes4 id) external pure returns(bool){return id==0x01ffc9a7||id==0xd9b67a26||id==0x0e89341c;}
    function balanceOf(address a,uint256 id) external view returns(uint256){if(a==address(0)) revert ZeroAddress();return _balances[id][a];}
    function balanceOfBatch(address[] calldata a,uint256[] calldata ids) external view returns(uint256[] memory out){if(a.length!=ids.length) revert LengthMismatch();out=new uint256[](a.length);for(uint256 i;i<a.length;i++){if(a[i]==address(0)) revert ZeroAddress();out[i]=_balances[ids[i]][a[i]];}}
    function transferOwnership(address n) external onlyOwner{if(n==address(0)) revert ZeroAddress();emit OwnershipTransferred(owner,n);owner=n;}
    function setApprovalForAll(address op,bool approved) external{isApprovedForAll[msg.sender][op]=approved;emit ApprovalForAll(msg.sender,op,approved);}
    function safeTransferFrom(address from,address to,uint256 id,uint256 value,bytes calldata data) external{if(msg.sender!=from&&!isApprovedForAll[from][msg.sender]) revert Unauthorized();_transfer(from,to,id,value);if(to.code.length!=0){try IERC1155Receiver420(to).onERC1155Received(msg.sender,from,id,value,data) returns(bytes4 v){if(v!=IERC1155Receiver420.onERC1155Received.selector) revert UnsafeRecipient();}catch{revert UnsafeRecipient();}}}
    function safeBatchTransferFrom(address from,address to,uint256[] calldata ids,uint256[] calldata values,bytes calldata data) external{if(msg.sender!=from&&!isApprovedForAll[from][msg.sender]) revert Unauthorized();if(ids.length!=values.length) revert LengthMismatch();if(to==address(0)) revert ZeroAddress();for(uint256 i;i<ids.length;i++){uint256 b=_balances[ids[i]][from];if(b<values[i]) revert InsufficientBalance();unchecked{_balances[ids[i]][from]=b-values[i];}_balances[ids[i]][to]+=values[i];}emit TransferBatch(msg.sender,from,to,ids,values);if(to.code.length!=0){try IERC1155Receiver420(to).onERC1155BatchReceived(msg.sender,from,ids,values,data) returns(bytes4 v){if(v!=IERC1155Receiver420.onERC1155BatchReceived.selector) revert UnsafeRecipient();}catch{revert UnsafeRecipient();}}}
    function mint(address to,uint256 id,uint256 value,bytes calldata data) external onlyOwner{if(to==address(0)) revert ZeroAddress();_balances[id][to]+=value;emit TransferSingle(msg.sender,address(0),to,id,value);if(to.code.length!=0){try IERC1155Receiver420(to).onERC1155Received(msg.sender,address(0),id,value,data) returns(bytes4 v){if(v!=IERC1155Receiver420.onERC1155Received.selector) revert UnsafeRecipient();}catch{revert UnsafeRecipient();}}}
    function burn(address from,uint256 id,uint256 value) external{if(msg.sender!=from&&!isApprovedForAll[from][msg.sender]) revert Unauthorized();uint256 b=_balances[id][from];if(b<value) revert InsufficientBalance();unchecked{_balances[id][from]=b-value;}emit TransferSingle(msg.sender,from,address(0),id,value);}
    function _transfer(address from,address to,uint256 id,uint256 value) internal{if(to==address(0)) revert ZeroAddress();uint256 b=_balances[id][from];if(b<value) revert InsufficientBalance();unchecked{_balances[id][from]=b-value;}_balances[id][to]+=value;emit TransferSingle(msg.sender,from,to,id,value);}
}
