import test from 'node:test';import assert from 'node:assert/strict';import type {SqlExecutor420} from '../src/core-projections.js';import {computeJobState420,computeRequestState420,computeWorkerState420,computeResearchProjectState420,computeRewardState420,COMPUTE_READ_SCHEMA_VERSION_420} from '../src/compute-read-model.js';
const h=(n:number)=>'0x'+n.toString(16).padStart(64,'0'),a=(n:number)=>'0x'+n.toString(16).padStart(40,'0');
class Db implements SqlExecutor420{queue:unknown[]=[];calls:any[]=[];async query(sql:string,params?:readonly unknown[]){this.calls.push({sql,params});return this.queue.shift()??{rows:[]};}}
const row=(event_name:string,fields:any,n=1)=>({event_name,fields,block_number:String(n),block_hash:h(100+n),tx_hash:h(200+n),tx_index:0,log_index:n});
test('CMP-7.6 reconstructs request revisions in canonical replay order',async()=>{const db=new Db();db.queue.push({rows:[row('RequestRevision',{requestId:h(1),owner:a(1),revision:'1',actor:a(1),commitment:h(2),predecessorCommitment:h(0),status:'1'},1),row('RequestRevision',{requestId:h(1),owner:a(1),revision:'2',actor:a(1),commitment:h(3),predecessorCommitment:h(2),status:'2'},2)]});const s=await computeRequestState420(db,420n,h(1));assert.equal(s?.schemaVersion,COMPUTE_READ_SCHEMA_VERSION_420);assert.equal(s?.revision,'2');assert.equal(s?.authoritative,false);assert.match(db.calls[0].sql,/order by block_number asc/);});
test('CMP-7.6 worker projection fails if revision precedes canonical registration',async()=>{const db=new Db();db.queue.push({rows:[row('WorkerRevised',{workerId:h(1),oldRevision:'1',newRevision:'2',oldCommitment:h(2),newCommitment:h(3)})]});await assert.rejects(()=>computeWorkerState420(db,420n,h(1)),/precedes registration/);});
test('CMP-7.6 research projection preserves retirement and acceptance state',async()=>{const db=new Db();db.queue.push({rows:[row('ResearchProjectRegistered',{projectId:h(1),owner:a(1),researchDomain:h(2),revision:'1',projectCommitment:h(3)},1),row('ResearchProjectAcceptanceSet',{projectId:h(1),acceptingNewWork:false,revision:'2',projectCommitment:h(4)},2),row('ResearchProjectRetired',{projectId:h(1),revision:'3',projectCommitment:h(5)},3)]});const s=await computeResearchProjectState420(db,420n,h(1));assert.equal(s?.retired,true);assert.equal(s?.acceptingNewWork,false);assert.equal(s?.revision,'3');});
test('CMP-7.6 reward projection is accounting evidence only',async()=>{const db=new Db();db.queue.push({rows:[row('UsefulRewardAccounted',{rewardId:h(1),contributionId:h(2),poolId:h(3),beneficiary:a(1),metricId:h(4),contributionAmount:'10',amount:'20',rewardPolicyId:h(5),rewardPolicyRevision:'2',poolFundingSnapshot:'100'})]});const s=await computeRewardState420(db,420n,h(1));assert.equal(s?.amount,'20');assert.equal(s?.authoritative,false);});
test('CMP-7.6 blocks private-field contamination and malformed object ids',async()=>{const db=new Db();db.queue.push({rows:[row('RequestRevision',{requestId:h(1),owner:a(1),revision:'1',actor:a(1),commitment:h(2),predecessorCommitment:h(0),status:'1',secret:'bad'})]});await assert.rejects(()=>computeRequestState420(db,420n,h(1)),/private field leakage/);await assert.rejects(()=>computeRequestState420(new Db(),420n,'0x12'),/object id invalid/);});

test('CMP-7.6 rebuilds canonical job lifecycle without treating the indexer as authority',async()=>{const db=new Db();db.queue.push({rows:[row('JobCreated',{jobId:h(9),requestId:h(1),owner:a(1),manifestHash:h(2),workloadType:h(3),inputCommitment:h(4),outputSchemaCommitment:h(5)},1),row('WorkerAssigned',{jobId:h(9),worker:a(2),assignmentRef:h(6)},2),row('ResultRecorded',{jobId:h(9),resultCommitment:h(7)},3),row('VerifierDecision',{jobId:h(9),verifier:a(3),decisionRef:h(8),approved:true},4),row('JobTransition',{jobId:h(9),previous:'6',current:'7',previousRevision:'4',currentRevision:'5',actor:a(1),evidenceRef:h(8)},5)]});const s=await computeJobState420(db,420n,h(9));assert.equal(s?.status,'VERIFIED');assert.equal(s?.approved,true);assert.equal(s?.authoritative,false);});
test('CMP-7.6 job projection rejects transition before creation',async()=>{const db=new Db();db.queue.push({rows:[row('JobTransition',{jobId:h(9),previous:'1',current:'2',previousRevision:'1',currentRevision:'2',actor:a(1),evidenceRef:h(2)})]});await assert.rejects(()=>computeJobState420(db,420n,h(9)),/precedes creation/);});
