// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;

library CommonsIds420 {
    bytes32 internal constant COMPONENT_COMMONS = keccak256("420/COMMONS/COMPONENT/V1");

    bytes32 internal constant SERVICE_POLICY_REGISTRY = keccak256("420/COMMONS/SERVICE/POLICY_REGISTRY/V1");
    bytes32 internal constant SERVICE_SPACE_REGISTRY = keccak256("420/COMMONS/SERVICE/SPACE_REGISTRY/V1");
    bytes32 internal constant SERVICE_MEMBERSHIP_REGISTRY = keccak256("420/COMMONS/SERVICE/MEMBERSHIP_REGISTRY/V1");
    bytes32 internal constant SERVICE_ROLE_REGISTRY = keccak256("420/COMMONS/SERVICE/ROLE_REGISTRY/V1");
    bytes32 internal constant SERVICE_CHANNEL_REGISTRY = keccak256("420/COMMONS/SERVICE/CHANNEL_REGISTRY/V1");
    bytes32 internal constant SERVICE_INVITE_REGISTRY = keccak256("420/COMMONS/SERVICE/INVITE_REGISTRY/V1");

    bytes32 internal constant SPACE_COMMUNITY = keccak256("420/COMMONS/SPACE/COMMUNITY/V1");
    bytes32 internal constant SPACE_ORGANIZATION = keccak256("420/COMMONS/SPACE/ORGANIZATION/V1");
    bytes32 internal constant SPACE_COOPERATIVE = keccak256("420/COMMONS/SPACE/COOPERATIVE/V1");
    bytes32 internal constant SPACE_CREATOR_COMMUNITY = keccak256("420/COMMONS/SPACE/CREATOR_COMMUNITY/V1");
    bytes32 internal constant SPACE_MERCHANT_GROUP = keccak256("420/COMMONS/SPACE/MERCHANT_GROUP/V1");
    bytes32 internal constant SPACE_PROJECT = keccak256("420/COMMONS/SPACE/PROJECT/V1");
    bytes32 internal constant SPACE_GUILD = keccak256("420/COMMONS/SPACE/GUILD/V1");
    bytes32 internal constant SPACE_PRIVATE_GROUP = keccak256("420/COMMONS/SPACE/PRIVATE_GROUP/V1");

    bytes32 internal constant VISIBILITY_PUBLIC = keccak256("420/COMMONS/VISIBILITY/PUBLIC/V1");
    bytes32 internal constant VISIBILITY_DISCOVERABLE_PRIVATE = keccak256("420/COMMONS/VISIBILITY/DISCOVERABLE_PRIVATE/V1");
    bytes32 internal constant VISIBILITY_INVITE_ONLY = keccak256("420/COMMONS/VISIBILITY/INVITE_ONLY/V1");
    bytes32 internal constant VISIBILITY_HIDDEN = keccak256("420/COMMONS/VISIBILITY/HIDDEN/V1");

    bytes32 internal constant ADMISSION_OPEN = keccak256("420/COMMONS/ADMISSION/OPEN/V1");
    bytes32 internal constant ADMISSION_APPROVAL_REQUIRED = keccak256("420/COMMONS/ADMISSION/APPROVAL_REQUIRED/V1");
    bytes32 internal constant ADMISSION_INVITE_ONLY = keccak256("420/COMMONS/ADMISSION/INVITE_ONLY/V1");
    bytes32 internal constant ADMISSION_CREDENTIAL_GATED = keccak256("420/COMMONS/ADMISSION/CREDENTIAL_GATED/V1");
    bytes32 internal constant ADMISSION_SUBSCRIPTION_GATED = keccak256("420/COMMONS/ADMISSION/SUBSCRIPTION_GATED/V1");
    bytes32 internal constant ADMISSION_CUSTOM_ADAPTER = keccak256("420/COMMONS/ADMISSION/CUSTOM_ADAPTER/V1");

    bytes32 internal constant CHANNEL_CHAT = keccak256("420/COMMONS/CHANNEL/CHAT/V1");
    bytes32 internal constant CHANNEL_ANNOUNCEMENTS = keccak256("420/COMMONS/CHANNEL/ANNOUNCEMENTS/V1");
    bytes32 internal constant CHANNEL_FORUM = keccak256("420/COMMONS/CHANNEL/FORUM/V1");
    bytes32 internal constant CHANNEL_FILES = keccak256("420/COMMONS/CHANNEL/FILES/V1");
    bytes32 internal constant CHANNEL_VOICE = keccak256("420/COMMONS/CHANNEL/VOICE/V1");
    bytes32 internal constant CHANNEL_VIDEO = keccak256("420/COMMONS/CHANNEL/VIDEO/V1");
    bytes32 internal constant CHANNEL_EVENT = keccak256("420/COMMONS/CHANNEL/EVENT/V1");
    bytes32 internal constant CHANNEL_GOVERNANCE_DISCUSSION = keccak256("420/COMMONS/CHANNEL/GOVERNANCE_DISCUSSION/V1");

    bytes32 internal constant ACTION_UPDATE_SPACE = keccak256("420/COMMONS/ACTION/UPDATE_SPACE/V1");
    bytes32 internal constant ACTION_APPROVE_MEMBER = keccak256("420/COMMONS/ACTION/APPROVE_MEMBER/V1");
    bytes32 internal constant ACTION_SUSPEND_MEMBER = keccak256("420/COMMONS/ACTION/SUSPEND_MEMBER/V1");
    bytes32 internal constant ACTION_BAN_MEMBER = keccak256("420/COMMONS/ACTION/BAN_MEMBER/V1");
    bytes32 internal constant ACTION_ASSIGN_ROLE = keccak256("420/COMMONS/ACTION/ASSIGN_ROLE/V1");
    bytes32 internal constant ACTION_CREATE_CHANNEL = keccak256("420/COMMONS/ACTION/CREATE_CHANNEL/V1");
    bytes32 internal constant ACTION_MODIFY_CHANNEL = keccak256("420/COMMONS/ACTION/MODIFY_CHANNEL/V1");
    bytes32 internal constant ACTION_CREATE_INVITE = keccak256("420/COMMONS/ACTION/CREATE_INVITE/V1");
    bytes32 internal constant ACTION_REVOKE_INVITE = keccak256("420/COMMONS/ACTION/REVOKE_INVITE/V1");
}
