// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.24;

enum GrowthStage { NONE, PROPAGATION, VEGETATIVE, FLOWERING, MATURATION }
enum PlantState { NONE, ACTIVE, HARVESTABLE, HARVESTED, TERMINATED }
enum BreedingState { NONE, COMMITTED, RANDOMNESS_PENDING, FINALIZABLE, FINALIZED, CANCELLED }
enum EquipmentState { NONE, ACTIVE, DEGRADED, BROKEN, RETIRED, RECYCLED }
enum ListingState { NONE, ACTIVE, PARTIALLY_FILLED, FILLED, CANCELLED, EXPIRED }
enum LeaseState { NONE, OFFERED, ACTIVE, COMPLETED, TERMINATED, CANCELLED }
enum LicenseState { NONE, ACTIVE, EXPIRED, REVOKED, TRANSFERRED }
enum ProposalState { NONE, PENDING, ACTIVE, DEFEATED, SUCCEEDED, EXECUTABLE, EXECUTED, EXPIRED, CANCELLED }
enum SeasonState { NONE, SCHEDULED, ACTIVE, CLOSED, FINALIZED }
enum CompetitionState { NONE, SCHEDULED, OPEN, CLOSED, RANDOMNESS_PENDING, FINALIZABLE, FINALIZED, CANCELLED }
enum RandomnessState { NONE, REQUESTED, COMMITTED, FINALIZED, CONSUMED, INVALIDATED }
enum UpgradeState { NONE, PROPOSED, QUALIFIED, SCHEDULED, ACTIVE, DRAINING, RETIRED, REJECTED }
enum MissionState { NONE, ELIGIBLE, ACTIVE, COMPLETE, CLAIMED, FAILED, EXPIRED }

enum AuthorityClass {
    OWNER,
    SESSION,
    DELEGATE,
    ORGANIZATION,
    COOPERATIVE,
    MODULE,
    SECURITY_COUNCIL,
    UPGRADE_AUTHORITY,
    GENESIS_AUTHORITY
}

enum RiskClass { R0, R1, R2, R3, R4 }
