import {createHash} from "node:crypto";
const stable=x=>JSON.stringify(x);
const digest=x=>createHash("sha256").update(stable(x)).digest("hex");
const ref=x=>{if(typeof x!=="string"||!/^[A-Za-z0-9][A-Za-z0-9:_-]{0,127}$/.test(x))throw Error("INVALID_ID");return x;};
const transitions={
 program:{DRAFT:["ACTIVE"],ACTIVE:["PAUSED","RETIRED"],PAUSED:["ACTIVE","RETIRED"],RETIRED:[]},
 season:{DRAFT:["SCHEDULED","CANCELLED"],SCHEDULED:["NOMINATIONS_OPEN","CANCELLED"],NOMINATIONS_OPEN:["NOMINATIONS_CLOSED","CANCELLED"],NOMINATIONS_CLOSED:["BALLOT_FROZEN","CANCELLED"],BALLOT_FROZEN:["VOTING_OPEN","CANCELLED"],VOTING_OPEN:["VOTING_CLOSED","CANCELLED"],VOTING_CLOSED:["FINALIZED","CANCELLED"],FINALIZED:["ARCHIVED"],ARCHIVED:[],CANCELLED:[]},
 category:{DRAFT:["ACTIVE"],ACTIVE:["CLOSED"],CLOSED:["RETIRED"],RETIRED:[]},
 nomination:{SUBMITTED:["ACCEPTED","REJECTED","WITHDRAWN","DISQUALIFIED"],ACCEPTED:["WITHDRAWN","DISQUALIFIED"],REJECTED:[],WITHDRAWN:[],DISQUALIFIED:[]},
 ballot:{DRAFT:["FROZEN","VOID"],FROZEN:["OPEN","VOID"],OPEN:["CLOSED","VOID"],CLOSED:["FINALIZED","VOID"],FINALIZED:[],VOID:[]}
};
const move=(object,to,graph)=>{if(!graph[object.state]?.includes(to))throw Error("INVALID_TRANSITION");return {...object,state:to,revision:object.revision+1};};
const frozen=x=>structuredClone(x);
export class AwardsDomain420 {
 constructor({authority}={}){if(typeof authority!=="function")throw Error("AUTHORITY_REQUIRED");this.authority=authority;this.programs=new Map();this.seasons=new Map();this.categories=new Map();this.policies=new Map();this.nominations=new Map();this.ballots=new Map();this.votes=new Map();this.results=new Map();this.badges=new Map();}
 authorize(actor,action){if(!this.authority(actor,action))throw Error("UNAUTHORIZED");}
 put(map,item){ref(item.id);if(map.has(item.id))throw Error("ID_REUSED");map.set(item.id,frozen(item));return frozen(item);}
 get(map,id){const item=map.get(ref(id));if(!item)throw Error("NOT_FOUND");return frozen(item);}
 program(actor,{id,name}){this.authorize(actor,"program");if(typeof name!=="string"||!name.trim()||name.length>120)throw Error("INVALID_NAME");return this.put(this.programs,{id,name,state:"DRAFT",revision:1});}
 policy(actor,{id,version,rules}){this.authorize(actor,"policy");if(!Number.isSafeInteger(version)||version<1||!rules||typeof rules!=="object"||Array.isArray(rules)||!Object.keys(rules).length)throw Error("INVALID_POLICY");return this.put(this.policies,{id,version,rules:frozen(rules),commitment:digest({id,version,rules})});}
 season(actor,{id,programId,policyId,nominationStart,nominationEnd,votingStart,votingEnd}){this.authorize(actor,"season");this.get(this.programs,programId);const p=this.get(this.policies,policyId);if(![nominationStart,nominationEnd,votingStart,votingEnd].every(Number.isSafeInteger)||!(nominationStart<nominationEnd&&nominationEnd<votingStart&&votingStart<votingEnd))throw Error("INVALID_WINDOWS");return this.put(this.seasons,{id,programId,policyId,policyCommitment:p.commitment,nominationStart,nominationEnd,votingStart,votingEnd,state:"DRAFT",revision:1});}
 category(actor,{id,seasonId,policyId,key,targetType,definitionCommitment,version=1}){this.authorize(actor,"category");const s=this.get(this.seasons,seasonId),p=this.get(this.policies,policyId);if(s.state!=="DRAFT"||!["RECORDING","CREATOR_PROFILE"].includes(targetType)||!Number.isSafeInteger(version)||version<1)throw Error("INVALID_CATEGORY");ref(key);ref(definitionCommitment);return this.put(this.categories,{id,seasonId,policyId,policyCommitment:p.commitment,key,targetType,definitionCommitment,version,state:"DRAFT",revision:1});}
 change(actor,type,id,to){this.authorize(actor,type);const maps={program:this.programs,season:this.seasons,category:this.categories,nomination:this.nominations,ballot:this.ballots};const map=maps[type];if(!map)throw Error("UNKNOWN_TYPE");const old=this.get(map,id);
 if(type==="season"&&to==="NOMINATIONS_OPEN"){if(this.get(this.programs,old.programId).state!=="ACTIVE"||![...this.categories.values()].some(c=>c.seasonId===id&&c.state==="ACTIVE"))throw Error("NOT_READY");}
 if(type==="season"&&to==="BALLOT_FROZEN"&&![...this.ballots.values()].some(b=>b.seasonId===id&&b.state==="FROZEN"))throw Error("BALLOT_NOT_FROZEN");
 if(type==="season"&&to==="FINALIZED"&&[...this.ballots.values()].some(b=>b.seasonId===id&&b.state!=="FINALIZED"))throw Error("BALLOT_NOT_FINALIZED");
 if(type==="ballot"&&to==="FROZEN"&&this.get(this.seasons,old.seasonId).state!=="NOMINATIONS_CLOSED")throw Error("NOMINATIONS_STILL_OPEN");
 if(type==="ballot"&&to==="OPEN"&&this.get(this.seasons,old.seasonId).state!=="BALLOT_FROZEN")throw Error("SEASON_NOT_READY");
 if(type==="ballot"&&to==="FINALIZED"&&![...this.results.values()].some(r=>r.ballotId===id))throw Error("RESULT_REQUIRED");
 const next=move(old,to,transitions[type]);map.set(id,next);return frozen(next);}
 nomination(actor,{id,seasonId,categoryId,targetType,targetId,eligibilityCommitment,submittedAt,nominatorRef}){this.authorize(actor,"nomination");const s=this.get(this.seasons,seasonId),c=this.get(this.categories,categoryId);if(s.state!=="NOMINATIONS_OPEN"||c.seasonId!==seasonId||c.targetType!==targetType||c.state!=="ACTIVE"||submittedAt<s.nominationStart||submittedAt>s.nominationEnd)throw Error("NOT_ELIGIBLE");ref(targetId);ref(eligibilityCommitment);ref(nominatorRef);if(!Number.isSafeInteger(submittedAt))throw Error("INVALID_TIME");return this.put(this.nominations,{id,seasonId,categoryId,targetType,targetId,nominatorRef,eligibilityCommitment,submittedAt,state:"SUBMITTED",revision:1});}
 ballot(actor,{id,seasonId,categoryId,candidateIds}){this.authorize(actor,"ballot");const s=this.get(this.seasons,seasonId),c=this.get(this.categories,categoryId);if(s.state!=="NOMINATIONS_CLOSED"||c.seasonId!==seasonId||!Array.isArray(candidateIds)||!candidateIds.length||new Set(candidateIds).size!==candidateIds.length)throw Error("INVALID_BALLOT");const normalized=[...candidateIds].sort();for(const n of normalized){const x=this.get(this.nominations,n);if(x.seasonId!==seasonId||x.categoryId!==categoryId||x.state!=="ACCEPTED")throw Error("INVALID_CANDIDATE");}
 return this.put(this.ballots,{id,seasonId,categoryId,candidateIds:normalized,candidateSetCommitment:digest(normalized),policyCommitment:c.policyCommitment,state:"DRAFT",revision:1});}
 vote(actor,{id,ballotId,voterEligibilityRef,choiceCommitment,replayDomain,submittedAt}){this.authorize(actor,"vote");const b=this.get(this.ballots,ballotId),s=this.get(this.seasons,b.seasonId);if(b.state!=="OPEN"||s.state!=="VOTING_OPEN"||!Number.isSafeInteger(submittedAt)||submittedAt<s.votingStart||submittedAt>s.votingEnd)throw Error("VOTE_CLOSED");[voterEligibilityRef,choiceCommitment,replayDomain].forEach(ref);return this.put(this.votes,{id,ballotId,voterEligibilityRef,choiceCommitment,replayDomain,submittedAt,state:"ACCEPTED"});}
 result(actor,{id,ballotId,winnerTargetIds,resultCommitment,finalizedAt}){this.authorize(actor,"result");const b=this.get(this.ballots,ballotId),s=this.get(this.seasons,b.seasonId);if(b.state!=="CLOSED"||s.state!=="VOTING_CLOSED"||[...this.results.values()].some(r=>r.ballotId===ballotId)||!Array.isArray(winnerTargetIds)||!Number.isSafeInteger(finalizedAt))throw Error("INVALID_RESULT");winnerTargetIds.forEach(ref);ref(resultCommitment);const v={id,ballotId,seasonId:b.seasonId,categoryId:b.categoryId,winnerTargetIds:[...winnerTargetIds],resultCommitment,policyCommitment:b.policyCommitment,finalizedAt,state:"FINALIZED"};return this.put(this.results,v);}
 badge(actor,{id,resultId,targetId}){this.authorize(actor,"badge");const r=this.get(this.results,resultId);if(r.state!=="FINALIZED"||!r.winnerTargetIds.includes(targetId))throw Error("INVALID_BADGE");return this.put(this.badges,{id,resultId,targetId,seasonId:r.seasonId,categoryId:r.categoryId,state:"ISSUED"});}
}
