export class StatusControlError420 extends Error{constructor(message){super(message);this.name='StatusControlError420';}}
const HEALTH=new Set(['healthy','degraded','unavailable','unknown']);
function assert420(c,m){if(!c)throw new StatusControlError420(m);}
function observedAt420(value){const ms=Date.parse(value);assert420(Number.isFinite(ms),'observedAt must be an ISO date-time');return new Date(ms).toISOString();}
function hexChainId420(value){assert420(typeof value==='string'&&/^0x[0-9a-fA-F]+$/.test(value),'canonical RPC returned invalid chainId');return BigInt(value).toString(10);}
function normalizeService420(name,endpoint,result,observedAt){const state=HEALTH.has(result?.state)?result.state:'unknown';return Object.freeze({name,endpoint,state,live:result?.live===true,ready:result?.ready===true,detail:typeof result?.detail==='string'?result.detail:null,observedAt,canonicalAuthority:false,source:`service:${name}`});}
export function createStatusControlView420(network){assert420(network&&typeof network.chainIdDecimal==='string','discovered network is required');return Object.freeze({title:'420 Developer Hub status',chainId:network.chainIdDecimal,environment:network.environment,canonicalAuthority:false,statusAuthority:'operational-observation-only',securityRule:'health and readiness are operational evidence only; they do not prove finality, settlement, ownership, authorization, Registry legitimacy, or protocol safety',supported:Object.freeze(['canonical-rpc-chain-identity','canonical-rpc-liveness','420indexer-health-readiness-status','manifest-service-reachability','420status-observation'])});}
export function createStatusAggregator420({network,rpc,indexer,serviceProbe,clock=()=>new Date().toISOString()}){assert420(network&&typeof network.chainIdDecimal==='string'&&typeof network.service==='function','discovered network is required');assert420(rpc&&typeof rpc.request==='function','canonical RPC adapter is required');assert420(indexer&&typeof indexer.diagnostics==='function','420Indexer client is required');assert420(typeof serviceProbe==='function','service probe is required');
 async function snapshot(){const observedAt=observedAt420(clock());let rpcChainId=null,rpcBlockNumber=null,rpcError=null;try{rpcChainId=hexChainId420(await rpc.request('eth_chainId',[]));assert420(rpcChainId===network.chainIdDecimal,'canonical RPC chainId does not match selected network');rpcBlockNumber=await rpc.request('eth_blockNumber',[]);}catch(error){if(error instanceof StatusControlError420)throw error;rpcError=error instanceof Error?error.message:String(error);}
 let indexerDiagnostics=null,indexerError=null;try{indexerDiagnostics=await indexer.diagnostics();assert420(String(indexerDiagnostics.chainId)===network.chainIdDecimal,'420Indexer chainId does not match selected network');}catch(error){indexerError=error instanceof Error?error.message:String(error);}
 const serviceNames=['explorer','verify','status'];const services=[];for(const name of serviceNames){const endpoint=network.service(name);if(!endpoint){services.push(Object.freeze({name,endpoint:null,state:'unknown',live:false,ready:false,detail:'not configured',observedAt,canonicalAuthority:false,source:`service:${name}`}));continue;}try{services.push(normalizeService420(name,endpoint,await serviceProbe(name,endpoint),observedAt));}catch(error){services.push(Object.freeze({name,endpoint,state:'unavailable',live:false,ready:false,detail:error instanceof Error?error.message:String(error),observedAt,canonicalAuthority:false,source:`service:${name}`}));}}
 const rpcState=rpcError?'unavailable':'healthy';const indexerState=indexerError?'unavailable':(indexerDiagnostics?.readiness?.ready===false?'degraded':'healthy');const states=[rpcState,indexerState,...services.map(x=>x.state)];const overall=states.includes('unavailable')?'degraded':states.includes('degraded')?'degraded':states.every(x=>x==='healthy')?'healthy':'unknown';
 return Object.freeze({schemaVersion:'1.0.0',observedAt,chainId:network.chainIdDecimal,environment:network.environment,overall,canonicalAuthority:false,statusAuthority:'operational-observation-only',canonicalRpc:Object.freeze({state:rpcState,chainId:rpcChainId,blockNumber:rpcBlockNumber,error:rpcError,source:'canonical-rpc',canonicalStateReference:rpcError?false:true}),indexer:Object.freeze({state:indexerState,error:indexerError,diagnostics:indexerDiagnostics,source:'420Indexer',canonicalAuthority:false}),services:Object.freeze(services),securityRule:'a green status is not proof of finality, settlement, ownership, authorization, Registry legitimacy, or protocol safety'});}
 return Object.freeze({snapshot,view:()=>createStatusControlView420(network),canonicalAuthority:false});}
