import {validateRuntimeConfig,runtimeReadiness} from './core/config.js';
import {LaunchpadService,normalizeCampaign,progress} from './core/service.js';
import {connectWallet,executionGate,submitReviewedTransaction} from './core/wallet.js';

const state={config:null,service:null,wallet:null,campaigns:[],selected:null,participant:null,review:null};
const $=s=>document.querySelector(s);
const setText=(s,v)=>{const n=$(s);if(n)n.textContent=String(v??'');};
function status(message,error=false){setText('#status',message);$('#status')?.setAttribute('data-state',error?'error':'ready');}
function setBusy(b){for(const el of document.querySelectorAll('button'))el.disabled=b||el.dataset.blocked==='true';}
function label(v){return String(v||'UNKNOWN').replaceAll('_',' ');}
function renderRuntime(){const r=runtimeReadiness(state.config,{walletChainId:state.wallet?.chainId});setText('#runtime-state',r.ready?'Canonical runtime resolved':'Execution locked Â· '+r.missing.join(', '));}
function renderWallet(){setText('#wallet-state',state.wallet?state.wallet.account.slice(0,6)+'â¦'+state.wallet.account.slice(-4):'Not connected');renderRuntime();}
function card(c){const b=document.createElement('button');b.type='button';b.className='campaign-card';b.innerHTML='<span class="mode"></span><strong></strong><span class="state"></span><p></p><div class="meter"><span></span></div><small></small>';b.querySelector('.mode').textContent=label(c.mode);b.querySelector('strong').textContent=c.title;b.querySelector('.state').textContent=label(c.state);b.querySelector('p').textContent=c.summary;const p=progress(c);b.querySelector('.meter span').style.width=p+'%';b.querySelector('small').textContent=c.raised+' / '+c.hardCap+' Â· '+p+'%';b.addEventListener('click',()=>openCampaign(c.saleId));return b;}
function renderCampaigns(){const grid=$('#campaign-grid');grid.replaceChildren(...state.campaigns.map(card));$('#empty-state').hidden=state.campaigns.length>0;}
function actionState(){const c=state.selected,w=!!state.wallet;const map=[['#contribute',w&&c?.state==='ACTIVE'],['#claim',w&&c?.state==='SUCCEEDED'],['#refund',w&&['FAILED','CANCELLED'].includes(c?.state)]];for(const [s,on] of map){const b=$(s);if(!b)continue;b.dataset.blocked=on?'false':'true';b.disabled=!on;}}
function renderDetail(){const c=state.selected;$('#detail').hidden=!c;if(!c)return;for(const [s,v] of [['#detail-title',c.title],['#detail-summary',c.summary],['#detail-mode',label(c.mode)],['#detail-state',label(c.state)],['#detail-sale',c.saleId],['#detail-project',c.projectId],['#detail-controller',c.controller],['#detail-payment',c.paymentAsset],['#detail-receiver',c.proceedsReceiver],['#detail-raised',c.raised],['#detail-hardcap',c.hardCap],['#detail-softcap',c.softCap],['#detail-policy',c.eligibilityPolicyHash]])setText(s,v);setText('#participant-state',state.participant?'Contributed '+(state.participant.contributed||0)+' Â· claimed '+(state.participant.claimed||0)+' Â· refunded '+(state.participant.refunded?'yes':'no'):'Connect wallet for participant status');actionState();}
async function loadCampaigns(){setBusy(true);status('Loading campaignsâ¦');try{const p=await state.service.campaigns();state.campaigns=(p.items||[]).map(normalizeCampaign);renderCampaigns();status(state.campaigns.length?'Campaigns loaded.':'No campaigns are currently published.');}catch(e){state.campaigns=[];renderCampaigns();status(e.message||String(e),true);}finally{setBusy(false);actionState();}}
async function openCampaign(saleId){setBusy(true);status('Loading campaignâ¦');try{const p=await state.service.campaign(saleId);state.selected=normalizeCampaign(p.campaign);state.participant=state.wallet?(await state.service.participant(saleId,state.wallet.account)).participant:null;renderDetail();status('Campaign detail loaded.');}catch(e){status(e.message||String(e),true);}finally{setBusy(false);actionState();}}
async function connect(){setBusy(true);try{state.wallet=await connectWallet(globalThis.ethereum);renderWallet();if(state.selected)await openCampaign(state.selected.saleId);status('Wallet connected. Review every transaction before signing.');}catch(e){status(e.message||String(e),true);}finally{setBusy(false);actionState();}}
function showReview(r){state.review=r;$('#review').hidden=false;for(const [s,v] of [['#review-kind',r.kind],['#review-summary',r.summary],['#review-to',r.transaction.to],['#review-value',r.transaction.value||'0x0'],['#review-data',r.transaction.data]])setText(s,v);const g=executionGate({config:state.config,wallet:state.wallet,review:r});setText('#review-gate',g.ok?'Ready for wallet review':g.reason);$('#submit-review').disabled=!g.ok;}
async function prepare(kind,payload={}){if(!state.selected||!state.wallet)return;setBusy(true);try{showReview(await state.service.prepare(kind,{saleId:state.selected.saleId,account:state.wallet.account,...payload}));status('Transaction prepared for explicit wallet review.');}catch(e){status(e.message||String(e),true);}finally{setBusy(false);actionState();}}
async function submit(){setBusy(true);try{const tx=await submitReviewedTransaction({ethereum:globalThis.ethereum,config:state.config,wallet:state.wallet,review:state.review});setText('#tx-hash',tx);$('#review').hidden=true;state.review=null;status('Transaction submitted. Confirm canonical chain state before retrying.');}catch(e){status(e.message||String(e),true);}finally{setBusy(false);actionState();}}
const CREATOR=new Set(['setCampaignMode','activate','finalize','cancel']);
async function creator(event){event.preventDefault();if(!state.wallet)return status('Connect wallet before creator requests.',true);const f=new FormData(event.currentTarget),action=String(f.get('action')||'');if(!CREATOR.has(action))return status('Unsupported creator request.',true);setBusy(true);try{const request=await state.service.creatorRequest({action,account:state.wallet.account,projectId:String(f.get('projectId')||''),saleId:String(f.get('saleId')||''),metadataHash:String(f.get('metadataHash')||''),mode:String(f.get('mode')||'')});setText('#creator-request-state',request.notice);status('Creator governance request prepared. No direct mutation authority was granted.');}catch(e){status(e.message||String(e),true);}finally{setBusy(false);actionState();}}
async function boot(){try{const r=await fetch('./runtime-config.json',{cache:'no-store'});if(!r.ok)throw new Error('runtime configuration unavailable');state.config=validateRuntimeConfig(await r.json());renderRuntime();if(!state.config.api.baseUrl)return status('Launchpad runtime is not published yet. Discovery and execution remain fail-closed.');state.service=new LaunchpadService({baseUrl:state.config.api.baseUrl,expectedSchema:state.config.api.projectionSchema});const rt=await state.service.runtime();if(state.config.network.chainId&&rt.chainId.toLowerCase()!==state.config.network.chainId.toLowerCase())throw new Error('Launchpad service chain mismatch');state.config={...state.config,network:{...state.config.network,chainId:rt.chainId},registry:{...state.config.registry,launchpadRouterAddress:rt.launchpadRouterAddress,allocationRegistryAddress:rt.allocationRegistryAddress,crowdfundingIntegrationAddress:rt.crowdfundingIntegrationAddress}};renderRuntime();await loadCampaigns();}catch(e){status(e.message||String(e),true);}}
$('#connect-wallet')?.addEventListener('click',connect);$('#refresh')?.addEventListener('click',()=>state.service&&loadCampaigns());$('#contribute')?.addEventListener('click',()=>prepare('contribute',{amount:$('#contribution-amount').value,paymentId:$('#payment-id').value.trim()}));$('#claim')?.addEventListener('click',()=>prepare('claim',{deliveryCommitment:$('#delivery-commitment').value.trim()}));$('#refund')?.addEventListener('click',()=>prepare('refund',{refundCommitment:$('#refund-commitment').value.trim()}));$('#submit-review')?.addEventListener('click',submit);$('#close-review')?.addEventListener('click',()=>{$('#review').hidden=true;state.review=null;});$('#creator-form')?.addEventListener('submit',creator);boot();
