import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createComputeJobApi420, routeComputeJobApi420 } from '../src/job-api.js';

async function fixture(){return JSON.parse(await readFile(resolve(process.cwd(),'../../packages/420-sdk/test/fixtures/compute-request-vector.json'),'utf8'));}
function host(){return {network:{chainId:420n,chainIdDecimal:'420'},contract(name:string){return name==='ComputeRequestRegistry420'?{name,address:'0x0000000000000000000000000000000000000042',version:'1',verified:true as const}:null;}};}
const jobId='0x'+'aa'.repeat(32), operationId='0x'+'bb'.repeat(32);
function store(){return {async job(chainId:bigint,id:string){if(chainId===420n&&id===jobId)return {schemaVersion:'420-compute-api-v1' as const,chainId:'420',jobId,requestId:'0x'+'cc'.repeat(32),status:'MATCHED',finality:'safe' as const,authoritative:false as const};return null;}};}

test('CMP-7.2 POST job prepares Wallet-authorized canonical request intent without signing',async()=>{const f=await fixture();const api=createComputeJobApi420(host(),store());const out=await routeComputeJobApi420(api,'POST','/v1/compute/jobs',{chainId:'420',operationId,requestId:f.requestId,request:f.request});assert.equal(out.status,202);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const plan=out.body.data as any;assert.equal(plan.status,'READY_FOR_WALLET_AUTHORIZATION');assert.equal(plan.intent.target.name,'ComputeRequestRegistry420');assert.equal(plan.intent.requiresWalletAuthorization,true);assert.equal(plan.canonicalState,false);assert.equal(plan.secretMaterialManaged,false);});
test('CMP-7.2 rejects cross-chain submission before constructing an intent',async()=>{const f=await fixture();const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'POST','/v1/compute/jobs',{chainId:'421',operationId,requestId:f.requestId,request:f.request});assert.equal(out.status,409);});
test('CMP-7.2 refuses secret material in submission payloads',async()=>{const f=await fixture();const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'POST','/v1/compute/jobs',{chainId:'420',operationId,requestId:f.requestId,request:{...f.request,privateKey:'0xdead'}});assert.equal(out.status,400);assert.ok(out.body&&typeof out.body==='object'&&'error' in out.body);assert.match((out.body.error as {message:string}).message,/secret material/);});
test('CMP-7.2 job reads are explicitly non-authoritative projections',async()=>{const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'GET','/v1/compute/jobs/'+jobId);assert.equal(out.status,200);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const data=out.body.data as {authoritative:boolean;finality:string};assert.equal(data.authoritative,false);assert.equal(data.finality,'safe');});
test('CMP-7.2 rejects unsupported methods and malformed routes',async()=>{const api=createComputeJobApi420(host(),store());assert.equal((await routeComputeJobApi420(api,'GET','/v1/compute/jobs')).status,405);assert.equal((await routeComputeJobApi420(api,'GET','/v1/compute/jobs/0x12')).status,404);});
