import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createComputeJobApi420, routeComputeJobApi420 } from '../src/job-api.js';

async function fixture(){return JSON.parse(await readFile(resolve(process.cwd(),'../../packages/420-sdk/test/fixtures/compute-request-vector.json'),'utf8'));}
function host(){return {network:{chainId:420n,chainIdDecimal:'420'},contract(name:string){return name==='ComputeRequestRegistry420'?{name,address:'0x0000000000000000000000000000000000000042',version:'1',verified:true as const}:null;}};}
const jobId='0x'+'aa'.repeat(32), operationId='0x'+'bb'.repeat(32);
const workerId='0x'+'dd'.repeat(32), verifierId='0x'+'ee'.repeat(32), projectId='0x'+'99'.repeat(32);
function store(){return {
  async job(chainId,id){if(chainId===420n&&id===jobId)return {schemaVersion:'420-compute-api-v1' as const,chainId:'420',jobId,requestId:'0x'+'cc'.repeat(32),status:'MATCHED',finality:'safe' as const,authoritative:false as const};return null;},
  async worker(chainId,id){if(chainId===420n&&id===workerId)return {schemaVersion:'420-compute-api-v1' as const,chainId:'420',workerId,providerId:'0x'+'01'.repeat(32),nodeId:'0x'+'02'.repeat(32),resourceId:'0x'+'03'.repeat(32),status:'ACTIVE',liveCapacityUnits:'4',availableCapacityUnits:'2',activeOfferIds:['0x'+'04'.repeat(32)],finality:'safe' as const,authoritative:false as const};return null;},
  async verifier(chainId,id){if(chainId===420n&&id===verifierId)return {schemaVersion:'420-compute-api-v1' as const,chainId:'420',verifierId,operator:'0x'+'11'.repeat(20),status:'ACTIVE',classIds:['0x'+'12'.repeat(32)],policyIds:['0x'+'13'.repeat(32)],finality:'safe' as const,authoritative:false as const};return null;},
  async verification(chainId,id){if(chainId===420n&&id===jobId)return {schemaVersion:'420-compute-api-v1' as const,chainId:'420',jobId,policyId:'0x'+'14'.repeat(32),verdict:'VERIFIED',decisionRef:'0x'+'15'.repeat(32),verifierIds:[verifierId],challengeDeadline:'1200',finality:'safe' as const,authoritative:false as const};return null;},
  async researchProject(chainId,id){if(chainId===420n&&id===projectId)return {schemaVersion:'420-compute-api-v1' as const,chainId:'420',projectId,owner:'0x'+'21'.repeat(20),projectCommitment:'0x'+'22'.repeat(32),metadataCommitment:'0x'+'23'.repeat(32),revision:'3',active:true,resultCount:'1',finality:'safe' as const,authoritative:false as const};return null;},
  async researchResults(chainId,id){if(chainId===420n&&id===projectId)return [{schemaVersion:'420-compute-api-v1' as const,chainId:'420',resultId:'0x'+'24'.repeat(32),projectId,workUnitId:'0x'+'25'.repeat(32),provenanceRef:'0x'+'26'.repeat(32),verificationDecisionRef:'0x'+'27'.repeat(32),publicationPolicyId:'0x'+'28'.repeat(32),finality:'safe' as const,authoritative:false as const}];return [];}
};}

test('CMP-7.2 POST job prepares Wallet-authorized canonical request intent without signing',async()=>{const f=await fixture();const api=createComputeJobApi420(host(),store());const out=await routeComputeJobApi420(api,'POST','/v1/compute/jobs',{chainId:'420',operationId,requestId:f.requestId,request:f.request});assert.equal(out.status,202);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const plan=out.body.data as any;assert.equal(plan.status,'READY_FOR_WALLET_AUTHORIZATION');assert.equal(plan.intent.target.name,'ComputeRequestRegistry420');assert.equal(plan.intent.requiresWalletAuthorization,true);assert.equal(plan.canonicalState,false);assert.equal(plan.secretMaterialManaged,false);});
test('CMP-7.2 rejects cross-chain submission before constructing an intent',async()=>{const f=await fixture();const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'POST','/v1/compute/jobs',{chainId:'421',operationId,requestId:f.requestId,request:f.request});assert.equal(out.status,409);});
test('CMP-7.2 refuses secret material in submission payloads',async()=>{const f=await fixture();const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'POST','/v1/compute/jobs',{chainId:'420',operationId,requestId:f.requestId,request:{...f.request,privateKey:'0xdead'}});assert.equal(out.status,400);assert.ok(out.body&&typeof out.body==='object'&&'error' in out.body);assert.match((out.body.error as {message:string}).message,/secret material/);});
test('CMP-7.2 job reads are explicitly non-authoritative projections',async()=>{const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'GET','/v1/compute/jobs/'+jobId);assert.equal(out.status,200);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const data=out.body.data as any;assert.equal(data.authoritative,false);assert.equal(data.finality,'safe');});
test('CMP-7.2 rejects unsupported methods and malformed routes',async()=>{const api=createComputeJobApi420(host(),store());assert.equal((await routeComputeJobApi420(api,'GET','/v1/compute/jobs')).status,405);assert.equal((await routeComputeJobApi420(api,'GET','/v1/compute/jobs/0x12')).status,404);});

test('CMP-7.3 worker API exposes scoped capacity/offer projection without protocol authority',async()=>{const api=createComputeJobApi420(host(),store());const out=await routeComputeJobApi420(api,'GET','/v1/compute/workers/'+workerId);assert.equal(out.status,200);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const data=out.body.data as any;assert.equal(data.workerId,workerId);assert.equal(data.status,'ACTIVE');assert.equal(data.availableCapacityUnits,'2');assert.equal(data.authoritative,false);});
test('CMP-7.3 worker API fails closed when the worker projection backend is unavailable',async()=>{const api=createComputeJobApi420(host(),{job:store().job});const out=await routeComputeJobApi420(api,'GET','/v1/compute/workers/'+workerId);assert.equal(out.status,503);});
test('CMP-7.3 worker API rejects state-changing methods at the read endpoint',async()=>{const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'POST','/v1/compute/workers/'+workerId,{});assert.equal(out.status,405);});

test('CMP-7.4 verifier API exposes verifier identity/capability projection without granting verdict authority',async()=>{const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'GET','/v1/compute/verifiers/'+verifierId);assert.equal(out.status,200);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const data=out.body.data as any;assert.equal(data.status,'ACTIVE');assert.equal(data.authoritative,false);});
test('CMP-7.4 verification API distinguishes projected verdict and challenge deadline from canonical authority',async()=>{const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'GET','/v1/compute/verifications/'+jobId);assert.equal(out.status,200);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const data=out.body.data as any;assert.equal(data.verdict,'VERIFIED');assert.equal(data.challengeDeadline,'1200');assert.equal(data.authoritative,false);});
test('CMP-7.4 verifier API fails closed when verifier backing data is unavailable',async()=>{const base=store();const out=await routeComputeJobApi420(createComputeJobApi420(host(),{job:base.job,worker:base.worker}),'GET','/v1/compute/verifiers/'+verifierId);assert.equal(out.status,503);});

test('CMP-7.5 research project API returns project identity/revision without inventing project authority',async()=>{const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'GET','/v1/compute/research/projects/'+projectId);assert.equal(out.status,200);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const data=out.body.data as any;assert.equal(data.revision,'3');assert.equal(data.active,true);assert.equal(data.authoritative,false);});
test('CMP-7.5 research results remain bounded provenance/verification/publication projections',async()=>{const out=await routeComputeJobApi420(createComputeJobApi420(host(),store()),'GET','/v1/compute/research/projects/'+projectId+'/results');assert.equal(out.status,200);assert.ok(out.body&&typeof out.body==='object'&&'data' in out.body);const data=out.body.data as any[];assert.equal(data.length,1);assert.equal(data[0].projectId,projectId);assert.equal(data[0].authoritative,false);});
test('CMP-7.5 research API fails closed when the projection backend is absent',async()=>{const base=store();const out=await routeComputeJobApi420(createComputeJobApi420(host(),{job:base.job}),'GET','/v1/compute/research/projects/'+projectId);assert.equal(out.status,503);});
