/* global COMMERCE_CONFIG */
import {createCommerceSdk420} from '../../packages/420-sdk/dist/commerce.js';
import {WalletSession} from './core/wallet.js';
import {productChange,listingChange,renderPreview,appendText,transactionTerms} from './core/builder.js';
const $=id=>document.getElementById(id),forms=[...document.querySelectorAll('form')];
let session=null,sdk=null,storeId=null,data=null,busy=false,epoch=0,plan=null,dirty=false;
const mediaURLs=new Map();
const values=form=>Object.fromEntries(new FormData(form));
const field=(form,name)=>$(form).elements.namedItem(name);
const message=text=>{$('status').textContent=text;$('error').hidden=true;};
const error=e=>{$('error').textContent=e.code??e.message??'Unable to verify this action. Try again.';$('error').hidden=false;$('error').focus();};
function clearSelections(){for(const [form,name,empty] of [['product-form','id','New product'],['product-form','category','No collection'],['category-form','id','New collection'],['category-form','parent','Top level'],['category-form','globalTaxonomy','No taxonomy link'],['variant-form','id','New variant'],['variant-form','productId',undefined],['listing-form','productId',undefined],['publish-product-form','productId',undefined],['branding-form','avatar','No avatar'],['branding-form','banner','No banner'],['rollback-form','release',undefined]])options(field(form,name),[],{empty});$('product-media').replaceChildren();appendText($('product-media'),'legend','Product photos (up to 12)');}
function reset(){epoch++;sdk=null;storeId=null;data=null;plan=null;dirty=false;for(const url of mediaURLs.values())URL.revokeObjectURL(url);mediaURLs.clear();for(const form of forms)form.reset();clearSelections();for(const id of ['preview','media-list','variant-list','global-list'])$(id).replaceChildren();$('review').close();$('store-result').textContent='No store selected.';$('identity-result').textContent='Resolve a merchant to create or resume its store.';$('stock-result').textContent='No canonical stock read yet.';$('network').textContent='Wallet disconnected; tenant data cleared.';message('Connect Wallet to resume.');controls();}
const scopeFor={'branding-form':'branding','upload-form':'media','rollback-form':'branding','category-form':'categories','product-form':'catalogue','variant-form':'catalogue','listing-form':'publish','stock-form':'catalogue','publish-product-form':'publish','publish-store-form':'publish','delegate-form':'delegate'};
function controls(){for(const form of forms)for(const button of form.querySelectorAll('button'))button.disabled=busy||!sdk||(!storeId&&!['identity-form','registration-form','store-form','open-form'].includes(form.id))||(storeId&&scopeFor[form.id]&&!data?.permissions?.includes(scopeFor[form.id]));$('connect').disabled=busy||!COMMERCE_CONFIG;$('switch').disabled=busy||!session;$('confirm-transaction').disabled=busy||!plan;$('disconnect').disabled=busy||!session;}
async function action(fn){if(busy)return;busy=true;const token=epoch;controls();try{if(!navigator.onLine)throw new Error('You are offline.');await fn(token);if(token!==epoch)throw new Error('Wallet session changed; result discarded.');}catch(e){error(e);}finally{busy=false;controls();}}
function current(token){if(token!==epoch)throw new Error('Wallet session changed; result discarded.');}
function options(select,items,{empty,label=x=>x.sku??x.slug??x.object_id,key=x=>x.product_id??x.category_id??x.object_id}={}){const selected=select.value;select.replaceChildren();if(empty!==undefined){const option=document.createElement('option');option.value='';option.textContent=empty;select.append(option);}for(const item of items){const option=document.createElement('option');option.value=key(item);option.textContent=label(item);select.append(option);}if([...select.options].some(o=>o.value===selected))select.value=selected;}
function clearTenant(){clearSelections();data=null;plan=null;dirty=false;for(const url of mediaURLs.values())URL.revokeObjectURL(url);mediaURLs.clear();for(const form of forms.filter(f=>!['identity-form','registration-form','store-form','open-form'].includes(f.id)))form.reset();for(const id of ['preview','media-list','variant-list'])$(id).replaceChildren();$('store-result').textContent='Loading authorized store…';$('stock-result').textContent='No canonical stock read yet.';}
async function load(token){
  const result=await sdk.merchantBuilder(storeId);current(token);data=result;
  data.branding??={theme_id:'default',public_description:'',version:0};
  $('store-result').textContent=`${data.store.slug} · ${data.store.status} · store version ${data.store.version} · ${storeId}`;
  field('branding-form','theme').value=data.branding.theme_id;field('branding-form','description').value=data.branding.public_description;
  field('publish-store-form','slug').value=data.store.slug;
  const global=await sdk.categories();current(token);$('global-list').replaceChildren();for(const c of global.items)appendText($('global-list'),'li',c.slug);
  options(field('category-form','globalTaxonomy'),global.items,{empty:'No taxonomy link'});
  for(const [form,name,empty] of [['category-form','id','New collection'],['category-form','parent','Top level'],['product-form','category','No collection']])options(field(form,name),data.categories,{empty});
  const media={items:data.media};
  for(const name of ['avatar','banner'])options(field('branding-form',name),media.items,{empty:'No '+name});
  field('branding-form','avatar').value=data.branding.avatar_object_id??'';field('branding-form','banner').value=data.branding.banner_object_id??'';
  $('product-media').replaceChildren();appendText($('product-media'),'legend','Product photos (up to 12)');$('media-list').replaceChildren();
  for(const m of media.items){const label=appendText($('product-media'),'label',m.object_id.slice(0,12));const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.name='media';checkbox.value=m.object_id;label.prepend(checkbox);
    if(!mediaURLs.has(m.object_id)){const preview=await sdk.merchantMedia(storeId,m.object_id);current(token);if(preview.contentType!=='image/png'||preview.dataBase64.length>7000000)throw new Error('Invalid private media response.');const bytes=Uint8Array.from(window.atob(preview.dataBase64),c=>c.charCodeAt(0));mediaURLs.set(m.object_id,URL.createObjectURL(new Blob([bytes],{type:'image/png'})));}
    const image=document.createElement('img');image.src=mediaURLs.get(m.object_id);image.alt='Private uploaded image '+m.object_id.slice(0,8);$('media-list').append(image);
  }
  for(const [form,name,empty] of [['product-form','id','New product'],['variant-form','productId',undefined],['listing-form','productId',undefined],['publish-product-form','productId',undefined]])options(field(form,name),data.products,{empty});
  options(field('variant-form','id'),data.variants,{empty:'New variant',key:x=>x.variant_id,label:x=>x.variant_sku});$('variant-list').replaceChildren();for(const v of data.variants)appendText($('variant-list'),'li',`${v.variant_sku}: ${v.option_json} · ${v.canonical_listing_id??'unbound draft'}`);
  options(field('rollback-form','release'),data.releases??[],{key:x=>String(x.version),label:x=>'Published design '+x.version});
  dirty=false;preview();message('Saved data refreshed. Protected actions always recheck canonical authorization.');
}
function selectedProduct(id){const product=data?.products.find(p=>p.product_id===id);if(!product)throw new Error('Save and select a product first.');return product;}
function preview(){if(!data)return;document.title='Preview: '+(data.store.slug??'Storefront')+' · 420Commerce';document.querySelector('meta[name=description]').content=field('branding-form','description').value.slice(0,160);const b=values($('branding-form'));renderPreview($('preview'),{slug:field('publish-store-form','slug').value,branding:{...data.branding,theme_id:b.theme,public_description:b.description,avatar_object_id:b.avatar,banner_object_id:b.banner},categories:data.categories,products:data.products,mediaURLs});const width=$('preview-width').value;$('preview').style.width=width==='fluid'?'100%':width+'px';}
function review(value,token){current(token);plan=value;dirty=false;$('review-terms').textContent=JSON.stringify(transactionTerms(value),null,2);$('review').showModal();}
function submit(id,fn){$(id).addEventListener('submit',e=>{e.preventDefault();action(async token=>{if(!sdk)throw new Error('Connect Wallet first.');await fn(values($(id)),token);});});}
$('connect').addEventListener('click',()=>{session?.dispose();session=null;action(async token=>{if(!COMMERCE_CONFIG||COMMERCE_CONFIG.origin!==location.origin)throw new Error('Approved same-origin configuration unavailable.');if(!window.ethereum)throw new Error('Open in 420Wallet or an EIP-1193 Wallet browser.');const start=epoch;session=new WalletSession(window.ethereum,COMMERCE_CONFIG,{onReset:reset});await session.connect();current(start);sdk=createCommerceSdk420({baseUrl:COMMERCE_CONFIG.apiUrl,origin:location.origin,chainId:COMMERCE_CONFIG.chainId,wallet:session.wallet(),host:session.host()});$('network').textContent=`Chain ${COMMERCE_CONFIG.chainId} · ${session.address} · code/Registry verified`;message('Wallet connected. Resolve your canonical Pay merchant.');current(token);});});
$('switch').addEventListener('click',()=>action(async()=>{await session?.switchChain();}));$('disconnect').addEventListener('click',()=>{session?.dispose();session=null;controls();});
submit('identity-form',async(v,t)=>{const result=await sdk.merchantIdentity(v.merchantId);current(t);$('identity-result').textContent=result.registered?'Canonical controller verified.':'Merchant is unregistered. Review a Pay registration transaction.';field('registration-form','merchantId').value=v.merchantId;field('store-form','merchantId').value=v.merchantId;if(result.store){clearTenant();storeId=result.store.store_id;await load(t);}});
submit('registration-form',async(v,t)=>review(await sdk.registrationPlan(v),t));
submit('store-form',async(v,t)=>{const result=await sdk.createStore(v.merchantId,v.slug);current(t);clearTenant();storeId=result.store_id;await load(t);});
submit('open-form',async(v,t)=>{clearTenant();storeId=v.storeId;await load(t);});
submit('branding-form',async(v,t)=>{await sdk.branding(storeId,{version:data.branding.version,theme:v.theme,description:v.description,...(v.avatar?{avatar:v.avatar}:{}),...(v.banner?{banner:v.banner}:{})});current(t);await load(t);});
submit('upload-form',async(v,t)=>{const file=v.media;if(file.size>5*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Select a PNG, JPEG or WebP up to 5 MB.');await sdk.upload(storeId,new Uint8Array(await file.arrayBuffer()),file.type);current(t);await load(t);});
submit('rollback-form',async(v,t)=>{const release=data.releases.find(r=>r.version===Number(v.release));if(!release)throw new Error('Select a published design.');const b=JSON.parse(release.branding);await sdk.branding(storeId,{version:data.branding.version,theme:b.theme_id,description:b.public_description,...(b.avatar_object_id?{avatar:b.avatar_object_id}:{}),...(b.banner_object_id?{banner:b.banner_object_id}:{})});current(t);await load(t);message('Previous branding restored to draft. Publish explicitly to release it.');});
submit('category-form',async(v,t)=>{const previous=data.categories.find(c=>c.category_id===v.id);await sdk.category(storeId,{...(v.id?{id:v.id,version:previous.version}:{}),slug:v.slug,order:Number(v.order),visibility:v.visibility,...(v.parent?{parent:v.parent}:{}),...(v.globalTaxonomy?{globalTaxonomy:v.globalTaxonomy}:{})});current(t);await load(t);});
submit('product-form',async(v,t)=>{const previous=data.products.find(p=>p.product_id===v.id),media=[...$('product-media').querySelectorAll('input:checked')].map(i=>i.value);await sdk.saveProduct(storeId,{...(v.id?{id:v.id,version:previous.version}:{}),sku:v.sku,description:v.description,media,publishState:'draft',...(v.category?{category:v.category}:{})});current(t);await load(t);});
submit('variant-form',async(v,t)=>{const previous=data.variants.find(x=>x.variant_id===v.id);await sdk.variant(storeId,v.productId,{...(v.id?{id:v.id,version:previous.version}:{}),sku:v.sku,options:JSON.parse(v.options),...(v.listingId?{listingId:v.listingId}:{})});current(t);await load(t);});
submit('listing-form',async(v,t)=>{const p=selectedProduct(v.productId);review(await sdk.listingPlan(storeId,p.product_id,listingChange(v,p),p.metadata_hash),t);});
submit('stock-form',async(v,t)=>{const result=await sdk.merchantListing(storeId,v.listingId);current(t);$('stock-result').textContent=JSON.stringify(result,null,2);message('Canonical stock read at finalized source; a buyer still requires a Market reservation.');});
submit('publish-product-form',async(v,t)=>{const p=selectedProduct(v.productId);await sdk.saveProduct(storeId,productChange(p,{listingId:v.listingId,revision:Number(v.revision),publishState:'published'}));current(t);await load(t);});
submit('publish-store-form',async(v,t)=>{await sdk.updateStore(storeId,{version:data.store.version,slug:v.slug,status:v.status,designVersion:data.branding.version,categoryVersions:data.categories.map(c=>({category_id:c.category_id,version:c.version})).sort((a,b)=>a.category_id.localeCompare(b.category_id))});current(t);await load(t);message(v.status==='published'?'Saved storefront design published.':'Storefront withdrawn.');});
submit('delegate-form',async(v,t)=>{await sdk.delegate(storeId,{wallet:v.wallet,expiresAt:Number(v.expiresAt),scopes:[...$('delegate-form').querySelectorAll('input[name=scope]:checked')].map(i=>i.value)});current(t);message('Controller-authorized editor scopes updated.');});
$('confirm-transaction').addEventListener('click',()=>action(async t=>{if(!plan||dirty)throw new Error('Review a fresh transaction plan.');const sending=plan;plan=null;$('review').close();const hash=await session.send(sending);current(t);message(`Transaction submitted: ${hash}. Not finalized or published. Resolve identity or explicitly verify listing binding after finality.`);}));
$('cancel-transaction').addEventListener('click',()=>{plan=null;$('review').close();controls();});$('review').addEventListener('cancel',()=>{plan=null;controls();});
$('preview-button').addEventListener('click',preview);$('preview-width').addEventListener('change',preview);
$('product-form').addEventListener('change',e=>{if(e.target.name!=='id')return;const p=data?.products.find(x=>x.product_id===e.target.value);field('product-form','sku').value=p?.sku??'';field('product-form','description').value=p?.description??'';field('product-form','category').value=p?.category_id??'';for(const i of $('product-media').querySelectorAll('input'))i.checked=!!p&&JSON.parse(p.media_manifest).includes(i.value);});
$('category-form').addEventListener('change',e=>{if(e.target.name!=='id')return;const c=data?.categories.find(x=>x.category_id===e.target.value);for(const [n,k]of [['slug','slug'],['parent','parent_id'],['globalTaxonomy','global_taxonomy_id'],['order','sort_order'],['visibility','visibility']])field('category-form',n).value=c?.[k]??(n==='order'?'0':n==='visibility'?'public':'');});
$('variant-form').addEventListener('change',e=>{if(e.target.name!=='id')return;const v=data?.variants.find(x=>x.variant_id===e.target.value);for(const [n,k]of [['sku','variant_sku'],['options','option_json'],['listingId','canonical_listing_id'],['productId','product_id']])field('variant-form',n).value=v?.[k]??'';});
for(const form of forms)form.addEventListener('input',()=>{dirty=true;plan=null;controls();});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});window.addEventListener('offline',()=>{$('offline').hidden=false;plan=null;controls();});window.addEventListener('online',()=>{$('offline').hidden=true;});
controls();
