import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const here=dirname(fileURLToPath(import.meta.url));const repoRoot=resolve(here,'../../..');const bin=resolve(repoRoot,'packages/420-cli/bin/420-qualify.mjs');
function run(args){return spawnSync(process.execPath,[bin,...args],{cwd:repoRoot,encoding:'utf8'});}
function freshEvidenceFile(){const dir=mkdtempSync(join(tmpdir(),'420-handoff-'));const source=JSON.parse(readFileSync(resolve(repoRoot,'developer-hub/qualification/evidence.example.json'),'utf8'));source.observedAt=new Date(Date.now()-60_000).toISOString();const path=join(dir,'evidence.json');writeFileSync(path,JSON.stringify(source));return {dir,path};}
test('qualification view exposes release-gate and handoff non-authority semantics',()=>{const result=run(['view']);assert.equal(result.status,0,result.stderr);const body=JSON.parse(result.stdout);assert.equal(body.qualification.canonicalAuthority,false);assert.equal(body.qualification.securityCertification,false);assert.ok(body.qualification.requiredChecks.includes('secret-material'));assert.equal(body.handoff.requiresExactCommitBinding,true);});
test('example qualification evidence passes for local network',()=>{const result=run(['check','developer-hub/qualification/evidence.example.json']);assert.equal(result.status,0,result.stderr);const body=JSON.parse(result.stdout);assert.equal(body.result,'PASS');assert.equal(body.qualifiedForDeveloperRelease,true);});
test('blocked qualification returns gate exit code 3',()=>{const dir=mkdtempSync(join(tmpdir(),'420-qualify-'));try{const source=JSON.parse(readFileSync(resolve(repoRoot,'developer-hub/qualification/evidence.example.json'),'utf8'));source.checks=source.checks.filter(check=>check.id!=='tests-qualified');const path=join(dir,'blocked.json');writeFileSync(path,JSON.stringify(source));const result=run(['check',path]);assert.equal(result.status,3,result.stderr);assert.equal(JSON.parse(result.stdout).result,'BLOCKED');}finally{rmSync(dir,{recursive:true,force:true});}});
test('handoff validates exact candidate SHA and successful workflow provenance',()=>{const sha='e1e6f4547e139357c978f4d7906c24642e8642fd';const {dir,path}=freshEvidenceFile();try{const result=run(['handoff',path,sha]);assert.equal(result.status,0,result.stderr);const body=JSON.parse(result.stdout);assert.equal(body.commitSha,sha);assert.equal(body.releaseEvidenceReady,true);assert.equal(body.canonicalAuthority,false);}finally{rmSync(dir,{recursive:true,force:true});}});
test('handoff rejects evidence from another commit',()=>{const {dir,path}=freshEvidenceFile();try{const result=run(['handoff',path,'2222222222222222222222222222222222222222']);assert.equal(result.status,1);assert.match(result.stderr,/does not match release candidate/);}finally{rmSync(dir,{recursive:true,force:true});}});
