import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,writeFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {Interface} from 'ethers';
import sharp from 'sharp';
import {setup,seller,attacker,b32,address} from '../../test/fixtures.mjs';
import {commerceServer} from '../../src/http.mjs';
import {RequestAuth} from '../../src/security.mjs';
import {ABIS,fixedPrice} from '../../src/authority.mjs';
import {stateABIs} from '../core/wallet.js';
import {fixture} from './fixture.mjs';
const f=setup(),wf=fixture(),temp=mkdtempSync(join(tmpdir(),'com4-browser-'));let api,browser;const errors=[],checks=[];let rejectTx=false,unmined=null,account=seller.address.toLowerCase(),chain='0x1a4';
f.service.reconcileTaxonomy([{id:'a'.repeat(64),slug:'app-goods',order:0}]);
f.source.merchant=async id=>({controller:id===b32(1)?seller.address.toLowerCase():address(0),active:id===b32(1)});
const server=createServer((req,res)=>{if(req.url.startsWith('/v1/'))return api.listeners('request')[0](req,res);const path=req.url==='/'?'index.html':req.url.slice(1);if(!['index.html','app.js','style.css','public.html','public.js','public.css','operations.html','operations.js'].includes(path)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html','Content-Security-Policy':"default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' blob:; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'"});res.end(readFileSync(join(temp,'site',path)));});
try{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
  api=commerceServer(f.service,new RequestAuth(f.db,{origin,chainId:'420',now:f.now}),{origin,now:f.now,rateLimit:10000});
  const config={...wf.config,origin,apiUrl:origin+'/'};
  const manifest=join(temp,'manifest.json');writeFileSync(manifest,JSON.stringify(config));
  execFileSync(process.execPath,['scripts/build.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,COMMERCE_WEB_TEST_OUTPUT:join(temp,'site'),COMMERCE_WEB_MANIFEST:manifest,COMMERCE_WEB_MANIFEST_SHA256:createHash('sha256').update(readFileSync(manifest)).digest('hex')},stdio:'inherit'});
  browser=await chromium.launch({headless:true,...process.env.COMMERCE_CHROMIUM_PATH?{executablePath:process.env.COMMERCE_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']}: {}});const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());
  await page.exposeFunction('walletRequest',async call=>{
    if(['eth_accounts','eth_requestAccounts'].includes(call.method))return [account];
    if(call.method==='eth_chainId')return chain;
    if(call.method==='eth_getBlockByNumber')return {hash:b32(100),timestamp:'0x'+Math.floor(f.now()/1000).toString(16)};
    if(call.method==='personal_sign')return (account===attacker.address.toLowerCase()?attacker:seller).signMessage(Buffer.from(call.params[0].slice(2),'hex'));
    if(call.method==='eth_sendTransaction'){if(rejectTx)throw new Error('Wallet rejected transaction');const tx=call.params[0],parsed=new Interface(tx.to===config.contracts.MerchantRegistry420.address?ABIS.MerchantRegistry420:ABIS.ListingRegistry420).parseTransaction({data:tx.data});unmined=parsed;return b32(900);}
    if(call.method==='eth_call'&&call.params[0].to===config.contracts.ListingRegistry420.address){const state=new Interface(stateABIs.ListingRegistry420);if(call.params[0].data.startsWith(state.getFunction('getListing').selector)){const parsed=state.parseTransaction({data:call.params[0].data}),l=f.listings.get(parsed.args[0]);return state.encodeFunctionResult('getListing',[[l?.seller??address(0),b32(3),b32(4),b32(5),l?.metadataHash??b32(0),b32(5),fixedPrice,b32(6),address(100),'100',l?.quantity??'0',0,l?.revision??0,l?.active??false]]);}}
    return wf.provider.request(call);
  });
  await page.addInitScript(({now})=>{Date.now=()=>now;const listeners={};window.ethereum={request:call=>window.walletRequest(call),on:(e,f)=>listeners[e]=f,removeListener:e=>delete listeners[e]};window.emitWallet=e=>listeners[e]?.();},{now:f.now()});
  const fill=async(form,values)=>{for(const [key,value] of Object.entries(values)){const node=page.locator(`#${form} [name="${key}"]`);if(await node.evaluate(n=>n.tagName==='SELECT'))await node.selectOption(String(value));else await node.fill(String(value));}};
  const submit=async form=>{await page.locator('#'+form+' button').click();await page.waitForFunction(id=>!document.querySelector('#'+id+' button').disabled,form);};
  const pass=name=>{checks.push(name);console.log('PASS '+name);};
  await page.goto(origin);await page.locator('#connect').click();await page.waitForFunction(()=>document.querySelector('#network').textContent.includes('code/Registry verified'));
  await fill('identity-form',{merchantId:b32(1)});await submit('identity-form');assert.match(await page.locator('#identity-result').textContent(),/controller verified/);pass('canonical Wallet/controller onboarding with real signed HTTP');
  await fill('registration-form',{merchantId:b32(9),profileId:b32(8),metadataHash:b32(7),payout:seller.address});await page.locator('#registration-form button').click();await page.locator('#review').waitFor({state:'visible'});assert.match(await page.locator('#review-terms').textContent(),/MerchantRegistry420/);assert.match(await page.locator('#review-terms').textContent(),new RegExp(seller.address.toLowerCase()));await page.locator('#cancel-transaction').click();assert.equal(unmined,null);pass('Pay registration reviews exact controller/payout and cancellation leaves identity untouched');
  await fill('store-form',{merchantId:b32(1),slug:'browser-store'});await submit('store-form');assert.equal(await page.locator('#error').isVisible(),false);assert.match(await page.locator('#store-result').textContent(),/browser-store/);
  const png=await sharp({create:{width:8,height:8,channels:3,background:'#123456'}}).png().toBuffer();await page.locator('#upload-form input').setInputFiles({name:'avatar.png',mimeType:'image/png',buffer:png});await submit('upload-form');
  const media=f.db.get('SELECT object_id FROM media').object_id;
  await fill('branding-form',{theme:'light',description:'Paper merchant',avatar:media,banner:media});await submit('branding-form');assert.equal((await fetch(origin+'/v1/media/'+media)).status,404);pass('real sanitized avatar/banner upload stays private');
  await fill('category-form',{slug:'merchant-goods',order:0,globalTaxonomy:'a'.repeat(64)});await submit('category-form');assert.equal(f.db.all('SELECT * FROM store_categories WHERE store_id IS NOT NULL').length,1);
  await fill('product-form',{sku:'BROWSER',description:'Accessible product draft'});await page.locator('#product-media input').check();await submit('product-form');assert.equal((await fetch(origin+'/v1/search').then(r=>r.json())).data.items.length,0);pass('private catalogue, merchant collection and product photo');
  const p=f.db.get('SELECT * FROM products');await fill('variant-form',{productId:p.product_id,sku:'BROWSER-SMALL',options:'{"size":"small"}'});await submit('variant-form');assert.equal(f.db.all('SELECT * FROM product_variants').length,1);pass('variant editing persists option data independently');
  const terms={productId:p.product_id,listingId:b32(2),sellerProfileId:b32(3),assetRef:b32(4),policyId:b32(5),adapterId:b32(6),quoteAsset:address(100),unitPrice:'100',quantity:'10',expiresAt:0};
  await fill('listing-form',terms);await page.locator('#listing-form button').click();await page.locator('#review').waitFor({state:'visible'});assert.match(await page.locator('#review-terms').textContent(),/ListingRegistry420/);assert.match(await page.locator('#review-terms').textContent(),/createListing/);assert.match(await page.locator('#review-terms').textContent(),/unitPriceBaseUnits/);assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations,[]);await page.locator('#cancel-transaction').click();assert.equal(unmined,null);pass('decoded canonical seller review and cancel never send');
  await page.locator('#listing-form button').click();await page.locator('#review').waitFor({state:'visible'});rejectTx=true;await page.locator('#confirm-transaction').click();await page.locator('#error').waitFor({state:'visible'});assert.equal(f.db.get('SELECT publish_state FROM products').publish_state,'draft');rejectTx=false;pass('Wallet rejection preserves private product draft');
  await page.locator('#listing-form button').click();await page.locator('#review').waitFor({state:'visible'});await page.locator('#confirm-transaction').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Not finalized or published'));assert.ok(unmined);
  await fill('publish-product-form',{productId:p.product_id,listingId:b32(2),revision:1});await submit('publish-product-form');assert.equal(f.db.get('SELECT publish_state FROM products').publish_state,'draft');pass('broadcast alone cannot publish; finalized listing binding required');
  f.listings.set(b32(2),{seller:seller.address.toLowerCase(),metadataHash:p.metadata_hash,revision:'1',active:true,quantity:'10',available:'7',unitPrice:'100',quoteAsset:address(100),expiresAt:'0',policyActive:true,adapterActive:true,reporterActive:true,saleMechanism:fixedPrice,policyId:b32(5),settlementAdapterId:b32(6),inventory:{originalOffered:'10',reserved:'1',sold:'2',released:'0',initialized:true}});
  await submit('publish-product-form');assert.equal(f.db.get('SELECT publish_state FROM products').publish_state,'published');
  f.db.run('INSERT INTO catalogue_projection VALUES(?,?,?,?,?)',b32(2),JSON.stringify({...f.listings.get(b32(2)),metadataHash:p.metadata_hash,revision:1}),b32(100),100,1);

  await fill('stock-form',{listingId:b32(2)});await submit('stock-form');assert.match(await page.locator('#stock-result').textContent(),/"available": "7"/);assert.match(await page.locator('#stock-result').textContent(),/"finalized": true/);pass('finalized product publication and canonical reserved/sold stock display');
  await fill('listing-form',{method:'reviseListing',revision:1,quantity:'11'});await submit('listing-form');assert.equal(await page.locator('#error').textContent(),'quantity_immutable');await fill('listing-form',{quantity:'10',unitPrice:'120'});await page.locator('#listing-form button').click();await page.locator('#review').waitFor({state:'visible'});assert.match(await page.locator('#review-terms').textContent(),/reviseListing/);await page.locator('#cancel-transaction').click();pass('revision review preserves immutable quantity and rejects attempted restock');
  await fill('publish-store-form',{slug:'browser-store',status:'published'});await submit('publish-store-form');assert.equal((await fetch(origin+'/v1/storefronts/browser-store').then(r=>r.json())).data.public_description,'Paper merchant');assert.equal((await fetch(origin+'/v1/media/'+media)).status,200);
  await fill('branding-form',{theme:'dark',description:'Night draft'});await submit('branding-form');assert.equal((await fetch(origin+'/v1/storefronts/browser-store').then(r=>r.json())).data.public_description,'Paper merchant');await submit('publish-store-form');assert.equal((await fetch(origin+'/v1/storefronts/browser-store').then(r=>r.json())).data.public_description,'Night draft');pass('versioned preview/publish separates public and draft branding');
  // COM-5 real browser smoke against the actual signed-service HTTP + SQLite fixture.
  const publicSearch=await fetch(origin+'/v1/search').then(async response=>({status:response.status,body:await response.json()}));
  assert.equal(publicSearch.status,200,'published public catalogue API must be readable');
  assert.equal(publicSearch.body.data.items.length,1,'published product must exist in the real service before browser navigation');
  const shopper=await context.newPage();shopper.on('pageerror',e=>errors.push(e.message));await shopper.goto(origin+'/public.html');
  await shopper.waitForFunction(()=>document.querySelector('#products article')||!document.querySelector('#error').hidden,{timeout:10000});
  assert.equal(await shopper.locator('#error').isVisible(),false,'shopper startup: '+await shopper.locator('#error').textContent());
  await shopper.locator('#products article').first().waitFor();
  assert.match(await shopper.locator('#products').textContent(),/BROWSER/);
  assert.match(await shopper.locator('#stores').textContent(),/browser-store/);
  await shopper.locator('#filters [name=query]').fill('BROWSER');
  await shopper.locator('#filters button').click();
  await shopper.locator('#products article').first().waitFor();
  assert.equal(await shopper.locator('#products article').count(),1);
  assert.equal(await shopper.locator('#products article button').last().isEnabled(),true);
  await shopper.locator('#products article button').last().click();
  assert.match(await shopper.locator('#cart').textContent(),/BROWSER/);
  await shopper.locator('#clear').click();assert.equal(await shopper.locator('#cart li').count(),0);
  assert.deepEqual((await new AxeBuilder({page:shopper}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations,[]);
  await shopper.setViewportSize({width:320,height:740});
  assert.equal(await shopper.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  assert.deepEqual((await new AxeBuilder({page:shopper}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations,[]);
  await shopper.close();pass('COM-5 anonymous marketplace search, cart, axe and 320px browser acceptance');
  const operations=await context.newPage();operations.on('pageerror',e=>errors.push(e.message));
  await operations.exposeFunction('walletRequest',async call=>page.evaluate(async c=>window.walletRequest(c),call).catch(async()=>{throw Error('wallet fixture unavailable')}));
  await operations.addInitScript(({now})=>{Date.now=()=>now;const listeners={};window.ethereum={request:call=>window.walletRequest(call),on:(e,f)=>listeners[e]=f,removeListener:e=>delete listeners[e]};},{now:f.now()});
  await operations.goto(origin+'/operations.html');
  assert.match(await operations.locator('h1').textContent(),/Merchant operations/);
  await operations.locator('#connect').click();
  await operations.waitForFunction(()=>document.querySelector('#status').textContent.includes('Verified Wallet connected')||!document.querySelector('#error').hidden);
  assert.equal(await operations.locator('#error').isVisible(),false,'operations connect: '+await operations.locator('#error').textContent());
  await operations.locator('#open input[name=storeId]').fill(f.db.get('SELECT store_id FROM stores').store_id);
  await operations.locator('#open button').click();
  await operations.waitForFunction(()=>document.querySelector('#summary').textContent.includes('order attempts')||!document.querySelector('#error').hidden);
  assert.equal(await operations.locator('#error').isVisible(),false,'merchant operations: '+await operations.locator('#error').textContent());
  assert.match(await operations.locator('#summary').textContent(),/0 order attempts/);
  assert.match(await operations.locator('#integrations').textContent(),/NOT_CONFIGURED/);
  assert.deepEqual((await new AxeBuilder({page:operations}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations,[]);
  await operations.setViewportSize({width:320,height:740});
  assert.equal(await operations.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  await operations.close();pass('COM-6 signed merchant dashboard, no invented receipts, integration gates, mobile accessibility');

  await fill('rollback-form',{release:'2'});await submit('rollback-form');assert.equal(f.db.get('SELECT public_description FROM store_branding').public_description,'Paper merchant');assert.equal((await fetch(origin+'/v1/storefronts/browser-store').then(r=>r.json())).data.public_description,'Night draft');pass('published branding rollback restores a private draft');
  // Text must fail server validation and never become HTML in preview.
  await fill('branding-form',{description:'<script>window.compromised=true</script>'});await page.locator('#preview-button').click();assert.equal(await page.locator('#preview script').count(),0);await submit('branding-form');assert.equal(await page.locator('#error').textContent(),'invalid_text');assert.equal(await page.evaluate(()=>document.activeElement.id),'error');pass('malicious content is rendered as text and rejected by API');
  await fill('branding-form',{description:'Paper merchant'});await page.locator('#preview-button').click();await page.locator('#preview-width').selectOption('320');
  const axe=new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']);assert.deepEqual((await axe.analyze()).violations,[]);for(const theme of ['default','light','dark']){await fill('branding-form',{theme});await page.locator('#preview-button').click();assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations,[]);}pass('desktop WCAG automated accessibility gate across all templates and transaction review');
  await page.setViewportSize({width:320,height:740});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);assert.deepEqual((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations,[]);await page.keyboard.press('Control+Home');await page.keyboard.press('Tab');await page.locator('.skip').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>location.hash),'#main');await page.screenshot({path:process.env.COMMERCE_SCREENSHOT_PATH??join(temp,'mobile.png'),fullPage:true});pass('320px responsive and keyboard skip-link accessibility gate');
  await page.setViewportSize({width:1280,height:900});account=attacker.address.toLowerCase();await page.evaluate(()=>window.emitWallet('accountsChanged'));assert.equal(await page.locator('#preview').textContent(),'');assert.equal(await page.locator('#product-form select[name=id] option').count(),1);assert.equal(await page.locator('#store-result').textContent(),'No store selected.');assert.equal(await page.locator('#branding-form button').isDisabled(),true);pass('account change clears private tenant data and pending authority');
  await f.service.delegate(seller.address,f.db.get('SELECT store_id FROM stores').store_id,{wallet:attacker.address,scopes:['branding'],expiresAt:f.now()+10000});
  account=attacker.address.toLowerCase();await page.locator('#connect').click();await page.waitForFunction(()=>document.querySelector('#network').textContent.includes('code/Registry verified'));
  await fill('open-form',{storeId:f.db.get('SELECT store_id FROM stores').store_id});await submit('open-form');assert.equal(await page.locator('#branding-form button').isDisabled(),false);assert.equal(await page.locator('#listing-form button').isDisabled(),true);assert.equal(await page.locator('#product-form select[name=id] option').count(),1);pass('scoped editor sees only branding and cannot invoke seller publication');
  account=seller.address.toLowerCase();await page.evaluate(()=>window.emitWallet('accountsChanged'));
  account=seller.address.toLowerCase();chain='0x1';await page.locator('#connect').click();await page.locator('#error').waitFor({state:'visible'});assert.match(await page.locator('#error').textContent(),/Wrong network/);assert.equal(await page.locator('#store-form button').isDisabled(),true);pass('wrong network blocks onboarding and signing');
  assert.deepEqual(errors,[]);console.log(`COM-4 browser integration: ${checks.length} PASS, 0 failed, 0 skipped; mock Wallet/RPC, real HTTP/SQLite/SDK, no live-chain claim`);
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));f.close();rmSync(temp,{recursive:true,force:true});}
