import {Interface,keccak256,toUtf8Bytes} from 'ethers';
import {WalletSession,stateABIs} from '../core/wallet.js';
const b32=n=>'0x'+n.toString(16).padStart(64,'0'),address=n=>'0x'+n.toString(16).padStart(40,'0');
export function fixture(){
  const version=new Interface(['function protocolVersion() view returns(uint32)']),versionResult=version.encodeFunctionResult('protocolVersion',[1]);
  const config={schema:'420-commerce-web-v1',environment:'local',origin:'http://127.0.0.1:4200',apiUrl:'http://127.0.0.1:4200/',chainId:'420',registry:{address:address(1),codeHash:keccak256('0x6000')},contracts:Object.fromEntries(['MerchantRegistry420','ListingRegistry420','InventoryReservation420','MarketPolicyRegistry420','OrderRegistry420','PaymentRegistry420','InvoiceRegistry420','MarketPaySettlementAdapter420'].map((n,i)=>[n,{address:address(i+20),verified:true,version:'1',versionResult,codeHash:keccak256('0x6000'),...['MerchantRegistry420','PaymentRegistry420','InvoiceRegistry420'].includes(n)?{componentId:keccak256(toUtf8Bytes('420/APP/420PAY/'+n.replace('Registry420','').toUpperCase()+'_REGISTRY')),registryVersion:[1,0,0]}:{}}]))};
  const calls=[],listeners={},now=Date.now();let wrong='',clock=now;
  const registry=new Interface(['function component(bytes32) view returns(tuple(bytes32 componentId,address implementation,bytes32 runtimeCodeHash,tuple(uint16 major,uint16 minor,uint16 patch) version,uint8 lifecycle))','function isActive(bytes32) view returns(bool)']);
  const provider={on:(e,fn)=>listeners[e]=fn,removeListener:e=>delete listeners[e],request:async({method,params})=>{calls.push({method,params});if(method==='eth_accounts'||method==='eth_requestAccounts')return [wrong==='account'?address(99):address(100)];if(method==='eth_chainId')return wrong==='chain'?'0x1':'0x1a4';if(method==='eth_getBlockByNumber')return {hash:b32(1),timestamp:'0x'+Math.floor((now-(wrong==='stale'?121000:0))/1000).toString(16)};if(method==='eth_getCode')return wrong==='code'?'0x6001':'0x6000';if(method==='eth_call'){if(params[0].data===version.encodeFunctionData('protocolVersion'))return wrong==='version'?version.encodeFunctionResult('protocolVersion',[2]):versionResult;if(params[0].to===config.registry.address){const parsed=registry.parseTransaction({data:params[0].data}),binding=Object.values(config.contracts).find(b=>b.componentId===parsed.args[0]);return registry.encodeFunctionResult(parsed.name,parsed.name==='isActive'?[wrong!=='registry']:[[binding.componentId,binding.address,binding.codeHash,[1,0,0],2]]);}const state=new Interface(stateABIs.MerchantRegistry420);if(params[0].data.startsWith(state.getFunction('merchants').selector))return state.encodeFunctionResult('merchants',[wrong==='exists'?address(999):address(0),b32(0),b32(0),0,false,0]);if(wrong==='simulate')throw new Error('simulation failed');return '0x';}if(method==='eth_sendTransaction')return b32(900);if(method==='personal_sign')return '0x1234';if(method==='wallet_switchEthereumChain')return null;throw new Error(method);}};
  return {config,provider,calls,listeners,now,session:new WalletSession(provider,config,{now:()=>clock}),setWrong:v=>wrong=v,advance:n=>clock+=n};
}
