import test from 'node:test';
import assert from 'node:assert/strict';
import {Interface} from 'ethers';
import {validateConfig,writeABIs} from '../core/wallet.js';
import {listingChange,productChange} from '../core/builder.js';
import {fixture} from './fixture.mjs';
const b32=n=>'0x'+n.toString(16).padStart(64,'0'),address=n=>'0x'+n.toString(16).padStart(40,'0');
function plan(f){const args=[b32(1),b32(2),b32(3),address(100)],iface=new Interface(writeABIs.MerchantRegistry420);return {controller:address(100),expiresAt:f.now+10000,intent:{chainId:'420',target:f.config.contracts.MerchantRegistry420.address,contract:'MerchantRegistry420',method:'register',args,data:iface.encodeFunctionData('register',args),requiresWalletAuthorization:true,canonicalAuthority:false}};}
test('Wallet pins finalized code, Registry and versions; explicit review sends only exact canonical zero-value transaction',async()=>{const f=fixture();await f.session.connect();assert.equal(f.calls.some(c=>c.method==='personal_sign'||c.method==='eth_sendTransaction'),false);assert.equal(await f.session.send(plan(f)),b32(900));const tx=f.calls.find(c=>c.method==='eth_sendTransaction').params[0];assert.equal(tx.to,f.config.contracts.MerchantRegistry420.address);assert.equal(tx.value,'0x0');for(const c of f.calls.filter(c=>['eth_call','eth_getCode'].includes(c.method)))assert.equal(c.params[1].requireCanonical,true);});
for(const reason of ['chain','account','code','version','registry','stale','simulate','exists'])test('Wallet blocks transaction on '+reason,async()=>{const f=fixture();await f.session.connect();f.setWrong(reason);await assert.rejects(()=>f.session.send(plan(f)));assert.equal(f.calls.some(c=>c.method==='eth_sendTransaction'),false);});
for(const key of ['target','data','chainId','contract','requiresWalletAuthorization'])test('Wallet refuses altered transaction '+key,async()=>{const f=fixture();await f.session.connect();const p=plan(f);p.intent[key]=key==='requiresWalletAuthorization'?false:key==='target'?address(999):'tampered';await assert.rejects(()=>f.session.send(p));assert.equal(f.calls.some(c=>c.method==='eth_sendTransaction'),false);});
test('expired plan, network reset, disposed listeners and double submit cannot reuse authority',async()=>{const f=fixture();await f.session.connect();f.advance(10001);await assert.rejects(()=>f.session.send(plan(f)));f.listeners.accountsChanged();assert.equal(f.session.address,null);await assert.rejects(()=>f.session.send(plan(f)));f.session.dispose();assert.equal(Object.keys(f.listeners).length,0);});
test('Wallet revocation during signature rejects result, and never creates a transaction',async()=>{const f=fixture();await f.session.connect();const original=f.provider.request;f.provider.request=async call=>{if(call.method==='personal_sign'){f.listeners.chainChanged();return '0x1234';}return original(call);};await assert.rejects(()=>f.session.wallet().signMessage('specific action'));assert.equal(f.calls.some(c=>c.method==='eth_sendTransaction'),false);});
test('unapproved/unknown/incorrect Pay identity configurations are rejected',()=>{assert.throws(()=>validateConfig(null));const f=fixture();f.config.contracts.MerchantRegistry420.componentId=b32(999);assert.throws(()=>validateConfig(f.config));});
test('UI binding pins product version/metadata and revise never invents mutable item/quantity controls',()=>{const p={product_id:'a'.repeat(64),version:3,sku:'A',description:'description',media_manifest:'[]',category_id:null};assert.deepEqual(productChange(p,{listingId:b32(2),revision:4,publishState:'published'}).revision,4);const changed=listingChange({method:'reviseListing',productId:p.product_id,quantity:'10',expiresAt:'0',revision:'4',itemClass:'PHYSICAL_GOOD'},p);assert.equal(changed.version,3);assert.equal(changed.quantity,'10');assert.equal(changed.itemClass,undefined);});
test('concurrent transaction request cannot prompt Wallet twice',async()=>{const f=fixture();await f.session.connect();const original=f.provider.request;let release;const waiting=new Promise(resolve=>release=resolve);f.provider.request=async call=>{if(call.method==='eth_sendTransaction'){await waiting;return b32(900);}return original(call);};const first=f.session.send(plan(f));await assert.rejects(()=>f.session.send(plan(f)),/already awaiting/);release();assert.equal(await first,b32(900));});
