import {card,emptyState,escapeHtml,button} from './design-system.js';
import {normalizeSearchPage,canonicalLink,normalizeSubject,normalizeReview,normalizeCorrection,normalizeVerification,normalizeRecommendations} from './discovery.js';
function resultCard(r){const href=canonicalLink({...r,accessible:true,active:true});return `<a class="discovery-result" href="${escapeHtml(href)}"><span class="eyebrow">${escapeHtml(r.type)}</span><strong>${escapeHtml(r.title||r.id)}</strong><small>${escapeHtml(r.id)}</small></a>`;}
export function renderSearch({projection=null}={}){
 if(!projection)return card({title:'Discover',body:emptyState({title:'Search unavailable',message:'A qualified search projection must be supplied. No local results or rankings are invented.'})});
 const page=normalizeSearchPage(projection);
 return card({eyebrow:'Qualified indexed results',title:'Search',body:`<form class="discover-search" data-search-form><label for="discover-query">Find people, posts, communities and discovery subjects</label><input id="discover-query" name="q" value="${escapeHtml(page.query)}" maxlength="200" type="search" autocomplete="off" /><button type="submit">Search</button></form><div class="discovery-grid">${page.items.map(resultCard).join('')||emptyState({title:'No results',message:'No accessible canonical results matched this query.'})}</div>${page.hasMore?button({label:'Load more',action:'discover-more',variant:'secondary'}):''}<p class="detail">Results are indexed projections; revalidate canonical access before taking action. Indexed block: ${escapeHtml(page.indexedBlock??'unavailable')}.</p>`});
}
export function renderSubjectDetail({projection=null,walletView=null}={}){
 if(!projection?.subject)return card({title:'Discovery subject',body:emptyState({title:'Subject unavailable',message:'A qualified canonical subject projection is required.'})});
 const subject=normalizeSubject(projection.subject);
 const reviews=(projection.reviews??[]).map(normalizeReview).filter(r=>r.active&&r.subjectId===subject.subjectId);
 const corrections=(projection.corrections??[]).map(normalizeCorrection).filter(r=>r.subjectId===subject.subjectId);
 const verifications=(projection.verifications??[]).map(normalizeVerification).filter(r=>r.subjectId===subject.subjectId);
 const write=walletView?.connected===true&&walletView?.canWrite===true&&projection.currentEligibility===true;
 const reviewAction=button({label:'Review via 420Wallet',action:'discovery-review',disabled:!write});
 const correctionAction=button({label:'Submit correction via 420Wallet',action:'discovery-correction',disabled:!write});
 return card({eyebrow:'Canonical discovery subject',title:subject.subjectId,body:`<dl class="mini-grid"><div><dt>Type</dt><dd>${escapeHtml(subject.subjectType)}</dd></div><div><dt>Status</dt><dd>${escapeHtml(subject.status)}</dd></div><div><dt>Reference</dt><dd>${escapeHtml(subject.canonicalRef)}</dd></div></dl><section><h3>Reviews</h3>${reviews.length?reviews.map(r=>`<article class="discovery-record">${escapeHtml(r.author)} · ${r.ratingBps}/10000 · version ${r.version}<p>Content commitment: ${escapeHtml(r.contentHash)}</p></article>`).join(''):emptyState({title:'No active reviews'})}</section><section><h3>Corrections</h3>${corrections.length?corrections.map(r=>`<p class="discovery-record">Field ${escapeHtml(r.fieldId)} · proposed commitment ${escapeHtml(r.proposedValueHash)}</p>`).join(''):emptyState({title:'No corrections'})}</section><section><h3>Verification attestations</h3>${verifications.length?verifications.map(v=>`<p class="discovery-record">${escapeHtml(v.verifier)} · ${v.supportsProposition?'Supports':'Does not support'} · version ${v.subjectVersion}</p>`).join(''):emptyState({title:'No attestations'})}</section><div class="actions">${reviewAction}${correctionAction}</div><p class="detail">Buttons represent Wallet intents only; canonical refresh is required after approval. Raw review content is not inferred from its hash.</p>`});
}
export function renderRecommendations({items=[]}={}){const results=normalizeRecommendations(items);return card({eyebrow:'Non-authoritative suggestions',title:'You may also discover',body:results.length?`<div class="discovery-grid">${results.map(i=>resultCard(i.result)).join('')}</div><p class="detail">Recommendation position is not social, moderation or reward authority.</p>`:emptyState({title:'No suggestions available'})});}
export function renderDiscoveryRoute({projection=null,walletView=null}={}){if(projection?.subject)return renderSubjectDetail({projection,walletView});return `<div class="discovery-surface">${renderSearch({projection:projection?.search??null})}${projection?.recommendations?renderRecommendations({items:projection.recommendations}):''}</div>`;}
