// BG-19.10: presentation-only projections; backend and shared rewards contracts retain authority.
const ID=/^0x[0-9a-f]{64}$/i, ADDRESS=/^0x[0-9a-f]{40}$/i;
const NOTIFICATION_STATES=new Set(['FINALIZED','RETRACTED','SUPERSEDED','DEGRADED']);
const REWARD_STATES=new Set(['SUBMITTED','VERIFIED','ACCRUED','CLAIMABLE','CLAIM_PENDING','PAID','REJECTED','REVERTED','DEFERRED']);
const CASE_STATES=new Set(['OPEN','UNDER_REVIEW','ACTIONED','CLOSED','APPEALED','RESOLVED']);
const FORBIDDEN=/(plaintext|ciphertext|privatekey|secret|sessionkey|signedurl|payloadbytes|messagetext|messagebody|evidencebody)/i;
function field(value,name,re){if(typeof value!=='string'||!re.test(value))throw new Error(`invalid ${name}`);return value.toLowerCase();}
function number(value,name){if(!Number.isSafeInteger(value)||value<0)throw new Error(`invalid ${name}`);return value;}
function state(value,allowed,name){const normalized=String(value??'').toUpperCase();if(!allowed.has(normalized))throw new Error(`invalid ${name}`);return normalized;}
function privacy(value){if(Array.isArray(value)){value.forEach(privacy);return;}if(value&&typeof value==='object')for(const [key,item] of Object.entries(value)){if(FORBIDDEN.test(key))throw new Error('private data in public projection');privacy(item);}}
function safeRoute(route){if(typeof route!=='string'||!/^\/(?:profile|friends|messages|notifications|discover|groups|pages|events|games|rewards)(?:\/[a-z0-9-]+)?(?:\?(?:session|conversation|subject)=0x[0-9a-f]{64})?$/i.test(route))return null;return route;}
export function normalizeNotification(item,viewer){privacy(item);const recipient=field(item.recipient,'recipient',ADDRESS),account=field(viewer,'viewer',ADDRESS);if(recipient!==account)throw new Error('notification recipient mismatch');return Object.freeze({id:field(item.id,'notification id',ID),recipient,state:state(item.state,NOTIFICATION_STATES,'notification state'),kind:String(item.kind??'Activity').slice(0,80),createdAt:number(item.createdAt,'notification timestamp'),unread:item.unread===true&&item.state==='FINALIZED',route:item.state==='FINALIZED'?safeRoute(item.route):null,authoritative:false});}
export function normalizeNotifications({viewer,items=[],cursor=null,hasMore=false}={}){if(!Array.isArray(items)||items.length>100)throw new Error('invalid notification page');const list=items.map(x=>normalizeNotification(x,viewer)).sort((a,b)=>b.createdAt-a.createdAt||a.id.localeCompare(b.id));return Object.freeze({items:Object.freeze(list),unreadCount:list.filter(x=>x.unread).length,cursor:typeof cursor==='string'?cursor:null,hasMore:hasMore===true,authoritative:false});}
export function normalizeReward(item,viewer){privacy(item);const account=field(viewer,'viewer',ADDRESS),beneficiary=field(item.beneficiary,'beneficiary',ADDRESS);if(account!==beneficiary)throw new Error('reward beneficiary mismatch');const status=state(item.status,REWARD_STATES,'reward status');const amount=String(item.amount??'0');if(!/^\d{1,78}$/.test(amount))throw new Error('invalid reward amount');return Object.freeze({id:field(item.id,'reward id',ID),beneficiary,status,amount,contributionType:String(item.contributionType??'').slice(0,40),campaignId:item.campaignId?field(item.campaignId,'campaign id',ID):null,claimable:status==='CLAIMABLE'&&item.claimAuthorized===true,paid:status==='PAID',authoritative:false});}
export function normalizeRewards({viewer,items=[]}={}){if(!Array.isArray(items)||items.length>100)throw new Error('invalid reward page');return Object.freeze({items:Object.freeze(items.map(x=>normalizeReward(x,viewer))),authoritative:false});}
export function normalizeSafetyCase(item,viewer){privacy(item);const account=field(viewer,'viewer',ADDRESS),subject=field(item.affectedAccount,'affected account',ADDRESS);if(subject!==account)throw new Error('case access denied');const status=state(item.status,CASE_STATES,'case status');return Object.freeze({id:field(item.id,'case id',ID),status,affectedAccount:subject,appealAllowed:item.appealAllowed===true&&status==='ACTIONED',decisionFinal:item.decisionFinal===true,authoritative:false});}
export function prepareOperationsIntent({kind,viewer,id,canWrite=false,eligible=false}={}){const supported={claim:'RewardDistributor420.claim',appeal:'BongGogglesModerationAppealRegistry420.submitAppeal',report:'BongGogglesModerationRegistry420.submitReport'};if(!supported[kind])throw new Error('unsupported operation');if(!canWrite||!eligible)throw new Error('current Wallet and canonical eligibility required');return Object.freeze({kind,actor:field(viewer,'viewer',ADDRESS),referenceId:field(id,'reference id',ID),canonicalTarget:supported[kind],requiresQualifiedBinding:true,requiresWalletApproval:true,authoritative:false});}
