import {AIClient420} from './core/api.js';import {validateRuntimeConfig} from './core/config.js';import {buildAIRequestDraft,submissionGate} from './core/request.js';import {connectWallet420} from './core/wallet.js';
const $=s=>document.querySelector(s);const state={config:null,api:null,wallet:null,readiness:null,view:'home',draft:null};
const short=x=>x?x.length>18?x.slice(0,10)+'…'+x.slice(-8):x:'—';const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function loadConfig(){const r=await fetch('./runtime-config.json',{cache:'no-store'});if(!r.ok)throw new Error('runtime config '+r.status);state.config=validateRuntimeConfig(await r.json());$('#network').textContent=state.config.network.name;if(state.config.services.ai){state.api=new AIClient420(state.config.services.ai);state.readiness=await state.api.readiness();$('#api-status').textContent=state.readiness.ready?'API ready':'API degraded';$('#source').textContent=state.readiness.source||'derived';$('#block').textContent=state.readiness.observedBlock||'—';}}
function nav(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));}
function card(title,rows=[]){return `<article class="card"><h3>${esc(title)}</h3>${rows.map(([k,v])=>`<p><span class="label">${esc(k)}</span><br><span class="hash">${esc(v)}</span></p>`).join('')}</article>`;}
async function renderHome(){return `<div class="grid">${card('Protocol boundary',[['AI Job Manager',state.config.contracts.AIJobManager],['AI Escrow',state.config.contracts.AIJobEscrow]])}${card('Read architecture',[['API',state.config.services.ai||'not configured'],['Authority','non-authoritative derived views']])}${card('Write status',[['Request submission',state.config.features.writes?'enabled':'gated'],['Reason','Wallet transaction adapter qualification required']])}</div>`;}
async function renderProviders(){if(!state.api)return '<p class="muted">AI API endpoint is not configured.</p>';const p=await state.api.providers('?limit=50');return `<h2>Providers</h2><div class="grid">${p.items.map(x=>card(short(x.providerId),[['State',x.state],['Operator',x.operatorAccount],['Compute provider',x.computeProviderId],['Stake ref',x.stakeRef],['Source',x.meta?.source||p.meta?.source]])).join('')||'<p>No providers returned.</p>'}</div>`;}
async function renderModels(){if(!state.api)return '<p class="muted">AI API endpoint is not configured.</p>';const p=await state.api.models('?limit=50');return `<h2>Models</h2><div class="grid">${p.items.map(x=>card(short(x.modelId),[['Creator',x.creator],['Active',x.active],['Latest version',x.latestVersionId||'—'],['Metadata',x.metadataHash]])).join('')||'<p>No models returned.</p>'}</div>`;}
async function renderJobs(){if(!state.api)return '<p class="muted">AI API endpoint is not configured.</p>';const q=state.wallet?.account?`?requester=${encodeURIComponent(state.wallet.account)}&limit=50`:'?limit=50';const p=await state.api.jobs(q);return `<div class="toolbar"><div><h2>Jobs</h2><p class="muted">${state.wallet?.account?'Filtered to connected requester':'Showing public derived job discovery'}</p></div></div><table class="table"><thead><tr><th>Job</th><th>State</th><th>Model</th><th>Provider</th><th>Funded / max</th><th>Result</th></tr></thead><tbody>${p.items.map(x=>`<tr><td class="hash">${esc(short(x.jobId))}</td><td>${esc(x.state)}</td><td class="hash">${esc(short(x.modelVersionId))}</td><td class="hash">${esc(short(x.providerId))}</td><td>${esc(x.fundedAmount420)} / ${esc(x.maxSpend420)}</td><td class="hash">${esc(short(x.resultHash))}</td></tr>`).join('')}</tbody></table>`;}
function requestForm(){const gate=submissionGate({config:state.config,wallet:state.wallet,draft:state.draft});return `<h2>New AI request</h2><p class="muted">This creates a reviewable AIJobManager.createRequest intent. The prompt or private payload is not placed on-chain; only its commitment is referenced.</p><div class="form"><label>Job ID<input id="jobId" placeholder="0x… bytes32"></label><label>Model version<input id="modelVersionId" placeholder="0x… bytes32"></label><label>Workload<select id="workloadClass"><option>TEXT</option><option>MULTIMODAL</option><option>IMAGE</option><option>AUDIO</option><option>VIDEO</option><option>EMBEDDING</option><option>RERANK</option><option>FINE_TUNE</option><option>BATCH</option></select></label><label>Request commitment<input id="requestHash" placeholder="0x… bytes32"></label><label>Privacy policy ID<input id="privacyPolicyId" placeholder="0x… bytes32"></label><label>Verification profile ID<input id="verificationProfileId" placeholder="0x… bytes32"></label><label>Maximum spend (420 base units)<input id="maxSpend420" value="1"></label><label>Deadline (unix seconds)<input id="deadline"></label></div><button id="review" class="primary">Review request</button>${state.draft?`<h3>Reviewed canonical intent</h3><pre>${esc(JSON.stringify(state.draft,null,2))}</pre>`:''}<button id="submit" class="primary" ${gate.allowed?'':'disabled'}>Submit via Wallet</button><p class="${gate.allowed?'ok':'muted'}">${esc(gate.reason||'Ready for qualified wallet submission')}</p>`;}
async function renderOperator(){return `<h2>Provider console</h2><div class="grid">${card('Identity',[['Wallet',state.wallet?.account||'not connected'],['Provider registration','read through Providers view']])}${card('Runtime',[['Status','provider runtime exposed separately'],['Private keys','never stored in AI daemon']])}${card('Operations',[['Queue','requires provider runtime API transport'],['Receipts','canonical Compute receipts remain authoritative for lifecycle']])}</div><p class="muted">This console is intentionally observational in RECOVERY-5. Provider lifecycle writes belong to their owning registries and qualified transaction adapters.</p>`;}
async function render(){nav();$('#notice').textContent=state.api?(state.readiness?.ready?'AI API connected. Views below are derived and non-authoritative.':'AI API configured but not ready; canonical chain state must be used for decisions.'):'AI API is not configured in runtime-config.json; the shell remains fail-closed.';const v=$('#view');try{if(state.view==='providers')v.innerHTML=await renderProviders();else if(state.view==='models')v.innerHTML=await renderModels();else if(state.view==='jobs')v.innerHTML=await renderJobs();else if(state.view==='request')v.innerHTML=requestForm();else if(state.view==='operator')v.innerHTML=await renderOperator();else v.innerHTML=await renderHome();bind();}catch(e){v.innerHTML=`<p class="danger">View unavailable: ${esc(e.message)}</p>`;}}
function bind(){const review=$('#review');if(review)review.onclick=()=>{try{state.draft=buildAIRequestDraft({jobId:$('#jobId').value.trim(),modelVersionId:$('#modelVersionId').value.trim(),workloadClass:$('#workloadClass').value,requestHash:$('#requestHash').value.trim(),privacyPolicyId:$('#privacyPolicyId').value.trim(),verificationProfileId:$('#verificationProfileId').value.trim(),maxSpend420:$('#maxSpend420').value.trim(),deadline:Number($('#deadline').value)});render();}catch(e){$('#notice').textContent=e.message;}};}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.draft=null;render();});$('#connect').onclick=async()=>{try{state.wallet=await connectWallet420(globalThis.ethereum,state.config.network.chainId);$('#account').textContent=short(state.wallet.account);$('#network').textContent=`${state.config.network.name} · chain ${state.wallet.chainId}`;$('#connect').textContent='Connected';render();}catch(e){$('#notice').textContent=e.message;}};
loadConfig().catch(e=>{$('#notice').textContent='Configuration error: '+e.message;}).finally(render);
