import test from 'node:test';import assert from 'node:assert/strict';import {validateSoakEvidence,offlineNoGo,SCENARIOS,LongSoakError} from '../src/long-soak.mjs';
const t=1760000000000;
const sample=()=>({schemaVersion:'420-cmp-9-14-soak-v1',releaseSha:'sha-release-1234',deploymentManifest:'manifest-1234',chainId:'chain-420',startedAt:t,endedAt:t+86400000,environment:'FUNDED_LIVE_TESTNET',provenanceValidated:true,cmp913LiveQualified:true,finalizedReceiptsValidated:true,fundingConservationValidated:true,operatorSignoff:'operator-123',independentReview:'reviewer-456',scenarios:SCENARIOS.map(name=>({name,status:'PASS',evidenceRef:'artifact/'+name}))});
const bad=(x,c)=>assert.throws(()=>validateSoakEvidence(x),e=>e instanceof LongSoakError&&e.code===c);
test('no evidence gives NO-GO',()=>{assert.equal(offlineNoGo().qualified,false);bad(null,'RUN_METADATA')});
test('short synthetic soak and unapproved environment cannot qualify',()=>{let e=sample();e.endedAt=t+3600000;assert.equal(validateSoakEvidence(e).decision,'NO_GO');e=sample();e.environment='OFFLINE_FIXTURE';assert.equal(validateSoakEvidence(e).qualified,false)});
test('unqualified scientific demo and unverified provenance block GO',()=>{let e=sample();e.cmp913LiveQualified=false;assert.equal(validateSoakEvidence(e).qualified,false);e=sample();e.provenanceValidated=false;assert.equal(validateSoakEvidence(e).qualified,false)});
test('missing or duplicate scenario and fake PASS without evidence fail',()=>{let e=sample();e.scenarios.pop();bad(e,'SCENARIO_INVENTORY');e=sample();e.scenarios[1].name=e.scenarios[0].name;bad(e,'SCENARIO_INVENTORY');e=sample();e.scenarios[0].evidenceRef='';bad(e,'SCENARIO_EVIDENCE')});
test('soak failure, reorg/rebuild and lack of independent review remain NO-GO',()=>{let e=sample();e.scenarios.find(x=>x.name==='indexerReorg').status='FAIL';assert.equal(validateSoakEvidence(e).decision,'NO_GO');e=sample();e.independentReview=e.operatorSignoff;assert.equal(validateSoakEvidence(e).decision,'NO_GO')});
